export const SSO_CALLBACK_DISPATCH_LIMIT = 20;
export const SSO_CALLBACK_MAX_ATTEMPTS = 100;
export const SSO_CALLBACK_USER_AGENT = 'Mystia-SSO/1.0';
export const SSO_CALLBACK_TIMEOUT_MS = 5000;
export const SSO_CALLBACK_DELIVERY_MAX_ROWS = 10_000;
export const SSO_CALLBACK_DELIVERY_RETENTION_MS = 30 * 24 * 60 * 60 * 1000;
export const SSO_CALLBACK_FAILED_QUEUE_MAX_ROWS = 1000;
export const SSO_CALLBACK_FAILED_QUEUE_RETENTION_MS = 30 * 24 * 60 * 60 * 1000;

export const SSO_CALLBACK_CLAIM_LEASE_MS = SSO_CALLBACK_TIMEOUT_MS + 60_000;
export const SSO_CALLBACK_DELIVERY_CLEANUP_INTERVAL_MS = 60 * 60 * 1000;
export const SSO_CALLBACK_FAILED_QUEUE_CLEANUP_INTERVAL_MS = 60 * 60 * 1000;
