onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@parcel/watcher"
  - sharp
overrides:
  "@react-aria/interactions@^3.22.3": 3.22.2
patchedDependencies:
  "@heroui/use-aria-button": patches/@heroui__use-aria-button.patch
  "@heroui/use-aria-link": patches/@heroui__use-aria-link.patch
  next: patches/next.patch
publicHoistPattern:
  - "*@heroui/*"
  - "*eslint-plugin*"
  - color2k
  - glob
  - immer
  - postcss-load-config
  - zustand
