onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@parcel/watcher"
  - better-sqlite3
  - sharp
overrides:
  "@react-aria/interactions@^3.22.3": 3.22.2
  react-dom: $react-dom
publicHoistPattern:
  - "*@heroui/*"
  - "*eslint-plugin*"
  - color2k
  - glob
  - immer
  - postcss-load-config
  - zustand
