import { SYNC_NAMESPACE_MAP } from '../sync/constants';

export const KIBIBYTE = 1024;
export const MEBIBYTE = 1024 * KIBIBYTE;

export const MAX_ACCOUNT_JSON_BODY_BYTES = 128 * KIBIBYTE;

export const MAX_BACKUP_DATA_BYTES = 10 * MEBIBYTE;
export const MAX_BACKUP_UPLOAD_JSON_BODY_BYTES =
	MAX_BACKUP_DATA_BYTES + 64 * KIBIBYTE;

export const MAX_SYNC_CHANGE_BYTES = MEBIBYTE;
export const MAX_SYNC_JSON_BODY_BYTES =
	MAX_SYNC_CHANGE_BYTES * Object.keys(SYNC_NAMESPACE_MAP).length +
	16 * KIBIBYTE;

export const SEND_BEACON_SYNC_BODY_BYTES = 48 * KIBIBYTE;

const SERVER_ACTION_BODY_OVERHEAD_BYTES = 2 * MEBIBYTE;
export const SERVER_ACTION_BODY_SIZE_LIMIT_BYTES =
	Math.ceil(
		(Math.max(MAX_BACKUP_UPLOAD_JSON_BODY_BYTES, MAX_SYNC_JSON_BODY_BYTES) +
			SERVER_ACTION_BODY_OVERHEAD_BYTES) /
			MEBIBYTE
	) * MEBIBYTE;
export const SERVER_ACTION_BODY_SIZE_LIMIT: `${number}mb` = `${SERVER_ACTION_BODY_SIZE_LIMIT_BYTES / MEBIBYTE}mb`;
