import {Providers} from './providers';
import type {Metadata} from 'next';

import 'reset-css';
import './globals.scss';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="light">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
