import type { TLocale } from '@/shared/i18n/locale';

import { SITE_METADATA } from './metadata';

/**
 * @description Site-level SEO keywords per locale. Page metadata keeps the
 * first {@link SITE_KEYWORDS_LENGTH} entries and appends the current page's
 * record names, mirroring the historical Simplified Chinese composition.
 */
export const SITE_KEYWORDS_LENGTH = 18;

export const SITE_KEYWORDS_BY_LOCALE: Readonly<
	Record<TLocale, ReadonlyArray<string>>
> = {
	en: [
		"Touhou Mystia's Izakaya",
		"Touhou Mystia's Izakaya Assistant",
		'Mystia Assistant',
		'Mystia Izakaya wiki',
		'Mystia Izakaya guide',
		'Mystia Izakaya guest catalog',
		'special guests',
		'bond rewards',
		'spell card effects',
		'foods',
		'recipes',
		'beverages',
		'ingredients',
		'cookware',
		'decorations',
		'clothing',
		'records',
		'badges',
	],
	ja: [
		'東方夜雀食堂',
		'夜雀助手',
		'東方夜雀食堂 攻略',
		'夜雀食堂 攻略',
		'夜雀食堂 wiki',
		'夜雀食堂 図鑑',
		'レア客',
		'絆報酬',
		'スペルカード効果',
		'料理',
		'レシピ',
		'飲み物',
		'食材',
		'調理器具',
		'置物',
		'衣装',
		'レコード',
		'バッジ',
	],
	ko: [
		'동방야작식당',
		'밤참새 도우미',
		'동방야작식당 공략',
		'동방 야작식당 위키',
		'밤참새 도우미 도감',
		'레어 손님',
		'유대 보상',
		'스펠 카드 효과',
		'요리',
		'레시피',
		'음료',
		'재료',
		'조리도구',
		'장식품',
		'의상',
		'레코드',
		'배지',
		'세트 메뉴',
	],
	'zh-CN': SITE_METADATA.keywords,
	'zh-TW': [
		'夜雀助手',
		'夜雀食堂助手',
		'東方夜雀食堂助手',
		'夜雀食堂小助手',
		'東方夜雀食堂小助手',
		'夜雀輔助',
		'夜雀食堂輔助',
		'東方夜雀食堂輔助',
		'夜雀食堂輔助工具',
		'東方夜雀食堂輔助工具',
		'夜雀食堂百科',
		'東方夜雀食堂百科',
		'夜雀食堂wiki',
		'東方夜雀食堂wiki',
		'夜雀食堂攻略',
		'東方夜雀食堂攻略',
		'夜雀食堂圖鑑',
		'東方夜雀食堂圖鑑',
	],
};

export const META_MYSTIA_KEYWORDS_BY_LOCALE: Readonly<
	Record<TLocale, ReadonlyArray<string>>
> = {
	en: [
		'MetaMystia',
		"Touhou Mystia's Izakaya multiplayer",
		'Mystia Izakaya multiplayer',
		'Mystia Izakaya co-op',
		"Touhou Mystia's Izakaya mod",
		'Mystia Izakaya mod',
		'ResourceEx mod',
		'Mystia Izakaya new guests',
		'Mystia Izakaya skins',
	],
	ja: [
		'MetaMystia',
		'東方夜雀食堂 マルチプレイ',
		'夜雀食堂 マルチプレイ',
		'夜雀食堂 協力プレイ',
		'東方夜雀食堂 Mod',
		'夜雀食堂 Mod',
		'ResourceEx Mod',
		'夜雀食堂 レア客追加',
		'夜雀食堂 スキン',
	],
	ko: [
		'MetaMystia',
		'동방야작식당 멀티플레이',
		'동방야작식당 협동',
		'밤참새 도우미 멀티플레이',
		'동방야작식당 모드',
		'밤참새 도우미 모드',
		'ResourceEx 모드',
		'동방야작식당 레어 손님 추가',
		'동방야작식당 스킨',
	],
	'zh-CN': [
		'MetaMystia',
		'东方夜雀食堂联机',
		'夜雀食堂联机',
		'夜雀食堂多人',
		'东方夜雀食堂Mod',
		'夜雀食堂Mod',
		'ResourceEx内容扩展',
		'夜雀食堂新稀客',
		'夜雀食堂皮肤',
	],
	'zh-TW': [
		'MetaMystia',
		'東方夜雀食堂連線',
		'夜雀食堂連線',
		'夜雀食堂多人',
		'東方夜雀食堂Mod',
		'夜雀食堂Mod',
		'ResourceEx內容擴展',
		'夜雀食堂新稀客',
		'夜雀食堂皮膚',
	],
};
