import fs from 'fs';

// English translations for description keys batch 1 (keys 1-200)
const translations: Record<string, string> = {
  '0分！': '0 points!',
  '40分。': '40 points.',
  '60分。': '60 points.',
  'MC幻想乡的板娘，通过\u201C联动之门\u201D穿越过来的异世界人，同时也担当驻夜雀食堂的形象大使，不断邀请着夜雀食堂世界的居民去MC幻想乡做客，积极的推进着两边的生态发展中。': 'The hostess of MC Gensokyo who crossed over through the "Crossover Gate" from another world. She also serves as the resident ambassador of Mystia\'s Izakaya, constantly inviting residents of the Izakaya world to visit MC Gensokyo, actively promoting the development of both sides.',
  'XX大人应该没有吃过这个吧？': 'Lord XX probably hasn\'t tried this before, right?',
  '\u201C一般\u201D颠倒过来还是\u201C一般\u201D。': '"Average" reversed is still "average."',
  '\u201C天妇罗\u201D又名\u201C天麸罗\u201D。将新鲜大虾裹上面粉做的罗衣，放入油锅炸至金黄酥脆，再控油捞出，隔壁家的童子都馋哭了。': '"Tempura," also known as "tenpura." Fresh shrimp is coated in a flour batter and deep-fried until golden and crispy, then drained from the oil. Even the neighbor\'s kids are drooling over it.',
  '\u201C芝士上的洞都是被老鼠咬出来的\u201D这种谣言究竟是谁传出来的？': 'Who started the rumor that "the holes in cheese are bitten out by mice"?',
  '\u201C蓬松松爱莲♡魔法店\u201D发行的糖果型货币，是爱莲分享给大家的甜蜜。可以在\u201C蓬松松爱莲♡魔法店\u201D里换购商品。': 'Candy-type currency issued by the "Fluffy Ellen ♡ Magic Shop," a sweetness that Ellen shares with everyone. Can be used to exchange for goods at the "Fluffy Ellen ♡ Magic Shop."',
  '\u201C黑夜给了我们黑色的眼睛\u201D，不就是为了让人寻找黑暗嘛。': '"The night gave us dark eyes" — isn\'t that just for seeking out the darkness?',
  '…♡': '...♡',
  '…不堪入目。': '...Unbearable to look at.',
  '…咕嗯，确实十分美味…不得不承认雪那笨蛋在美食的品味这方面意外的有天赋呢。': '...Mm, it is indeed delicious... I have to admit that idiot Yuki has an unexpected talent when it comes to taste in food.',
  '…真是有意思的味道，回去之后我会推荐给雪的。': '...What an interesting flavor. I\'ll recommend it to Yuki when I get back.',
  '《东方夜雀食堂》在2021年获得国产游戏销量榜第17名，为感谢各位玩家的支持，特意制作了帅气的执事服以表谢意！未来还请多多指教！': '"Touhou Mystia\'s Izakaya" ranked 17th on the domestic game sales chart in 2021. To thank all players for their support, this handsome butler outfit was specially made as a token of gratitude! Please continue to support us in the future!',
  '【八重雾中渡】工作时会摸鱼，但顾客试图落座时会被立即拉到桌子旁。到【星熊勇仪】处泡温泉后，可使当晚工作时不会再摸鱼。': '[Eightfold Fog Crossing] Slacks off during work, but immediately pulls customers to their seats when they try to sit down. After visiting Hoshiguma Yuugi\'s hot spring, won\'t slack off for the rest of the evening.',
  '【分头行动】作为厨师时，赤蛮奇会分出两个头进行传菜和酒水工作；作为传菜或酒水时，会分出一个头进行另一项工作。移动速度随着头的数量减少而提升，工作速度随着头的数量减少而下降。同时，可受到【少名针妙丸】施加的\u201C万宝槌之力\u201D影响，使移动速度提高200%。': '[Split Action] As a chef, Sekibanki splits off two heads for serving and beverage duties; as a server or bartender, splits off one head for the other role. Movement speed increases as heads decrease, but work speed decreases. Can also be affected by Shinmyoumaru\'s "Miracle Mallet Power," increasing movement speed by 200%.',
  '【双人成行】召唤云山和自己一起工作。': '[Duo Journey] Summons Unzan to work together.',
  '【捕梦之网】依照顾客评价生成梦境能量，哆来咪吸收这些能量以提升自身制作料理的速度和返还食材的概率。': '[Dream Catcher\'s Net] Generates dream energy based on customer evaluations. Doremy absorbs this energy to increase her cooking speed and ingredient return rate.',
  '【时盛运旺】处于\u201C热火朝天\u201D状态时，萨拉将阻止普通顾客来店，并每隔一段时间从整个幻想乡随机邀请稀有顾客来店。': '[Fortune\'s Favor] While in the "Bustling" state, Sara will prevent regular customers from coming and periodically invite random rare customers from across Gensokyo.',
  '【钓瓶落之怪】驱赶普通顾客时不会受到不良影响，但会收不到钱。': '[Tsurube-otoshi] Driving away regular customers won\'t cause negative effects, but you won\'t receive payment.',
  '【鳞粉乃梦泉】每隔30秒，拉尔瓦会在场上播撒一次持续15秒的催眠粉。期间稀有顾客在用餐时会忘掉自己的点单，普通顾客会爱上\u201C昂贵\u201D标签并在用餐时返还当次消耗掉的料理预算。': '[Scales of the Dream Spring] Every 30 seconds, Larva scatters sleep powder lasting 15 seconds. During this time, rare customers forget their orders while dining, and regular customers fall in love with the "Expensive" tag while refunding the meal budget consumed.',
  '一个两个都往地上钻，地上真的那么有趣吗？': 'Everyone keeps going underground — is it really that interesting down there?',
  '一个人的礼貌是一面照出它肖像的镜子。': 'One\'s manners are a mirror reflecting their character.',
  '一会也带点回去给芙兰尝尝吧。': 'I should bring some back for Flan to try.',
  '一会儿吃完饭要给橙买木天蓼，给紫大人买吃的…': 'After eating, I need to buy matatabi for Chen and food for Lady Yukari...',
  '一会儿和妖精朋友们去哪里玩好呢…': 'Where should I go play with my fairy friends later...',
  '一切恶法，本是虚妄。': 'All evil is but an illusion.',
  '一本正经的谜之仙人。总觉得她和一般的仙人哪里不太一样…不过我也没见过别的仙人就是了。': 'A mysterious hermit who acts all serious. She feels somehow different from typical hermits... though I\'ve never met any other hermits myself.',
  '一朵朵绚丽烂漫的鲜花扎成的花束。花儿们以生命为代价也要完成的事，必须要对此付出敬意！': 'A bouquet of splendidly gorgeous flowers. What flowers accomplish at the cost of their lives deserves the utmost respect!',
  '一直以为座敷童子是地缚灵的一种，没想到这种认知是错误的。似乎只要依附在什么东西上，就可以到处往来的样子。对了，听说座敷童子会给店家带来好运，至少希望这个传言是真的呢。': 'I always thought Zashiki-warashi were a type of earthbound spirit, but turns out that was wrong. It seems like as long as they attach to something, they can go anywhere. By the way, I heard Zashiki-warashi bring good luck to establishments — I hope at least that rumor is true.',
  '一直以来小瞧地上了，这一趟来得值！': 'I\'ve been underestimating the surface all this time — this trip was worth it!',
  '一直活在后悔中是一种怎样的心情呢？如果时间可以重来，她就不会从捣药的工作中逃走了吗？那样她就会感到幸福吗？这些问题我都没能问出口…不过，与其徘徊在过去，还是向前看比较好吧？希望她有朝一日能得到真正的自由。': 'What does it feel like to live in constant regret? If time could be rewound, would she not have run away from her medicine-pounding job? Would that have made her happy? I couldn\'t bring myself to ask these questions... But rather than lingering in the past, it\'s better to look forward, right? I hope she finds true freedom someday.',
  '一直让灵梦小姐退治她也挺可怜的…总之要是经济宽裕的话，让她来店里也不是坏事，听说能看到她的话，就能获得一般人想象不到的幸运？': 'Having Reimu exterminate her all the time is kind of pitiful... Anyway, if finances allow, having her come to the shop isn\'t a bad thing. I heard that seeing her brings unimaginable luck?',
  '一种像花儿一样美丽的菌类。据说历代皇家贵族把银耳看作延年益寿之品，但在月都似乎很常见。这种看起来一尘不染的洁白，和月都的感觉很相衬。': 'A fungus as beautiful as a flower. Royalty throughout history have regarded snow fungus as a longevity tonic, but it seems quite common in the Lunar Capital. Its pristine whiteness suits the atmosphere of the Lunar Capital perfectly.',
  '一种大洋性洄游海鱼，但在幻想乡的河流湖泊可见。有点儿珍贵。': 'An oceanic migratory fish, but can be found in Gensokyo\'s rivers and lakes. Somewhat rare.',
  '一种常见的野菜。具有一定的毒性，不建议过量食用，并且食用前须焯水烹饪。': 'A common wild vegetable. Has some toxicity, not recommended to eat in excess, and must be blanched before cooking.',
  '一种洄游性海鱼，但却在幻想乡的河流湖泊随处可见。': 'A migratory sea fish, but can be found everywhere in Gensokyo\'s rivers and lakes.',
  '一种烤制面皮、内置红豆沙夹心的甜点。因由两块像铜锣一样的饼合起来的，故而得名铜锣烧。': 'A dessert with baked dough and red bean paste filling. Named "dorayaki" because it\'s made of two pancakes pressed together like gongs.',
  '一种药食两用植物。将薜荔籽浸泡后搓汁，冷藏后会凝固成晶莹剔透的胶状物，可以用来制作果冻和凉粉等，是消暑神品。': 'A dual-purpose medicinal and edible plant. Soaking and squeezing its seeds produces a juice that solidifies into a crystal-clear gel when refrigerated, used to make jelly and cold desserts — a perfect summer treat.',
  '一种高度洄游海鱼，但在幻想乡的河流湖泊可见。有点儿珍贵。': 'A highly migratory sea fish, but can be found in Gensokyo\'s rivers and lakes. Somewhat rare.',
  '一般来说遇到我们的Boss可以获得幸运呜撒！不过如果是在这里的话。': 'Normally, meeting our Boss brings luck, usa! But since we\'re here...',
  '一般般。': 'So-so.',
  '一般般吧。': 'Just so-so.',
  '一路走来真是辛苦你了。': 'You\'ve really worked hard to get here.',
  '一边担忧着人类，一边担忧着妖怪，真是伟大啊，所谓贤者就是指这样的存在吧？她似乎有着另一个形态，一个我应该没有见过的形态，但却又隐约觉得自己见过…': 'Worrying about humans while also worrying about youkai — how admirable. Is this what they call a sage? She seems to have another form, one I shouldn\'t have seen before, yet I vaguely feel like I have...',
  '一边是魔界辣椒汤底，一边是萝卜牛骨汤底，兼具红白两种汤汁的特色双锅牛肉。一家人，一个锅，两种口味团团圆圆，仿佛有了它就有家的气息。': 'One side is Makai chili broth, the other is radish and beef bone broth — a special dual-pot beef dish with both red and white soups. One family, one pot, two flavors in harmony, as if it brings the warmth of home.',
  '七色的优昙花很美，七色的料理感觉却很恶心呢。': 'Seven-colored Udumbara flowers are beautiful, but seven-colored cuisine feels nauseating.',
  '三个人一起坐…说实话有点挤啊…': 'Three people sitting together... honestly it\'s a bit cramped...',
  '三餐正常，四餐满意。': 'Three meals is normal, four meals is satisfying.',
  '上次从一个妖精手里抢到了和我一样高的向日葵诶。': 'Last time I snatched a sunflower as tall as me from a fairy.',
  '上白泽慧音利用学童们用剩下的布料缝制而成的衣裳。似乎是中国某个时代，女孩子开始读书时候穿的衣服。': 'An outfit sewn by Kamishirasawa Keine from leftover fabric from her students. Supposedly clothing girls wore when they started school in some era of China.',
  '上面写着\u201CWelcome Hell\u201D的字样，看起来像是什么流行品牌。': 'It says "Welcome Hell" on it — looks like some kind of trendy brand.',
  '下一次料理时没有成功完美演唱会使厨具炸毁，当晚无法使用，部分排队的顾客也会被吓得抱头鼠窜。': 'If the next cooking attempt doesn\'t achieve a perfect performance, the cookware will explode, becoming unusable for the evening. Some queuing customers will also flee in panic.',
  '下一次没有成功完美演唱的料理，将会引来天雷，击晕一位伙伴30秒。': 'If the next dish isn\'t cooked with a perfect performance, it will summon lightning, stunning a partner for 30 seconds.',
  '下次叫上觉大人一起来吧。': 'Let\'s bring Lady Satori along next time.',
  '下次要不要把我家的猫咪们也带过来呢？': 'Should I bring my cats along next time?',
  '不劳者不得食，我是不是也该做点什么呢？': 'No work, no food — maybe I should do something too?',
  '不可以欺负人哟，小麻雀。': 'No bullying allowed, little sparrow.',
  '不同花色的我们性格其实也有点不同。': 'We with different suit colors actually have slightly different personalities.',
  '不堪一试！这种水平也敢开店？': 'Pathetic! You dare open a shop at this level?',
  '不够的钱等我下次化缘回来再补上吧。': 'I\'ll make up the rest of the money when I come back from my next alms round.',
  '不小心超过预算了…要不，免费让你去我那儿修炼作为补偿吧。': 'I accidentally went over budget... How about free training at my place as compensation?',
  '不想上课啊…偷偷跑出来不会被慧音老师发现吧？': 'I don\'t want to go to class... Sneaking out won\'t be noticed by Teacher Keine, right?',
  '不想成为别人的盘中餐，就好好做好盘中餐吧。': 'If you don\'t want to become someone else\'s meal, then make the meal well.',
  '不愧是我冒着被刀子扎的风险也要来吃的菜。': 'As expected of a dish worth risking getting stabbed over.',
  '不愧是风靡幻想乡的食堂，多谢款待！': 'As expected of the restaurant taking Gensokyo by storm — thanks for the meal!',
  '不是自己做的饭吃起来就是没有心理负担呢。': 'Food you didn\'t cook yourself just tastes guilt-free, doesn\'t it?',
  '不是说要为我准备健康料理吗？': 'Didn\'t you say you\'d prepare healthy food for me?',
  '不浪费食物是我的底线。': 'Not wasting food is my bottom line.',
  '不温不火的水平呢。': 'A lukewarm level of skill.',
  '不玩就不玩，那么大脾气做什么嘛。': 'If you don\'t want to play, fine — but why throw such a tantrum?',
  '不知腐鼠成滋味，猜意鹓雏竟未休。': 'Not knowing the taste of rotten rats, yet endlessly guessing what the phoenix desires.',
  '不知道从哪儿流入的外来食材，坚硬的外壳下有美味的果肉和丰富的汁水。': 'A foreign ingredient from who knows where, with delicious flesh and rich juice beneath its hard shell.',
  '不知道从哪里流入的外来食材，较为常见。': 'A foreign ingredient from who knows where. Fairly common.',
  '不知道这家店的食物做得有没有我的烤红薯好吃呢？': 'I wonder if this shop\'s food is as good as my roasted sweet potatoes?',
  '不知道那位小姐在地上过得怎么样呢。': 'I wonder how that lady is doing in the world above.',
  '不老不死只意味着，永不得救赎的孤独。': 'Immortality only means eternal loneliness without redemption.',
  '不能太耽于口腹之欲。': 'One mustn\'t overindulge in culinary pleasures.',
  '不能带苏格拉底进来吗？': 'Can\'t I bring Socrates in?',
  '不能理解的事情就不要去理它，要不然在幻想乡可活不下去。': 'Don\'t bother trying to understand things you can\'t — otherwise you won\'t survive in Gensokyo.',
  '不要在花田里留下垃圾哦！': 'Don\'t leave trash in the flower fields!',
  '不要放过每一个客人，给我好好赚钱还债啊！': 'Don\'t let a single customer go — earn money and pay off the debt!',
  '不要的指甲可以给我哦。': 'You can give me your unwanted nails.',
  '不要紧张，把我视为普通客人就好了哟。': 'Don\'t be nervous — just treat me as a regular customer.',
  '不要随地乱扔烟蒂啊。': 'Don\'t litter cigarette butts everywhere.',
  '不要！我已经没有金币给你了！': 'No! I have no more gold coins for you!',
  '不过，老板娘你一定不止于此对吧。': 'But you\'re not going to stop here, are you, boss lady?',
  '不进则退，不得则亡。': 'Fall behind and you retreat; fail to gain and you perish.',
  '不错哟！我的船正缺一位你这样的厨娘。': 'Not bad! My ship is in need of a cook like you.',
  '不错的下酒菜！': 'Great drinking snack!',
  '不错，凭着去时走错路的经验，回来时就顺利了。': 'Not bad — thanks to getting lost on the way there, the return trip was smooth.',
  '不错，可以有90分。': 'Not bad — that\'s a 90-point dish.',
  '不错，难怪享有盛名。': 'Not bad — no wonder it has such a reputation.',
  '与其说是凶兆的黑猫，不如说是凶巴巴的黑猫…': 'Rather than a black cat of ill omen, more like a fierce black cat...',
  '与火为伴的厨子生活说不定挺适合吾…': 'A cook\'s life alongside fire might actually suit me...',
  '世上最实在的食材！不仅香甜软糯，而且能强效地应对饥饿，在冬天还有暖手的效果。': 'The most down-to-earth ingredient! Not only sweet and soft, but also highly effective against hunger, and even warms your hands in winter.',
  '业火随机烧掉三个Buff纸张，其带来的效果也会随之失效。': 'Hellfire randomly burns three buff slips, and their effects will also be lost.',
  '中场休息！捉迷藏什么的吃饱再继续玩吧。': 'Halftime break! Let\'s eat before continuing the hide-and-seek game.',
  '中断Combo，且在30秒内无法再获得Combo。': 'Breaks the combo and prevents gaining another combo for 30 seconds.',
  '丰姬从当地出没的稀有顾客以及当晚邀请的稀有顾客中随机选择三个还未出现的顾客，使她们\u201C神隐\u201D，今晚无法前来夜雀食堂。': 'Toyohime randomly selects three rare customers who haven\'t appeared yet from both local and invited rare customers, spiriting them away so they cannot visit the Izakaya tonight.',
  '丰姬大人桃子吃得太多了。': 'Lady Toyohime eats way too many peaches.',
  '丰姬小姐真是相当——相当喜欢桃子，以及相当——相当优哉游哉。像她这么强大的人，真的可以这样什么都不用操心吗？无论在什么环境下都能活得这么天真，这应该也算是一种能力吧？': 'Miss Toyohime really, really loves peaches, and is really, really carefree. Can someone as powerful as her truly afford to worry about nothing? Being able to live so innocently in any environment — that\'s a talent in itself, isn\'t it?',
  '丰姬连接海和山，链接幻想乡的一个地点，使该区域的普通顾客和稀有顾客可以穿越\u201C面\u201D前来。通过丰姬的能力链接的地区刷新效果分别独立，刷新速率为原先的33%。': 'Toyohime connects sea and mountain, linking a location in Gensokyo so that regular and rare customers from that area can cross through the "boundary." Linked areas refresh independently at 33% of the original rate.',
  '为、为什么啊…': 'Wh-why...',
  '为了不让厄运转移到人类身上而收集厄运的厄神。虽然名字里有个神，但其实和我一样是妖怪。明明是妖怪却满心满意为人类着想，真不可思议。这样的她还要遭受人类的排斥，实在太可怜了。最近为了进行抑制厄的修行而到夜雀食堂打工。': 'A misfortune goddess who collects misfortune to prevent it from transferring to humans. Despite having "goddess" in her title, she\'s actually a youkai like me. A youkai who wholeheartedly thinks of humans — how strange. That such a person is still shunned by humans is truly pitiful. Recently she\'s been working at the Izakaya for training in suppressing misfortune.',
  '为了来你这里就餐，我连身边的黑暗都减弱了。': 'To dine at your place, I even reduced the darkness around me.',
  '为了演唱会特意赶制的\u201C鸟兽伎乐\u201D乐队演出服。': 'A performance outfit hastily made for the "Choujuu Gigaku" band concert.',
  '为了虫族的复兴！现在我们推出\u201C昆虫的通知\u201D——为什么要让我闭嘴！': 'For the revival of the insect race! Now presenting "Insect Notification" — why are you telling me to shut up!',
  '为什么不能和平相处呢？': 'Why can\'t we just get along?',
  '为什么不让我吃啦？': 'Why won\'t you let me eat?',
  '为什么其他顾客都要重新排队？好哦，那我也去重新排队吧！': 'Why do all the other customers have to line up again? Okay, I\'ll go line up again too!',
  '为什么吃饭要付钱啊？': 'Why do I have to pay for food?',
  '为什么隔壁的菜看起来那么美味，我好嫉妒啊…': 'Why does the food at the next table look so delicious? I\'m so jealous...',
  '主要由土豆制成的，外表酥脆，内在绵软可口，在油炸类食品中有着较高的人气。': 'Mainly made from potatoes, crispy on the outside and soft inside. Quite popular among fried foods.',
  '久违地出来吃饭了呢…': 'It\'s been a while since I went out to eat...',
  '之前太失礼了，老板娘能不计前嫌真是太好了。': 'I was so rude before — I\'m glad the boss lady doesn\'t hold grudges.',
  '之后该怎么办呢。': 'What should I do after this?',
  '乌冬？听起来很有亲切感呜撒！会很好吃吧！': 'Udon? That sounds so familiar, usa! It must be delicious!',
  '乌鸦曾经也是被供奉的神鸟，一朝走下神坛就成了不祥之鸟。': 'Crows were once revered as sacred birds, but once they fell from grace, they became birds of ill omen.',
  '也就和船上的备用食物差不多。': 'About the same as backup food on the ship.',
  '也就这样吧。': 'Well, that\'s about it.',
  '也就这种程度吧。': 'That\'s about all it amounts to.',
  '也就那么回事吧。': 'It is what it is.',
  '也没比我做的好多少嘛。': 'It\'s not much better than what I make.',
  '也罢。我已经习惯了。': 'Whatever. I\'m used to it.',
  '买卖不公者终堕刀锯地狱。': 'Those who trade unfairly shall fall into the Hell of Saws.',
  '享受美食的时间是最快乐的。': 'Time spent enjoying good food is the happiest.',
  '人和妖怪原来可以以这种方式达成平衡吗…': 'So humans and youkai can achieve balance in this way...',
  '人生得意须尽欢，胡吃海塞需尽兴。': 'When life is good, enjoy it to the fullest; when feasting, eat to your heart\'s content.',
  '人类什么的，我真是受够了。': 'I\'m so sick of humans.',
  '人类光是遇到我，就已经花光所有的运气了。': 'Just encountering me has already used up all of a human\'s luck.',
  '人类可能不太了解，但我知道…命莲寺的修行僧几乎都是妖怪。虽说也会进行什么六个菠萝蜜的修行，但谁也没看出究竟有什么效果，不少妖怪在修行之外依然我行我素。': 'Humans might not know this, but I do... almost all of Myouren Temple\'s monks are actually youkai. Though they practice the six paramitas or whatever, nobody can tell what effect it has — many youkai still do as they please outside of training.',
  '人类啊，好好珍惜活着的幸福吧。': 'Humans, cherish the happiness of being alive.',
  '人类就是喜欢以貌取人的生物！': 'Humans are creatures that just love judging by appearances!',
  '人类村子中的名门望族，编撰《幻想乡缘起》的稗田家家主，是个了不起的大小姐。': 'Head of the prestigious Hieda clan in the human village, the compiler of "The Chronicles of Gensokyo." A remarkable young lady.',
  '人类的长者充其量也不过活了几十年罢了，对我们妖怪来说是很短的岁月。但是有些老人身上似乎有种仙人般的气质…偶尔听听老人的话，应该也不会吃亏吧。': 'Human elders have only lived a few decades at most — a very short time for us youkai. But some elders seem to have an almost sage-like quality... It wouldn\'t hurt to heed their words once in a while.',
  '人类长寿一些难道是什么罪过吗？': 'Is it a sin for humans to live a little longer?',
  '人而无礼，胡不遄死！': 'A person without manners might as well perish!',
  '人里供应的鸡蛋，较为常见。': 'Eggs supplied from the human village. Fairly common.',
  '人里农田产的南瓜，较为常见。': 'Pumpkins from the human village farms. Fairly common.',
  '人里农田产的洋葱，较为常见。': 'Onions from the human village farms. Fairly common.',
  '人里农田产的萝卜，较为常见。': 'Radishes from the human village farms. Fairly common.',
  '人里圈养的家猪肉，较为常见。': 'Domesticated pork from the human village. Fairly common.',
  '人里圈养的肉牛肉，较为常见。': 'Domesticated beef from the human village. Fairly common.',
  '人里有卖的豆腐，较为常见。': 'Tofu sold in the human village. Fairly common.',
  '人间之里产的食材，十分常见。传闻对吸血鬼有独特的杀伤力。': 'An ingredient from the human village. Very common. Rumored to be uniquely deadly to vampires.',
  '人间之里产的食材，十分常见。作为调味品或是直接吃都是个不错的选择。': 'An ingredient from the human village. Very common. Good as a seasoning or eaten directly.',
  '人间之里产的食材，十分常见。既可以作为主食，也可以拿来煲汤。': 'An ingredient from the human village. Very common. Can serve as a staple food or be used in soups.',
  '人间之里古书店\u201C铃奈庵\u201D的店员以及店主之女。对妖怪怀有不可思议的热忱且很有主见，以强势的态度跑到夜雀食堂来打工，是个奇怪的人类小女孩。': 'A clerk at the old bookstore "Suzunaan" in the human village, and the shop owner\'s daughter. She has a mysterious enthusiasm for youkai and is very opinionated. She came to work at the Izakaya with a forceful attitude — a strange little human girl.',
  '人间之里当然是只有人类的村子啦！嗯？你那个怀疑的眼神是怎么回事？': 'The human village is of course a village with only humans! Hm? What\'s with that suspicious look?',
  '人间之里散落的有些年代感的铜钱，似乎已经不再流通。': 'Old copper coins scattered around the human village. They seem to no longer be in circulation.',
  '人间之里的人类自酿的梅子酒。因为喝起来很甜，所以经常有不了解它的生物被它的后劲儿击倒。': 'Plum wine home-brewed by humans in the human village. It tastes sweet, so creatures unfamiliar with it often get knocked out by its delayed kick.',
  '人间烟火气，最抚凡人心。': 'The warmth of everyday life soothes the mortal heart.',
  '人间界的待客之道真是让我大开眼界，我们恐怕要后会无期了。': 'The hospitality of the mortal world has truly opened my eyes. I\'m afraid we may never meet again.',
  '什么叫黑心老板娘啊，我们算是见识了！': 'So this is what they call a black-hearted boss lady — now we\'ve seen it for ourselves!',
  '什么时候我也能像妹妹那样子受欢迎呢。': 'When will I be as popular as my little sister?',
  '什么黑店！太子大人给的家用竟然堪堪支付一顿饭钱？！': 'What a rip-off! The allowance from the Crown Prince barely covers one meal?!',
  '仅在桥附近特别的树上产出的奇怪果实，据说没有人能够无表情板着脸吃完一整颗，有着强大的\u201C酸\u201D味，只能取其果汁来调味。': 'A strange fruit that only grows on special trees near bridges. They say no one can eat a whole one with a straight face due to its incredibly sour taste — only its juice can be used for seasoning.',
  '今夜的月亮比昨夜的更明亮。': 'Tonight\'s moon is brighter than last night\'s.',
  '今天也好累啊…': 'Today was tiring too...',
  '今天也是就这样过去了吗…': 'Is today going to pass just like this too...',
  '今天又因为扎针的时候下手太重被客人投诉了…': 'Got another complaint today for pressing too hard with the needle...',
  '今天又没有吓到人…': 'Didn\'t manage to scare anyone again today...',
  '今天天气不错…不过以前有段时间天气很糟糕，一会起雾一会地震一会冰雹的。': 'Nice weather today... though there was a period when the weather was awful — fog, earthquakes, and hail all at once.',
  '今天没有闹事的吧？发生什么要及时告诉我。': 'Nobody caused trouble today, right? Tell me immediately if anything happens.',
  '今天的第五顿饭启动！': 'Fifth meal of the day, go!',
  '今天的素材也不太能用呢…': 'Today\'s materials aren\'t very usable either...',
  '今天送来的怨灵有点多啊。': 'There are a lot of vengeful spirits delivered today.',
  '今天遇到的那个神社的巫女真的好可怕啊。': 'That shrine maiden I met today was really scary.',
  '今天那局棋真是恰逢敌手啊。这样才有意思！': 'Today\'s chess match was a perfect match of rivals. That\'s what makes it fun!',
  '今年的季节很正常呢，真是难得。': 'The seasons are normal this year — how rare.',
  '今日的执著，会造成明日的后悔。': 'Today\'s obsession will become tomorrow\'s regret.',
  '从不尽的火诞生的，是无论多少次都会复活的不死鸟。': 'Born from the eternal flame — the immortal phoenix that revives no matter how many times it falls.',
  '从位于博丽神社的守矢分社中离奇获得的服饰，似乎在外界很流行。': 'An outfit mysteriously obtained from the Moriya branch shrine at the Hakurei Shrine. Seems to be popular in the outside world.',
  '从外侧看平平无奇，但是内侧却有着点点星辰，非常神奇甚至中二感满满的披风！作为妖怪，被夜空包裹会有种奇妙的安心感。': 'An ordinary-looking cape from the outside, but with twinkling stars on the inside — a very magical, even chuunibyou-esque cape! As a youkai, being wrapped in the night sky gives a strange sense of comfort.',
  '从守矢小神社中摇出的银色青蛙硬币。持有一百枚时将自动获得衣服【水手服】和物品【金色的青蛙硬币】。': 'A silver frog coin shaken from the small Moriya Shrine. Holding one hundred will automatically grant the outfit [Sailor Uniform] and the item [Golden Frog Coin].',
  '从幻昙华中提取色素，给一个个蘑菇伞染上颜色，将之铺在宝箱周围就像被锦花簇拥着。宝箱里究竟藏有什么惊喜呢？怀着这样的想法打开，跳出来的却是伸着大舌头的滑稽的伞！吓一跳了吧——？': 'Extracting pigments from Fantasy Flowers to dye mushroom umbrellas and arranging them around treasure chests like clusters of colorful flowers. What surprise could the chest hold? Opening it with such anticipation, out pops a funny umbrella sticking out its tongue! Gave you a scare, didn\'t it?',
  '从海难中逃到荒岛的幸存者，万般无奈地将已被海水浸湿的面粉和芝士混合成的\u201C面糊\u201D放在阳光下烤，没想到味道变得十分香脆可口。于是这个做法流传了下来。': 'Survivors who escaped to a deserted island after a shipwreck had no choice but to bake the "batter" of seawater-soaked flour and cheese in the sun. Surprisingly, it turned out crispy and delicious, and the recipe was passed down.',
  '从酒柜里偷走三瓶最高级的酒。': 'Steals three bottles of the finest liquor from the liquor cabinet.',
  '从野外采回来的竹笋，较为常见。': 'Bamboo shoots gathered from the wild. Fairly common.',
  '从魔法森林采回来的品相良好的松露，无法人工种植，非常珍贵。': 'Fine truffles gathered from the Forest of Magic. Cannot be cultivated artificially. Very precious.',
  '从魔法森林采回来的品相良好的蘑菇，无法人工种植，非常珍贵。': 'Fine mushrooms gathered from the Forest of Magic. Cannot be cultivated artificially. Very precious.',
  '仔细想想，人类刚死掉的时候，应该会茫然吧？如果能在猝然长辞之际遇到开朗善谈的阿燐，或许能中和一些对死亡的恐惧。': 'Come to think of it, humans must feel bewildered right when they die, right? If they could meet the cheerful and talkative Orin at the moment of passing, perhaps it would ease some of their fear of death.',
  '仙人也不是只吃\u201C霞\u201D的。': 'Even hermits don\'t only eat "mist."',
  '仙人说话都是这样一板一眼吗？和她对话有种挨训的感觉…不过能让主食霞的仙人来自己的店里光顾，还是挺有成就感的。': 'Do all hermits talk so formally? Talking with her feels like being scolded... But having a hermit who mainly eats mist come to my shop is quite an accomplishment.',
  '代替红美铃守护夜雀食堂的熊猫，全身黑白分明，据说是个集万千宠爱于一身的国宝…这样的话，是我守护它才对吧？！': 'A panda guarding the Izakaya in place of Hong Meiling, with distinct black and white markings. Said to be a national treasure beloved by all... In that case, shouldn\'t I be the one guarding it?!',
  '令全场除自身以外的顾客的厌恶标签反转为喜好标签，持续30秒。当场上包括排队顾客在内的普通顾客数量之和不少于7时，此符卡转化为\u201C逆弓「天壤梦弓的诏敕」\u201D。': 'Reverses all customers\' (except self) disliked tags to liked tags for 30 seconds. When there are 7 or more regular customers on the floor including those in queue, this spell card transforms into "Reverse Bow: Decree of the Celestial Dream Bow."',
  '以为有了盔甲就可以横行霸道的八脚笨蛋，只需最简单的清蒸就能成为究极美味！不过要小心它的钳子…': 'The eight-legged fool that thinks it can run rampant with its armor — the simplest steaming turns it into an ultimate delicacy! But watch out for its claws...',
  '以南瓜做的船，承载着如梦似幻的食材，在莲子铺成的河上驶入幻想。据说每每享用完这道料理，都会有如梦方醒的感觉。至于究竟是何种梦境，便是因人而异了。': 'A ship made of pumpkin, carrying dreamlike ingredients, sailing into fantasy on a river of lotus seeds. They say eating this dish always leaves you feeling like you\'ve just woken from a dream. As for what kind of dream — that varies from person to person.',
  '以无意识妖怪的帽子为原型制作的深沉甜食，即使切开感受到的也是无尽的黑暗，但香醇的程度令人流连忘返。': 'A deep, dark dessert modeled after an unconscious youkai\'s hat. Even when sliced, all you feel is endless darkness, yet its richness is utterly unforgettable.',
  '以毒攻毒最美味了！': 'Fighting poison with poison is the most delicious!',
  '以海鲜汤料煨煮的汤面，劲道爽滑，汤浓鲜美，是一道非常豪华的家常菜。凭一碗海鲜面，便能让人记住深藏着的大海的味道。': 'Noodles simmered in seafood broth — springy, smooth, with a rich and savory soup. A very luxurious home-style dish. A single bowl of seafood noodles can remind you of the deep flavors of the sea.',
  '以牛肉、竹笋为主要食材的一道家常菜品。鲜嫩的竹笋炖肉具有开胃、促进消化的作用，再以竹子作为摆盘，可谓是色香味俱全。': 'A home-style dish with beef and bamboo shoots as the main ingredients. Tender bamboo shoots stewed with meat stimulate the appetite and aid digestion. Presented on bamboo, it\'s a feast for the eyes, nose, and tongue.',
  '以猩红恶魔头上的帽子为原型制作的梦幻甜食，切开会有仿佛血液一般的甜美酱料流出。': 'A dreamy dessert modeled after the Scarlet Devil\'s hat. When cut open, a sweet sauce that resembles blood flows out.',
  '以猪肉作为主要食材制作而成的家常菜，口味偏重。': 'A home-style dish made primarily with pork. Rich in flavor.',
  '以糯米为主料、辅以松子制作的药膳。松子糕的粉质细腻，柔软可口，并有清香的松子味，深受道士们喜爱。': 'A medicinal dish made primarily with glutinous rice and pine nuts. Pine nut cake has a fine, delicate texture, is soft and delicious, with a fragrant pine nut flavor — a favorite among Taoist priests.',
  '以花卉为主题的双层奶油蛋糕。锦簇花团铺在细腻的奶油上，散发出丝丝香甜，蓝色的蝴蝶轻轻驻足，久久不归。这不是梦境，却胜似梦境。': 'A flower-themed double-layer cream cake. Clusters of blooms rest on the delicate cream, emanating wisps of sweetness. A blue butterfly gently alights, lingering endlessly. This isn\'t a dream, yet it surpasses one.',
  '以选用孔庙\u201C诗礼堂\u201D前银杏树所结果实烹制而得名，清香甜美，柔韧筋道，可解酒止咳。': 'Named after being prepared with fruits from the ginkgo trees in front of the Confucian Temple\'s "Hall of Poetry and Rites." Fragrant and sweet, chewy and elastic, it can relieve hangovers and suppress coughs.',
  '以金枪鱼高汤制作的饼身清透干净，和新鲜海胆组成高级的香槟色系搭配，底层的胡麻酱更增一丝醇厚的口感。如此玲珑的甜品，让人不忍破坏这晶莹剔透的美丽。': 'The shell made with tuna broth is clear and clean, paired with fresh sea urchin in an elegant champagne-colored combination. The sesame paste at the bottom adds a touch of richness. Such an exquisite dessert that one can\'t bear to break its crystal-clear beauty.',
};

// Apply translations
let content = fs.readFileSync('app/data/i18n/en.ts', 'utf8');
let count = 0;
for (const [key, value] of Object.entries(translations)) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`('${escaped}':\\s*)'',`, 'g');
  const newContent = content.replace(regex, `$1'${value.replace(/'/g, "\\'")}',`);
  if (newContent !== content) {
    count++;
    content = newContent;
  }
}
fs.writeFileSync('app/data/i18n/en.ts', content);
console.log(`Updated ${count} translations in app/data/i18n/en.ts`);
console.log(`Expected: ${Object.keys(translations).length}`);
