/**
 * Fill English translations for "Other" category (272 keys).
 * These include: spell card names, customer preference descriptions,
 * and miscellaneous game strings.
 *
 * Run: npx tsx scripts/fillEnOther.ts
 */
import { readFileSync, writeFileSync } from 'fs';

const enTranslations: Record<string, string> = {
	// === Spell card names (keep 「」 brackets, translate content) ===
	'"灵符「梦想封印」': '"Spirit Sign "Fantasy Seal"',
	'"唰"': '"Whoosh"',
	'「NOver say no to pOnda」': '「NOver say no to pOnda」',
	'「不玩尽兴还想走?!」': '「Not Done Having Fun Yet?!」',
	'「人与妖的梦乡」': '「Dreamland of Humans and Youkai」',
	'「传奇的格列佛」': '「The Legendary Gulliver」',
	'「全人类的绯想天」': '「Scarlet Weather Rhapsody of All Humankind」',
	'「八衢潮流风靡幻想」': '「Yachimata Trend Sweeping Fantasy」',
	'「决斗Spark!!!」': '「Duel Spark!!!」',
	'「刚欲兽神饕餮的晚餐」': '「Dinner of the Greedy Beast God Taotie」',
	'「加料加量不加价」': '「Extra Portions, Same Price」',
	'「呜撒的猫咪」': '「Orin\'s Kitty」',
	'「和人偶一起玩的孩子」': '「The Child Who Plays with Dolls」',
	'「地下偶像狂欢夜」': '「Underground Idol Party Night」',
	'「地狱的托卡马克装置」': '「Hell\'s Tokamak Device」',
	'「墨染浮櫻化醉蝶」': '「Ink-Dyed Floating Cherry Blossoms, Drunken Butterfly」',
	'「天狗例行小酌」': '「Tengu\'s Routine Drink」',
	'「天罚的石柱」': '「Pillar of Divine Punishment」',
	'「嫉妒与透支」': '「Jealousy and Overdraft」',
	'「幽冥的轮回」': '「Cycle of the Netherworld」',
	'「恋爱的糖果屋」': '「Candy House of Love」',
	'「惩罚无良商家的最好办法」': '「The Best Way to Punish Unscrupulous Merchants」',
	'「戒严令」': '「Martial Law」',
	'「扶我起来，我还能吃」': '「Help Me Up, I Can Still Eat」',
	'「接着奏乐接着舞」': '「Keep Playing, Keep Dancing」',
	'「断恶修善的禁欲考验」': '「The Ascetic Trial of Renouncing Evil for Good」',
	'「月免的篝火盛宴」': '「Moon Rabbit\'s Bonfire Feast」',
	'「死灰复燃」': '「Rekindled Embers」',
	'「永夜归返 世间开明」': '「Return from Eternal Night, Dawn of the World」',
	'「渎神的代价」': '「The Price of Blasphemy」',
	'「猛兽的艺术用法」': '「The Artistic Use of Beasts」',
	'「现与隐的境界」': '「The Boundary of Visible and Hidden」',
	'「甜美的冰霜小妖精」': '「Sweet Little Frost Fairy」',
	'「百万鬼夜行」': '「Night Parade of a Million Demons」',
	'「笔枪纸弹禁制之道」': '「Way of Sealing with Pen-Spears and Paper-Bullets」',
	'「自在极意无意识」': '「Ultra Instinct Unconsciousness」',
	'「自我极意无意识」': '「Self Ultra Instinct Unconsciousness」',
	'「船灵流连不散」': '「The Ship Spirit Lingers On」',
	'「花鸟风月群芳沐」': '「Flowers, Birds, Wind, and Moon Bathed in Blossoms」',
	'「虚构的情报」': '「Fabricated Intelligence」',
	'「超级巨幻影唐伞」': '「Super Giant Phantom Karakasa」',
	'「遗落的水晶鞋」': '「The Lost Glass Slipper」',
	'「酒醉迷乱」': '「Drunken Delirium」',
	'「食堂风起厨神无双」': '「Rising Storm at the Eatery, Peerless Chef」',
	'「食物瞬间消失术」': '「Instant Food Vanishing Trick」',
	'「饕餮的饕餮之宴」': '「Taotie\'s Feast of Gluttony」',
	'「饭要一口一口吃才健康」': '「Eating Slowly is Healthy」',
	'「香霖堂购物节」': '「Kourindou Shopping Festival」',
	'「魔卡小狸十股变化」': '「Magic Card Tanuki Tenfold Transformation」',

	// === Preferences / short phrases ===
	'一点点怀念': 'A little nostalgic',
	'三分饱': 'Only a third full',
	'三种神器「乡」': 'Three Sacred Treasures "Land"',
	'三种神器「剑」': 'Three Sacred Treasures "Sword"',
	'三种神器「玉」': 'Three Sacred Treasures "Jewel"',
	'三种神器「镜」': 'Three Sacred Treasures "Mirror"',
	'不健康的饮食': 'Unhealthy diet',
	'不可磨灭的过去': 'An indelible past',
	'不可能实现': 'Impossible to achieve',
	'不同地方的美食': 'Cuisine from different places',
	'不喝酒': 'No alcohol',
	'不多吃点': 'Not eating more',
	'不死「火鸟 凤翼天翔」': 'Immortal "Fire Bird -Phoenix Wings Soaring-"',
	'不能受热': 'Cannot stand heat',
	'不能吃不饱': 'Must eat until full',
	'不要油手碰花': 'Don\'t touch flowers with greasy hands',
	'不要让血液冷下来': 'Don\'t let the blood cool down',
	'不那么死气沉沉': 'Not so lifeless',
	'丑拒': 'Ugly, refused',
	'世界好美': 'The world is beautiful',
	'中等浓度的酒': 'Medium-strength alcohol',
	'丰盛的大餐': 'A hearty feast',
	'些许疲惫': 'A little tired',
	'人家是狼': 'I\'m a wolf, you know',
	'从胃里降温': 'Cool down from the stomach',
	'仙符「凤凰卵」': 'Immortal Sign "Phoenix Egg"',
	'令后人传诵的功绩': 'Achievements praised by posterity',
	'以前的时光': 'Times of the past',
	'价格高昂': 'Expensive price',
	'传薪「浴火捏盘」': 'Legacy "Forging Plates in Fire"',
	'低浓度的酒': 'Low-strength alcohol',
	'低级趣味': 'Vulgar taste',
	'佐渡老家': 'Hometown in Sado',
	'佐酒的小菜': 'Side dishes for drinks',
	'作为稗田家主': 'As the head of the Hieda family',
	'充满勇气的故事': 'A story full of courage',
	'兔子的胃很小': 'A rabbit\'s stomach is small',
	'入我相机': 'Into my camera',
	'入魔「走火入魔」': 'Possessed "Consumed by Obsession"',
	'冬紫罗兰': 'Winter violet',
	'冻符「完美冻结」': 'Freeze Sign "Perfect Freeze"',
	'凉凉的东西': 'Cold things',
	'分散很多个小的自己': 'Split into many small selves',
	'分解「剧毒中和」': 'Decomposition "Deadly Poison Neutralization"',
	'华符「芳华绚烂」': 'Splendor Sign "Brilliant Bloom"',
	'卖相不好的低贱品': 'Cheap stuff with bad appearance',
	'历史和文化相辅相成': 'History and culture complement each other',
	'反应会下降': 'Reactions will slow down',
	'口味重的东西': 'Strongly flavored food',
	'口授「黑心店家的黑心历史」': 'Oral Teaching "Dark History of Shady Shops"',
	'口碑最好的菜': 'The dish with the best reputation',
	'古老的东西': 'Ancient things',
	'可爱的玩偶': 'Cute dolls',
	'吃太饱不利于思考': 'Eating too much hinders thinking',
	'吃草帮助消化': 'Eating grass aids digestion',
	'吃遍各地美食': 'Taste cuisine from everywhere',
	'名神的后裔': 'Descendant of famous gods',
	'吾之时代': 'My era',
	'品相好看': 'Good appearance',
	'喜欢上和歌了': 'I\'ve come to like waka',
	'四天王奥义「三步必杀」': 'Four Heavenly Kings Secret "Three-Step Kill"',
	'因果「推理与判断之眼」': 'Cause & Effect "Eye of Reasoning and Judgment"',
	'国符「秘笈头槌」': 'Nation Sign "Secret Headbutt"',
	'圣童女「太阳神的贡品」': 'Holy Maiden "Offering to the Sun God"',
	'地底海底相通': 'The underground connects to the ocean floor',
	'地藏「业火救济」': 'Jizo "Hellfire Salvation"',
	'复仇之火永扑不尽': 'The fire of revenge never dies',
	'外国风味': 'Foreign flavors',
	'夜符「红雾异变再临」': 'Night Sign "Scarlet Mist Incident Redux"',
	'大口吃肉': 'Eat meat in big bites',
	'大和风情': 'Yamato-style charm',
	'天上剑「天人之五衰」': 'Heavenly Sword "Five Signs of a Dying Celestial"',
	'天罚「天雷暴击」': 'Divine Punishment "Thunder Critical Strike"',
	'太熟吃不惯': 'Too well-cooked, not used to it',
	'头脑发昏': 'Feeling dizzy',
	'奇迹「白昼新星」': 'Miracle "Daytime Supernova"',
	'好热': 'So hot',
	'好看的食物': 'Good-looking food',
	'宝槌「通货膨胀危机」': 'Treasure Mallet "Inflation Crisis"',
	'宵夜的份量': 'Late-night snack portion',
	'小槌「你给我变大吧!」': 'Mallet "Grow Bigger Already!"',
	'就用肚子来装': 'Just fill the stomach',
	'带着魔法的女仆长': 'Head maid with magic',
	'开心「东方红绿蓝」': 'Happy "Eastern Red Green Blue"',
	'异国风味': 'Exotic flavors',
	'律符「颠倒错乱」': 'Law Sign "Inverted Confusion"',
	'微微沾点酒精': 'Just a touch of alcohol',
	'恨符「丑时参拜」': 'Grudge Sign "Ushi no Toki Mairi"',
	'恶作剧「Combo消失术」': 'Prank "Combo Vanishing Trick"',
	'恶心「东方红红蓝」': 'Nausea "Eastern Red Red Blue"',
	'想起「不高兴的事情」': 'Recall "Unpleasant Memories"',
	'想起「那年的素兔的恐怖」': 'Recall "The Terror of the Plain Rabbit That Year"',
	'想起「高兴的事情」': 'Recall "Happy Memories"',
	'我不缺钱': 'I\'m not short on money',
	'我爱吃的糕点': 'Pastries I love',
	'我的家乡': 'My hometown',
	'我的食量': 'My appetite',
	'手机': 'Phone',
	'打包一份回去': 'Pack one to go',
	'把肉串起来': 'Skewer the meat',
	'拍个不停': 'Can\'t stop taking photos',
	'拷问「頞部陀」': 'Interrogation "Arbuda"',
	'拿手好菜': 'Signature dish',
	'指头缝都塞不满': 'Can\'t even fill the gaps between fingers',
	'撰书「这也全部是妖精干的吗」': 'Chronicle "Was This All the Fairies\' Doing Too?"',
	'文化的差异': 'Cultural differences',
	'文明的尺度': 'The measure of civilization',
	'料理里的故事': 'Stories in the cuisine',
	'方圆「山海千重」': 'Bounds "A Thousand Layers of Mountains and Seas"',
	'方符「奇门遁甲」': 'Square Sign "Qimen Dunjia"',
	'旅行的乐趣': 'The joy of travel',
	'无法抵达的地方': 'Unreachable places',
	'无限的胃袋': 'Infinite stomach',
	'旧时光景': 'Scenes of old times',
	'晚上不宜太饱': 'Shouldn\'t eat too much at night',
	'晦朔「天地未形」': 'New Moon "Before Heaven and Earth Took Form"',
	'暖暖身子': 'Warm up the body',
	'暗符「境界线」': 'Dark Sign "Boundary Line"',
	'最上乘的调味品': 'The finest seasoning',
	'最上品的菜': 'Top-quality dish',
	'最原始的味道': 'The most primal flavor',
	'最烈的酒': 'The strongest liquor',
	'最珍贵的料理': 'The most precious cuisine',
	'月之民不食糟糠': 'Lunarians don\'t eat chaff',
	'月之都如果有山': 'If the Lunar Capital had mountains',
	'月兔也是仙子': 'Moon rabbits are also celestials',
	'月符「月光射线」': 'Moon Sign "Moonlight Ray"',
	'有趣的东西': 'Interesting things',
	'有酒无菜': 'Drinks without dishes',
	'本州风格': 'Honshu style',
	'梦符「二重结界」': 'Dream Sign "Duplex Barrier"',
	'梦符「时空一粟」': 'Dream Sign "A Grain in Spacetime"',
	'森林里疯长的': 'Wildly growing in the forest',
	'森林里的果子': 'Fruits of the forest',
	'欺符「超限效应」': 'Deception Sign "Threshold Effect"',
	'毒最基础的味道': 'The most basic taste of poison',
	'比火焰炽热': 'Hotter than flames',
	'比雾之湖大一点': 'A little bigger than the Misty Lake',
	'毕竟是猫舌头': 'After all, I have a cat tongue',
	'水符「山洪暴发」': 'Water Sign "Flash Flood"',
	'永远猜不到我想要的是什么': 'You\'ll never guess what I want',
	'没有做熟的食物': 'Uncooked food',
	'没有味道': 'No flavor',
	'没那么刺激': 'Not so stimulating',
	'河童「延展手臂」': 'Kappa "Extending Arms"',
	'河童的口味': 'Kappa\'s taste',
	'油炸食品': 'Fried food',
	'流传至今的过去': 'The past that lives on',
	'流星「超级英仙座」': 'Meteor "Super Perseus"',
	'浓烈的酒': 'Strong alcohol',
	'清风': 'Fresh breeze',
	'清风流过的感觉': 'The feeling of a fresh breeze',
	'溺符「深海漩涡」': 'Drowning Sign "Deep Sea Vortex"',
	'滋滋冒气': 'Sizzling with steam',
	'满嘴荤腥': 'Mouth full of meat',
	'激活身体和思维': 'Activate body and mind',
	'火焰的燃烧': 'The burning of flames',
	'火辣辣的感觉': 'A fiery sensation',
	'灯符「荧光现象」': 'Lamp Sign "Fluorescent Phenomenon"',
	'独特的惊喜': 'A unique surprise',
	'狱光「扩散地狱火」': 'Prison Light "Spreading Hellfire"',
	'狱界剑「二百由旬之一闪」': 'Purgatory Sword "A Flash of 200 Yojana"',
	'狼魂「野性觉醒」': 'Wolf Soul "Wild Awakening"',
	'猫符「猫醉步」': 'Cat Sign "Cat\'s Drunken Walk"',
	'现今的饮料': 'Modern drinks',
	'生机「四十叶草般的幸运」': 'Vitality "Forty-Leaf Clover Luck"',
	'生肉总比熟肉好吃': 'Raw meat always tastes better than cooked',
	'真是累人': 'Truly tiring',
	'知识的奇妙冒险「文化之风」': 'Bizarre Adventure of Knowledge "Cultural Winds"',
	'祖国的味道': 'Taste of the homeland',
	'神宝「蓬莱的玉枝 梦色之乡」': 'Sacred Treasure "Hourai Jeweled Branch -Town of Dreams-"',
	'神德「五谷丰穰米之浴」': 'Divine Virtue "Bountiful Harvest Rice Bath"',
	'神诏「众神谕使」': 'Divine Decree "Messenger of the Gods"',
	'竹林里的麻雀': 'Sparrow in the bamboo grove',
	'粮食酿造的米酒': 'Rice wine brewed from grain',
	'红符「红色不夜城」': 'Scarlet Sign "Red City That Never Sleeps"',
	'绅士风度': 'Gentlemanly demeanor',
	'细索「犍陀多绳索」': 'Fine Thread "Kandata\'s Rope"',
	'缩短他乡与故乡的距离': 'Shorten the distance between foreign land and home',
	'肚子总是空空': 'Stomach is always empty',
	'腐肉': 'Rotten meat',
	'自古逢秋悲寂寥': 'Since ancient times, autumn brings sorrow',
	'荤腥的东西': 'Meaty and fishy stuff',
	'蓝色满天星': 'Blue baby\'s breath',
	'藤原「灭罪寺院伤」': 'Fujiwara "Sin-Atoning Temple Wounds"',
	'蜘蛛的口味': 'Spider\'s taste',
	'蠢符「夜虫龙卷」': 'Foolish Sign "Night Bug Tornado"',
	'血液沸腾起来': 'Blood boils up',
	'血淋淋的食物': 'Bloody food',
	'被雷劈过一样': 'Like being struck by lightning',
	'要吃冰的': 'Want something icy',
	'让人吓一跳': 'Something that startles you',
	'讲究这么多': 'So particular about things',
	'诫罚「诸神圣裁」': 'Admonition "Divine Judgment of the Gods"',
	'贵的买不起': 'Too expensive to afford',
	'跟别人分享': 'Share with others',
	'踹不动树': 'Can\'t kick down a tree',
	'过去吃过的': 'Things I\'ve eaten before',
	'追求奇妙的体验': 'Seeking a wondrous experience',
	'适合发博客': 'Perfect for blogging',
	'逆弓「天壤梦弓的诏敕」': 'Reverse Bow "Decree of the Dream Bow of Heaven and Earth"',
	'逆转「颠倒世界」': 'Reversal "Inverted World"',
	'邪术「天下无墙」': 'Black Magic "A World Without Walls"',
	'配得上我的称号': 'Worthy of my title',
	'酒吞奥义「鬼进酒」': 'Shuten Secret "Spirits for the Oni"',
	'金水符「水银之毒」': 'Metal-Water Sign "Mercury Poison"',
	'铃兰「凋零花园」': 'Lily of the Valley "Withering Garden"',
	'锻炼不宜吃太多': 'Shouldn\'t eat too much while training',
	'陈腐的东西不能入口': 'Stale things are inedible',
	'陈酿': 'Aged wine',
	'降温工作': 'Cooling off',
	'雨符「雨夜怪谈」': 'Rain Sign "Rainy Night Ghost Story"',
	'雷影「电光石火」': 'Thunder Shadow "Lightning Flash"',
	'颠覆强者': 'Overthrow the strong',
	'食之品相': 'Appearance of food',
	'食物的保质期': 'Shelf life of food',
	'食物的相逢': 'Meeting of foods',
	'饱餐一顿': 'A full meal',
	'饿狼「暴食的月下舞踏」': 'Hungry Wolf "Gluttonous Dance Under the Moon"',
	'馊掉的东西': 'Spoiled food',
	'魔符「即席菩提」': 'Magic Sign "Impromptu Bodhi"',
	'魔符「拿来吧你」': 'Magic Sign "Gimme That"',
	'魔符「狡猾的献祭」': 'Magic Sign "Cunning Sacrifice"',
};

// Read the current file
const filePath = 'app/data/i18n/en.ts';
const content = readFileSync(filePath, 'utf8');

let updated = content;
let count = 0;

for (const [key, value] of Object.entries(enTranslations)) {
	const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	const pattern = new RegExp(`'${escaped}':\\s*'',`);
	if (pattern.test(updated)) {
		const safeValue = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
		updated = updated.replace(pattern, `'${key}': '${safeValue}',`);
		count++;
	} else {
		console.log(`Key not found or already filled: ${key}`);
	}
}

writeFileSync(filePath, updated, 'utf8');
console.log(`\nUpdated ${count} translations in ${filePath}`);
