import fs from 'fs';

// English translations for description keys batch 5 (keys 800-999)
const translations: Record<string, string> = {
  '差不多也该出去走走了。': 'It\'s about time to go out for a walk.',
  '差不多也该考虑考虑以后了。': 'It\'s about time to start thinking about the future.',
  '差不多该觉察到心中的压力了吧。': 'It\'s about time to notice the pressure in your heart.',
  '差点就在众目睽睽下吃霸王餐了！': 'I almost dined and dashed in front of everyone!',
  '己所不欲，勿施于人。': 'Do not do unto others what you would not have done unto yourself.',
  '已臻化境的料理台！': 'A perfected cooking station!',
  '已臻化境的油锅！': 'A perfected fryer!',
  '已臻化境的烧烤架！': 'A perfected grill!',
  '已臻化境的煮锅！': 'A perfected boiling pot!',
  '已臻化境的蒸锅！': 'A perfected steamer!',
  '帕秋莉·诺蕾姬送的舒服又保暖的家居服，穿上就不想脱下来了。': 'Cozy and warm loungewear gifted by Patchouli Knowledge — once you put it on, you never want to take it off.',
  '帕秋莉…她不会突然从哪冒出来吧。': 'Patchouli... she won\'t suddenly pop out from somewhere, will she?',
  '带有"猎奇"标签的食物制作速度提高30%，且额外提供30%续单率，持续30秒。': 'Food with the "Exotic" tag has 30% faster production speed and provides an extra 30% reorder rate. Lasts 30 seconds.',
  '常见的家常菜。以猪肉为主要材料，裹以面粉一炸，邻居家的孩子都馋哭了。': 'A common home-cooked dish. Pork as the main ingredient, coated in flour and fried — the neighbor\'s kids are drooling with envy.',
  '常见的家常菜。传说中是稻荷神的狐狸使者最喜欢的食物。': 'A common home-cooked dish. Said to be the favorite food of Inari\'s fox messengers.',
  '常见的家常菜。看上去颗颗饭粒饱满，淋上的香酱和牛肉的口感融为一体，令人胃口倍增。': 'A common home-cooked dish. Each grain of rice looks plump, with the savory sauce and beef blending perfectly — a real appetite booster.',
  '常见的家常菜。看上去颗颗饭粒饱满，淋上的香酱和猪肉的口感融为一体，令人胃口倍增。': 'A common home-cooked dish. Each grain of rice looks plump, with the savory sauce and pork blending perfectly — a real appetite booster.',
  '常见的家常菜，但也讲究烧制的火候，才能将豆腐的鲜嫩口感得到最大展现。': 'A common home-cooked dish, but precise heat control is needed to bring out the best tenderness of the tofu.',
  '常见的平价饭团。内馅儿加入了鳟鱼和洋葱，融合了海鲜的细腻口感和洋葱的炽热，无论是营养还是口感都属上佳。': 'A common affordable rice ball. The filling of trout and onion combines the delicate texture of seafood with the fiery kick of onion — excellent in both nutrition and taste.',
  '常见的平价饭团。在饭团中放入烤制后的猪肉，为其增加了一份香浓的嚼劲。': 'A common affordable rice ball. Grilled pork is placed inside, adding a rich, chewy flavor.',
  '帽子帽子扔锅里！': 'Hats, hats, throw them in the pot!',
  '帽子着火了！': 'The hat\'s on fire!',
  '干了一天活过来喝一杯！': 'Worked all day — came here for a drink!',
  '干嘛要把人赶走啊…': 'Why kick people out...',
  '平安时代的强盗都没有你猖獗！': 'Even Heian-era bandits weren\'t as outrageous as you!',
  '平淡无奇的锅碗瓢盆里，盛满了人类的一生。': 'In ordinary pots and pans lies a lifetime of humanity.',
  '并不是真正的桃子，似乎是比那名居天子亲手做的。虽然不能吃，但据说能带来好运。': 'Not a real peach — apparently handmade by Hinanawi Tenshi. Though inedible, it\'s said to bring good luck.',
  '幸好有带一些钱…不过大家要省着点花呀。': 'Glad I brought some money... but everyone needs to spend wisely.',
  '幻想乡流行起来的远程通话装置。': 'A remote communication device that became popular in Gensokyo.',
  '幻想乡的消费水平比外面世界还高啊…': 'The cost of living in Gensokyo is even higher than the outside world...',
  '幻想乡的雨PH值为6哦，就是几乎不含酸性的意思。': 'Rain in Gensokyo has a pH of 6 — meaning it\'s almost non-acidic.',
  '幻想乡随处可见的探宝者。要是能和它们打好关系，以后就不用担心丢东西了。不过委托它们寻找食物的话，可能会在拿回来之前就被它们啃光。': 'Treasure hunters found everywhere in Gensokyo. Get on their good side and you\'ll never worry about losing things. But if you ask them to find food, they might eat it all before bringing it back.',
  '幽幽子释放1/3/5/8（随使用次数提升）只蝴蝶飞向保温箱，每只蝴蝶吞噬保温箱中存储的一个料理，转化为等同于四倍料理价格的金钱（享受小费倍率加成）。': 'Yuyuko releases 1/3/5/8 butterflies (increasing with uses) that fly toward the warmer. Each butterfly consumes one stored dish, converting it into money worth four times the dish\'s price (affected by tip multiplier).',
  '店主！为什么没有烧鸟啊！啊…别这么看着我啊。': 'Owner! Why is there no yakitori?! Ah... don\'t look at me like that.',
  '店内所有顾客每15秒会进行1-20円的打赏。': 'All customers in the shop tip 1-20 yen every 15 seconds.',
  '店内气氛掉落到冰点，顾客也会降低心情。': 'The shop atmosphere drops to freezing, and customers\' moods decrease.',
  '店里要是出现虫子的话，我可以帮你解决哦。': 'If bugs appear in the shop, I can take care of them for you.',
  '座敷童子其实并不是像地缚灵那样，只能呆在固定的场所里哦。': 'Zashiki-warashi aren\'t bound to one place like earthbound spirits, you know.',
  '开什么玩笑，把魔界所有人的零花钱加起来也吃不起这样一顿饭啊！': 'You\'re kidding — even combining everyone in Makai\'s pocket money couldn\'t pay for a meal like this!',
  '式神什么的果然还是想不明白…有着不为人知的过去，还和那个饕餮尤魔有联系？明明是性格天差地别的两个人。': 'I still can\'t figure out shikigami... She has an unknown past and is connected to that taotie Yuuma? Even though their personalities are completely opposite.',
  '弱小妖怪什么时候才可以不被欺压？！': 'When will weak youkai stop being bullied?!',
  '弱小的妖怪们，和我一起站起来吧！': 'Weak youkai, rise up with me!',
  '当你没有决定要成功时，你就已经决定要失败了。': 'When you haven\'t decided to succeed, you\'ve already decided to fail.',
  '当夜结算时收取翻倍佣金。': 'Collects double commission at the end of the night.',
  '当完成场上顾客的订单且至少获得普通评价后，在座位附近掉落一枚"蓬松松糖果"以供拾取，持续30秒。': 'After completing a seated customer\'s order with at least a Normal rating, drops a "Fluffy Candy" near the seat for pickup. Lasts 30 seconds.',
  '当心我把你烤了哦！': 'Watch out or I\'ll roast you!',
  '当晚营业结束后，再经过60秒，将会强制驱逐店铺内的顾客并关店。': 'After business hours end that evening, after 60 more seconds all customers in the shop will be forcibly evicted and the shop will close.',
  '形似甜甜圈而长了一对恶魔的角，说是甜品而其实完全就是芝士口味的汉堡包。不过由于中间有洞，吃的时候要尤其留意不要弄脏了衣服。': 'Shaped like a donut with a pair of devil horns — called a dessert but actually a cheese-flavored hamburger. Because of the hole in the middle, be careful not to stain your clothes while eating.',
  '常常在妖怪山上巡逻的白狼天狗，嗅觉、听觉非常灵敏，被称为山上的千里眼，能迅速发现入侵者。正因为有这样的守卫在，我们这种小妖怪平时根本不敢上山。': 'White wolf tengu who patrol Youkai Mountain regularly. With incredibly keen senses of smell and hearing, they\'re called the mountain\'s all-seeing eyes and can quickly spot intruders. With guards like these, small youkai like us normally don\'t dare go up the mountain.',
  '很久以前就离开了幻想乡、有着大姐头气魄的鬼，性格刚毅且干脆利落。如今在管理着旧地狱街道上的温泉。偶尔去泡一泡温泉吧！': 'An oni with a big-sister spirit who left Gensokyo long ago — tough, decisive, and no-nonsense. Now she manages the hot springs on Former Hell\'s streets. Go enjoy the hot springs sometime!',
  '很久以前，有一位僧侣被封印到了我所在的魔界。后来发生了什么？这是秘密。': 'Long ago, a monk was sealed in the Makai where I live. What happened after? That\'s a secret.',
  '很好吃哦！': 'Very delicious!',
  '很有粘性的米。制作出来的料理或绵软适口，或鲜嫩弹牙。': 'Very sticky rice. The dishes made from it are either soft and smooth, or fresh and chewy.',
  '很美味，看来你下了不少功夫。': 'Very delicious — looks like you put in a lot of effort.',
  '得更努力工作赚钱才行了…': 'I need to work harder to earn more money...',
  '得赶在被女仆长发现前回去。': 'I need to get back before the head maid notices.',
  '微苦的橙味为主，香气扑鼻，入口柔顺。最近非常流行。': 'Mainly a slightly bitter orange flavor — aromatic and smooth on the palate. Very popular recently.',
  '心情就像缓缓打开的花蕾一样呢。': 'My mood feels like a slowly blossoming flower bud.',
  '忙碌的一天终于结束了！': 'A busy day is finally over!',
  '怎么啦怎么啦？是没看到我吗？': 'What\'s wrong, what\'s wrong? Didn\'t you see me?',
  '怎么有人卖东西比我还离谱啊？！': 'How can someone sell things at even more outrageous prices than me?!',
  '怎么看都像是随手抓来的兔子，但因为是帝抓来的，竟然有着奇妙的幸运。': 'Looks like a randomly caught rabbit in every way, but because the Emperor caught it, it has mysterious good fortune.',
  '性格暴躁，总是摆出一副老油条的样子，其实也没啥本事吧。不过，它们似乎很擅长变幻，要警惕它们用叶子来付账！': 'Short-tempered, always acting like a seasoned pro, but probably doesn\'t have much actual ability. However, they seem skilled at shapeshifting — watch out for them paying with leaves!',
  '怪不得紫大人会把希望寄托在你身上。': 'No wonder Lady Yukari places her hopes in you.',
  '怪诞评审好酷——啊呀！那不就是我嘛！': 'The quirky judge is so cool — oh wait! That\'s me!',
  '总有一天我会把你收入麾下。': 'Someday I\'ll recruit you under my command.',
  '总觉得别人碗里的更香…': 'Somehow the food in others\' bowls looks better...',
  '总觉得河童们最近是不是兴奋得有些异常…': 'Somehow the kappa seem unusually excited lately...',
  '总觉得，满月时的记忆似乎不太完整…': 'Somehow, memories during the full moon seem incomplete...',
  '恋恋喜欢热闹啦！': 'Koishi loves lively places!',
  '惊——！好吃到吓人！': 'Wha—! Frighteningly delicious!',
  '想吃仙人的妖怪不少，给仙人做饭的还是第一次见呢。': 'Plenty of youkai want to eat hermits, but a youkai cooking FOR a hermit is a first.',
  '想用这个来收集信仰的话，还需要再精进一些吧。': 'If you want to use this to gather faith, you\'ll need to improve a bit more.',
  '想要获得情报就要深入群众。': 'To get information, you need to go among the people.',
  '感觉我好像长出了肌肉。': 'I feel like I\'ve grown muscles.',
  '感谢我没有报导这种漫天要价的行为吧！': 'Be grateful I didn\'t report these outrageous prices!',
  '慧音老师又留了好多作业…好在来之前就写完了。': 'Miss Keine assigned a lot of homework again... Good thing I finished before coming.',
  '慧音老师的课真的好——无——聊！如果是阿求姐姐来上的话大概会不一样吧？': 'Miss Keine\'s class is SO BORING! It would probably be different if Sister Akyuu taught it, right?',
  '成美给的礼物，可以放置在家附近。': 'A gift from Narumi — can be placed near the house.',
  '我一定会把你写到《幻想乡缘起》里！': 'I will definitely write you into the Gensokyo Chronicle!',
  '我一定要在博客上推荐这道料理！': 'I have to recommend this dish on my blog!',
  '我一定要把你从船上扔下去！': 'I will definitely throw you off the ship!',
  '我一开始就没有对你抱有任何期待。': 'I never had any expectations of you from the start.',
  '我不会把你的店吃垮的啦。': 'I won\'t eat your shop out of business.',
  '我不可能放任你在月都胡来！': 'I can\'t let you run wild in the Lunar Capital!',
  '我不是为了这种东西跑到地上来的——！': 'I didn\'t come all the way to the surface for this—!',
  '我不是家里蹲，只是永琳每次都要嘱咐半天所以我才懒得出门。': 'I\'m not a shut-in — it\'s just that Eirin always lectures me so long before leaving that I can\'t be bothered to go out.',
  '我不是已经把桃子留下了吗？': 'Didn\'t I already leave the peach behind?',
  '我不是想打击你，但是味道确实不太好…': 'I don\'t mean to discourage you, but the taste really isn\'t great...',
  '我不是挑食，只是正好不爱吃那些口味。': 'I\'m not picky — I just happen to dislike those flavors.',
  '我不是来化缘的，我带了钱！': 'I\'m not here to beg for alms — I brought money!',
  '我不是那种会动粗的人，所以才能好好地活这么长时间。': 'I\'m not the violent type — that\'s why I\'ve lived this long.',
  '我不能允许幻想乡存在这种漫天要价的行为！': 'I cannot allow such outrageous pricing in Gensokyo!',
  '我也不是什么挑食的人。': 'I\'m not picky either.',
  '我也很羡慕今朝有酒今朝醉的生活啊…': 'I also envy the lifestyle of living in the moment...',
  '我也想变得像山女小姐一样受欢迎啊。': 'I wish I could be as popular as Miss Yamame.',
  '我享受到的服务已经超过了交易本身，必须要给予答谢！': 'The service I\'ve received exceeds the transaction itself — I must show my gratitude!',
  '我什么时候也能有自己的仙界呢？': 'When will I have my own hermit realm?',
  '我们的王总是温柔而睿智。': 'Our king is always gentle and wise.',
  '我们的画风跟其他人真的不一样啊…': 'Our style really is different from everyone else\'s...',
  '我们的老大住在一个到处都埋着宝藏的神秘之地。': 'Our boss lives in a mysterious place where treasure is buried everywhere.',
  '我们虽然长得丑了那么一点点，但干活可是很麻利的。': 'We may be a tiny bit ugly, but we\'re very efficient workers.',
  '我们认为是宝藏的东西，人类总不这样认为。': 'What we consider treasure, humans never seem to agree.',
  '我们跑腿的只能在山上做些低端基本的工作。': 'We errand-runners can only do basic, low-level work on the mountain.',
  '我们这种底层天狗就连吃饭也要被瞧不起吗？': 'Do even low-ranking tengu like us get looked down upon just for eating?',
  '我作为邻居来捧场了哦老板娘！': 'I\'m here as your neighbor to show support, boss lady!',
  '我修行的可是优雅的冰系魔法哦？比火系魔法要强很多呢。': 'I practice elegant ice magic, you know? It\'s much stronger than fire magic.',
  '我倒要看看现在的年轻人的居酒屋搞得怎么样。': 'Let me see how the youngsters\' izakaya is doing nowadays.',
  '我像是身上有很重铜臭味的人吗？': 'Do I look like someone who reeks of money?',
  '我其实是个妖精美食家哦。': 'I\'m actually a fairy gourmet, you know.',
  '我去借点钱再来吃！': 'Let me borrow some money and come back to eat!',
  '我又来了！吓~一跳了吗？': 'I\'m back! Did I scare you~?',
  '我只是装得阴沉的样子啦。': 'I\'m just pretending to be gloomy.',
  '我可以理解为这是你下的战书吗？': 'Can I take this as your declaration of war?',
  '我可是丰收之神！你不能这样对我！': 'I\'m a goddess of harvest! You can\'t treat me like this!',
  '我可是圣诞节最受欢迎的礼物之一哦。': 'I\'m one of the most popular Christmas gifts, you know.',
  '我可没有偷懒哦——虽然确实是偷偷溜出来的。': 'I wasn\'t slacking off — though I did sneak out.',
  '我可没有点这些菜！你自己上的菜自己买单吧。': 'I didn\'t order these dishes! You served them yourself, so you pay for them.',
  '我可爱的橙，现在看见尸体就兴高采烈的…': 'My adorable Chen now gets excited at the sight of corpses...',
  '我可爱的部下们受你关照了哟。': 'I see you\'ve been looking after my cute subordinates.',
  '我和苏格拉底都很满意哦！': 'Both Socrates and I are very satisfied!',
  '我和铃铃一致好评！': 'Rin-Rin and I both give rave reviews!',
  '我和铃铃好不容易攒下来的钱快见底了…': 'The money Rin-Rin and I saved up is almost gone...',
  '我女儿让我去香霖堂买什么…手鸡？现在的小孩子啊。': 'My daughter told me to buy something at Kourindou... a hand chicken? Kids these days.',
  '我好恨呐。': 'I\'m so resentful.',
  '我对无聊的战斗不感兴趣。': 'I have no interest in boring battles.',
  '我对梦里的味道念念不忘，所以就来了。': 'I couldn\'t stop thinking about the taste I had in my dream, so I came.',
  '我就只带了这么多，爱要不要吧。': 'This is all I brought — take it or leave it.',
  '我就只有这么多钱了…': 'This is all the money I have...',
  '我就是为了感受一下热闹才来的。': 'I came just to enjoy the lively atmosphere.',
  '我就随便带了点钱，你都拿去好了。': 'I just casually brought some money — take it all.',
  '我已经离开太久了，如今的幻想乡变了太多，我需要好好适应。': 'I\'ve been away for too long — Gensokyo has changed so much. I need to readjust.',
  '我应该也可以做到这种程度吧？': 'I should be able to do this much too, right?',
  '我很清楚成本是多少。': 'I know exactly how much the cost is.',
  '我才不是嘴馋，我只是来监督你的。': 'I\'m not here because I\'m greedy — I\'m just here to supervise you.',
  '我是我，四个我加在一起也是我！': 'I am me, and four of me put together is still me!',
  '我是谁？？？我在哪？？？我为什么会在这里？？？': 'Who am I??? Where am I??? Why am I here???',
  '我最喜欢在花田玩捉迷藏游戏了。': 'I love playing hide and seek in flower fields!',
  '我期待的幻想乡并非这种模样。': 'The Gensokyo I expected doesn\'t look like this.',
  '我本来也没打算吃。': 'I wasn\'t planning on eating anyway.',
  '我残暴？呵呵，皆是那些幽灵罪有应得。': 'I\'m brutal? Heh, those ghosts all got what they deserved.',
  '我没什么耐心，一会儿上菜可别让我等太久啊！': 'I\'m not very patient — don\'t make me wait too long for the food!',
  '我没有留下一记魔炮你就该感恩戴德了。': 'You should be grateful I didn\'t blast you with a Master Spark.',
  '我没有钱哦！吓到了吧——？！': 'I have no money! Scared you—?!',
  '我的书并没有乱放，所有的书都在它们自己想呆的位置上。': 'My books aren\'t placed randomly — every book is where it wants to be.',
  '我的佣人没有随行，身上带的钱不够，请见谅…': 'My servant didn\'t come along and I didn\'t bring enough money, please forgive me...',
  '我的工资只剩这么多了…': 'This is all that\'s left of my salary...',
  '我的金币不断地被抢走，这样的日子还能过下去吗！': 'My gold coins keep getting stolen — can I even go on living like this?!',
  '我的钱变成秋天的落叶了…': 'My money turned into autumn leaves...',
  '我的钱可不是树上掉下的落叶！': 'My money doesn\'t grow on trees!',
  '我的钱和我的怨恨都消散得差不多了。': 'Both my money and my resentment have mostly faded away.',
  '我的魔界支付说它要炸了…': 'My Makai Pay says it\'s about to explode...',
  '我的麟是麒麟的麟哦！很厉害吧。': 'The "Rin" in my name is the "Rin" from Kirin, you know! Pretty amazing, right?',
  '我能品尝出料理里的善意哦！': 'I can taste the kindness in the food!',
  '我能来的次数不多，所以我很珍惜这样的机会。': 'I can\'t come often, so I treasure opportunities like this.',
  '我能理解这种被嫌弃的感觉。': 'I understand the feeling of being disliked.',
  '我要把这个黑店钉在树上！': 'I\'ll nail this scam shop to a tree!',
  '我要让守矢之名响彻幻想乡！': 'I\'ll make the name of Moriya echo throughout Gensokyo!',
  '我要让这双驱赶我的手烂掉！': 'I\'ll make the hands that shooed me away rot!',
  '我要颠倒正是这种将糟糠奉为美食的世界！': 'I want to overturn this world that treats slop as delicacies!',
  '我觉得你应该能做得更好。': 'I think you should be able to do better.',
  '我过得向来清贫，就只有这么多钱了…': 'I\'ve always lived frugally — this is all the money I have...',
  '我还不习惯自己带钱出门…': 'I\'m still not used to bringing money out on my own...',
  '我还不太习惯地上的消费水平…': 'I\'m still not used to the spending levels on the surface...',
  '我还以为你会和别的妖怪不一样…': 'I thought you\'d be different from other youkai...',
  '我这把年纪了，实在是没法住在魔法森林附近…太潮湿了，关节成天疼。': 'At my age, I really can\'t live near the Forest of Magic... it\'s too humid, my joints ache all day.',
  '我远道而来就为了个这？': 'I came all this way for THIS?',
  '我连自己出来吃点儿东西都不行吗？': 'Can\'t I even come out to eat something on my own?',
  '我都想破格把你掳到八寒地狱来做饭呢！': 'I want to break the rules and kidnap you to cook in the Eight Cold Hells!',
  '我闻到烧烤和好酒的味道了！': 'I smell grilled food and fine drinks!',
  '所有人看起来都这么幸福，我好嫉妒啊…': 'Everyone looks so happy — I\'m so jealous...',
  '所有厨具的料理速度加快50%，持续20秒。': 'All cookware\'s cooking speed increases by 50% for 20 seconds.',
};

// Apply translations
let content = fs.readFileSync('app/data/i18n/en.ts', 'utf8');
let count = 0;
for (const [key, value] of Object.entries(translations)) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`('${escaped}':\\s*)'',`, 'g');
  const newContent = content.replace(regex, `$1'${value.replace(/'/g, "\\'")}',`);
  if (newContent !== content) {
    count++;
    content = newContent;
  }
}
fs.writeFileSync('app/data/i18n/en.ts', content);
console.log(`Updated ${count} translations in app/data/i18n/en.ts`);
console.log(`Expected: ${Object.keys(translations).length}`);
