import fs from 'fs';

// English translations for description keys batch 3 (keys 401-600)
const translations: Record<string, string> = {
  '发动一次保护结界，可以完全防御下一位稀有顾客的惩罚符卡。': 'Activates a protective barrier that can completely defend against the next rare customer\'s penalty spell card.',
  '取悦自己才是最重要的。': 'Pleasing yourself is what matters most.',
  '受到\u201C恶灵缠怨\u201D：无法获得夜雀之歌类Buff，且无法触发特殊厨具效果，持续30秒。': 'Inflicted with "Evil Spirit\'s Grudge": cannot gain Night Sparrow Song buffs and cannot trigger special cookware effects for 30 seconds.',
  '受邪仙操纵的僵尸。虽然是尸体但是不会腐烂，拥有比生前更强劲的力量。脑子不太好使，想与之沟通也很困难，但胜在不挑食。据说人类要是被咬到会暂时变成它们的同类，感觉还挺有趣的。就像\u201C僵尸体验卡\u201D？': 'A zombie controlled by a wicked hermit. Though a corpse, it doesn\'t decay and has more power than in life. Not great in the brain department and difficult to communicate with, but at least it\'s not a picky eater. They say humans who get bitten temporarily turn into one of them — sounds kind of fun. Like a "zombie experience pass"?',
  '口味偏甜、营养丰富的银耳莲子粥。滋润而不腻滞，还具有养心安神的功效。': 'Sweet and nutritious snow fungus and lotus seed congee. Moisturizing without being greasy, it also calms the heart and soothes the mind.',
  '口腹之欲都要被勾起来了！': 'My appetite is about to be fully aroused!',
  '古代人的亡灵。过去似乎怀有很深的怨恨，所以性质上是妖怪们最害怕的怨灵。有点儿不太敢接触她呢…': 'The ghost of an ancient person. She seemed to harbor deep resentment in the past, making her the type of vengeful spirit that youkai fear the most. I\'m a bit afraid to approach her...',
  '古老的真相不明的妖怪——鵺。长得和传说完全不一样真可惜…虽然也是命莲寺的弟子，但总是见到她独自在寺院附近无所事事地游荡，似乎不太合群的样子。': 'An ancient youkai of unknown identity — the Nue. What a shame she looks nothing like the legends... Though she\'s also a disciple of Myouren Temple, she\'s always seen wandering aimlessly near the temple alone, seemingly not fitting in.',
  '只是坐下来就已经觉得胃里暖暖的。': 'Just sitting down already makes my stomach feel warm.',
  '只有嗅觉敏锐的商人，才能将商业情报作用发挥到极致。': 'Only a merchant with a keen nose can maximize the use of business intelligence.',
  '只有抵住最黑的暗，才能收获最光的亮。': 'Only by enduring the deepest darkness can you harvest the brightest light.',
  '只有这样的美味才能够配得上吸血鬼的尊贵身份！': 'Only such delicacies are worthy of a vampire\'s noble status!',
  '只有这种程度吗？': 'Is this the extent of it?',
  '只有这种舌尖上的享受，才配得上我无限的胃袋！': 'Only this level of gustatory pleasure is worthy of my infinite stomach!',
  '只比庸俗之人的作品好一点。': 'Only slightly better than the work of a vulgar person.',
  '只能使用一个托盘进行服务，被禁用托盘内的还未拿走的物品会被焚毁，持续30秒。': 'Can only use one tray for serving. Items not yet taken from disabled trays will be destroyed. Lasts 30 seconds.',
  '只能算是无功无过吧。': 'I\'d say it\'s just mediocre — no merits, no faults.',
  '只要填饱肚子就不会感到空虚啦！': 'As long as your stomach is full, you won\'t feel empty!',
  '只要好好去完成客人的要求，就不会被特地刁难。': 'As long as you fulfill the customer\'s requests properly, they won\'t give you a hard time.',
  '只要聚在一起就会有说不完的话，基本说的都是些生活琐事，或者互相奉承衣服首饰什么的。偶尔还能听到关于料理的技巧，这点倒是挺好的。': 'Whenever they get together there\'s always endless chatter — mostly daily trivia or complimenting each other\'s clothes and jewelry. Occasionally I can pick up cooking tips, which is actually quite nice.',
  '只要见过她照顾花儿的样子，那些有关她的谣言就会不攻自破。但我还是不明白，她有那么强大的妖力，为什么会容忍谣言满天飞，为什么要默默地承受那些恶意中伤呢？': 'Anyone who\'s seen her tending to flowers would know those rumors about her are groundless. But I still don\'t understand — with her immense youkai power, why does she tolerate the rumors flying around? Why does she silently endure all that malicious slander?',
  '只要遇到需要帮助的人，爱莲小姐就会尽十二分努力去帮助，是个非常友好的魔法使！爱莲小姐对工作也一直保持着相当的热忱，每次和她对话感觉自己也变得活力满满了。': 'Whenever she meets someone who needs help, Miss Ellen gives 120% effort — she\'s a very friendly magician! Miss Ellen also maintains great enthusiasm for work. Every time I talk to her, I feel energized too.',
  '召唤若干狸猫，变化成就座顾客的样子（不包括揣藏本人），并重新加入到排队队列中。狸猫变化的顾客，喜好和预算与变化对象无异，但所有狸猫变化成的稀有顾客整晚只能释放一次变化对象的符卡。': 'Summons several tanuki who disguise themselves as seated customers (excluding the shapeshifter herself) and rejoin the queue. Tanuki-disguised customers have the same preferences and budget as their targets, but all tanuki-disguised rare customers can only use the target\'s spell card once per evening.',
  '召开一场盛大的篝火盛宴，场上每只存在的兔子生成一个随机食材或一瓶随机酒水，接下来30秒内出现新的兔子时会同样生成食材或酒水。生成食材的概率为80%，生成酒水的概率为20%。': 'Hosts a grand bonfire feast. Each rabbit on the field generates a random ingredient or drink. New rabbits appearing within the next 30 seconds also generate ingredients or drinks. 80% chance for ingredients, 20% for drinks.',
  '可以以秒为单位，编辑夜晚顾客前来的次序和时间点。': 'Allows editing the order and timing of nightly customer arrivals down to the second.',
  '可以免疫【苏我屠自古】惩罚符卡的击晕效果。': 'Can immunize against the stun effect of Soga no Tojiko\'s penalty spell card.',
  '可以啊！居然做得这么好！': 'Not bad! I can\'t believe it\'s this good!',
  '可以抵挡一次中断Combo的失误。': 'Can block one combo-breaking mistake.',
  '可以看到每个顾客的预算额度。': 'Allows seeing each customer\'s budget.',
  '可以进行精细高级操作的钓鱼竿，除了能够钓鱼，还能够寻找到宝箱！非常神奇！': 'A fishing rod capable of fine, advanced operations. Besides fishing, it can even find treasure chests! Truly amazing!',
  '可可树的果实。据说在不同地区有不同的风味，有的会带点儿果香，有的带有烟熏的风味。可以磨成粉食用，是制作巧克力的基本原料。': 'Cocoa tree fruit. Said to have different flavors depending on the region — some with fruity notes, others with a smoky flavor. Can be ground into powder, and is the basic ingredient for making chocolate.',
  '可恶！你要是将来落在我手上…': 'Curse you! If you ever fall into my hands...',
  '可恶，不能输在气势上，一定要装作常来的样子。': 'Damn, I can\'t lose in presence — I have to act like I come here all the time.',
  '可恶，今天又输给灵梦那个家伙了呀！': 'Curse it, I lost to that Reimu again today!',
  '可恶，我没退治你，你居然敢赶我走？！': 'How dare you! I haven\'t even exterminated you, and you dare kick me out?!',
  '叶子变的钱非常便利哦。': 'Money made from leaves is very convenient.',
  '叶子老朽倒是有很多，钱就只有这些了。': 'I have plenty of leaves, but this is all the money I\'ve got.',
  '吃不下的食物可以打包吗？我想带给我家猫咪吃。': 'Can I take the leftovers to go? I want to bring them to my cats.',
  '吃到一半莫名其妙就被赶走了…料理再好吃以后也不来了，哼！': 'Got thrown out halfway through for no reason... No matter how good the food is, I\'m never coming back — hmph!',
  '吃喜欢的东西，过可爱的人生。': 'Eat what you love, live a lovely life.',
  '吃夜宵是不是有点不够矜持啊？': 'Isn\'t eating late-night snacks a bit unladylike?',
  '吃完再回去做帽子吧！': 'Let\'s eat first and then go back to making hats!',
  '吃完后再做做运动吧。': 'Let\'s exercise a bit after eating.',
  '吃掉这个小麻雀的话，我是不是也能做出这么美味的食物。': 'If I eat this little sparrow, could I make food this delicious too?',
  '吃掉黑暗物质。每吃一份，全速度增加20%，直到200%。': 'Eats Dark Matter. Each portion increases all speeds by 20%, up to 200%.',
  '吃货最高境界就是眼见为食。': 'The highest realm of a foodie is eating with your eyes.',
  '吃食只是为了支撑自己不会倒下。': 'Eating is just to keep myself from collapsing.',
  '吃饭就是图个气氛，气氛不到位食物也会变难吃。': 'Eating is all about the atmosphere — bad atmosphere makes even good food taste bad.',
  '吃饭的时候说话会咬到舌头。': 'Talking while eating will make you bite your tongue.',
  '吃饱了才好恶作剧。': 'Only when full can you pull pranks properly.',
  '吃饱了才有力气去守护。': 'Only when full do you have the strength to protect.',
  '吃饱了还得载那个家伙去魔界…': 'Even after eating, I still have to carry that person to Makai...',
  '吃饱啦。': 'I\'m full.',
  '同情心什么的根本就不需要。': 'Sympathy and such are not needed at all.',
  '后厨的火力够吗？需要吾帮忙添一把火吗？': 'Is the kitchen firepower enough? Need me to add some fire?',
  '后户之国的童子？绿发的电波少女？怎么可能是我嘛，我可是魔界的魔法使舞哦。': 'A child from the Land of the Back Door? A green-haired eccentric girl? That can\'t be me — I\'m Mai, the magician of Makai.',
  '向日葵要是也有毒就好了。': 'If only sunflowers were poisonous too.',
  '吓跑排队中的普通顾客。': 'Scares away regular customers in the queue.',
  '听说也是外界流行的街边小吃，在特制的面糊中裹上引发奇迹的章鱼脚，糯脆的外衣之下Q弹的章鱼脚产生让人幸福的感觉。': 'Said to be a popular street food from the outside world. Wrapping miracle-inducing octopus legs in a special batter — beneath the crispy skin, the bouncy octopus legs create a feeling of happiness.',
  '听说妖兽尾巴越多则越强，但一般妖怪猫都只有两条尾巴。': 'They say the more tails a beast youkai has, the stronger they are, but most youkai cats only have two tails.',
  '听说是外界流行的街边小吃，使用面糊和各种食材混合后在铁板上烧制而成，脆香而丰富，因其百变和平价的特性被所有人喜爱。': 'Said to be a popular street food from the outside world. Made by mixing batter with various ingredients and cooking on an iron plate. Crispy, savory, and rich — loved by everyone for its versatility and affordability.',
  '听说是外面世界冬季穿的水手服，为了对抗冬天的冷空气，特意加长了袖子和裙子的长度，以及进行了深色的设计，看起来保暖多了…但是等等，为什么冬季还要穿水手服？！': 'Said to be a winter sailor uniform from the outside world. To combat the cold winter air, the sleeves and skirt were specially lengthened with a dark-colored design — looks much warmer... But wait, why wear a sailor uniform in winter?!',
  '听说看到报春精会带来好运，我也想见一见呢。': 'They say seeing a spring herald fairy brings good luck — I want to see one too.',
  '听说鬼又开始在幻想乡行动了？该不会卷土重来吧？': 'I heard oni are active in Gensokyo again? Could they be making a comeback?',
  '吵吵闹闹的人类小不点儿，这种家伙要是在以前…现在好好接触下来以后，偶尔看着他们亲近自己的笑脸，会不知不觉地感到疲劳减少，真是奇怪啊。': 'These noisy little human brats — in the old days, these types... But now, after getting to know them, occasionally seeing their smiling faces warming up to me, I unconsciously feel less tired. How strange.',
  '吸引大量居民前来就餐。': 'Attracts a large number of residents to come dine.',
  '呃，一会儿去找朋友要些果子垫垫肚子好了。': 'Hmm, I\'ll go ask a friend for some fruits to fill my stomach later.',
  '呜呜呜，你怎么觉得我会有那么多钱的！': 'Waah, what makes you think I have that much money!',
  '呜呜，我要找kk投诉你开黑店！': 'Wah, I\'m going to report your shady shop to KK!',
  '呜呜，我要是也能做出这个味道就好了！': 'Wah, if only I could make food that tastes like this!',
  '呜呜，老板娘，轮到我点单了吗？不要无视我啦！诶，这是要重新排队的意思吗？': 'Wah, boss lady, is it my turn to order? Don\'t ignore me! Wait, does this mean I have to line up again?',
  '呜哇，实在是…太美味了♡！咕咕！': 'Wow, this is... so delicious ♡! Coo coo!',
  '呜啊，你这家伙，等着痛失魔界市场吧！': 'Ugh, you — just wait until you lose the Makai market!',
  '味道不错诶，教教我怎么做呗。': 'Tastes good — teach me how to make it.',
  '味道不错，相信你不会止步于此。': 'Good flavor — I trust you won\'t stop here.',
  '味道极佳，值得称赞！': 'Excellent taste — worthy of praise!',
  '呵——！我接受你的挑衅——！': 'Ha—! I accept your provocation—!',
  '呵呵！麻雀之食贵于玉，薪贵于桂。': 'Hehe! The sparrow\'s food is more precious than jade, its fuel dearer than cinnamon.',
  '呸！难吃！': 'Bleh! Disgusting!',
  '呼呼~比起那种大叔才会喜欢的烈酒，我还是更喜欢温和一点的饮料。': 'Hehe~ Compared to that strong liquor only old men like, I prefer milder drinks.',
  '命莲寺特产。传说观音菩萨右手持杨枝，左手持盛有甘露的净瓶，用杨柳枝撒下甘露会带来好运。许多慕名而来的信徒都会饮上一杯。': 'A Myouren Temple specialty. Legend says that Guanyin holds a willow branch in the right hand and a pure vase of sweet dew in the left. Sprinkling sweet dew with the willow branch brings good fortune. Many devoted visitors come to drink a cup.',
  '命莲寺的弟子中有个能够变幻形态的入道，只要见过他的样子，就很容易联想到棉花糖。加入桃汁制作的棉花糖甜而不腻，造型生动有趣，深受小孩子的喜爱。': 'Among the disciples of Myouren Temple is a shape-shifting nyuudou whose appearance easily reminds one of cotton candy. Cotton candy made with peach juice is sweet without being cloying, with a fun and vivid shape that children love.',
  '和喜欢宅在屋里喝茶的博丽巫女不同，早苗小姐非常勤奋，随处都能看到她在努力收集信仰的身影。以人类之身来收集信仰真是了不起啊，似乎是什么现人神呢。': 'Unlike the Hakurei shrine maiden who likes to stay home drinking tea, Miss Sanae is very diligent — you can see her everywhere working hard to gather faith. Gathering faith as a human is truly remarkable. She seems to be some kind of living god.',
  '和因幡用来吸引游客的纪念品一样徒有其表。但谁能拒绝小兔子呢？！': 'Just for show, like Inaba\'s souvenirs to attract tourists. But who can refuse cute little bunnies?!',
  '和女仆长送来的甜点一样无聊…': 'As boring as the sweets the head maid sends...',
  '和我们家的女仆比起来还差得远呢。': 'Still far behind compared to the maids at our place.',
  '和我印象中的味道还差了一点。': 'Still a bit off from the taste I remember.',
  '和橙学着做饭的水平差不多呢。': 'About the same level as Chen when she was learning to cook.',
  '和雪相处下来，会发现她是一个乐观开朗、非常重视友谊的孩子，不过在天真无邪的同时也有一点冒失，有点像是和我一样的鸟脑袋呢！除此之外，原来她和舞是好朋友呀，怪不得总能看见她俩在一起摆摊呢！不过雪一个人摆摊的时候经常会算错价格，或许应该给她推荐一下人里最好的私塾寺子屋呢！': 'Getting to know Yuki, you\'ll find she\'s an optimistic and cheerful child who values friendship greatly. Though innocent, she\'s also a bit clumsy — kind of a birdbrain like me! Also, turns out she and Mai are good friends — no wonder they\'re always at their stall together! But when Yuki runs the stall alone, she often miscalculates prices. Maybe I should recommend the best private school in the human village — Terakoya!',
  '和黑水的味道差不多吧。': 'Tastes about the same as black water.',
  '咖啡被瞬间暴露于真空中，会因为过低的气压导致瞬间沸腾，因汽化现象而被不断带走热量的水最终会在沸腾的过程中凝固。这种一边沸腾一边冰冻的咖啡是月都的特色饮料。': 'When coffee is instantly exposed to vacuum, the extremely low pressure causes it to boil instantly. The water, continuously losing heat through vaporization, eventually freezes during the boiling process. This simultaneously boiling and freezing coffee is a signature drink of the Lunar Capital.',
  '咱们妖精哪来那么多钱。': 'Where would fairies get that much money?',
  '咱！没！钱！': 'We! Have! No! Money!',
  '咲夜只给我准备了这么多钱！': 'Sakuya only prepared this much money for me!',
  '咲夜小姐的飞刀就像是长了眼睛一样。': 'Miss Sakuya\'s throwing knives seem to have eyes of their own.',
  '咳咳，我有点不舒服，先回去了…': 'Ahem, I\'m feeling a bit unwell, I\'ll head back first...',
  '咸若啮檗吞针！': 'Salty as gnawing bark and swallowing needles!',
  '哇——这个世界欺负柔弱的妖精！': 'Wah — this world bullies weak fairies!',
  '哇——这个世界的老板娘这么生猛的吗！': 'Wah — the boss lady in this world is this fierce?!',
  '哇啊——我再也不要来了！': 'Waah — I\'m never coming back!',
  '哇塞，下次我一定要带大家来一起分享！': 'Wow, next time I have to bring everyone to share!',
  '哇！料理和星星一样会闪光耶！': 'Wow! The food shines just like the stars!',
  '哇，不错嘛！': 'Wow, not bad!',
  '哇，原来还发生过这种事情。式神什么的好像也明白一点儿了。蓝小姐照顾橙，照顾紫小姐，性格温柔又体贴，真希望她能不这么辛苦。': 'Wow, so something like that happened. I think I understand shikigami a little better now. Miss Ran takes care of Chen and Miss Yukari. Her personality is so gentle and caring — I really wish she didn\'t have to work so hard.',
  '哈哈哈，今天会用什么来招待我们呢！': 'Hahaha, what will you treat us to today!',
  '哎呀，忘记带钱了呢。': 'Oops, I forgot to bring money.',
  '哎，真没劲。': 'Sigh, how boring.',
  '哗~虽然妖精是不用吃东西的，但是还是来叨扰啦！': 'Ta-da~ Fairies don\'t need to eat, but I came to bother you anyway!',
  '哦哦！还挺热闹的嘛！一直放任着不管，现在就是\u201C回收\u201D的时候！': 'Ooh! Quite lively! After leaving things alone for so long, now it\'s time to "collect"!',
  '哦！谢谢。': 'Oh! Thanks.',
  '哦？原来也有这种店面啊。': 'Oh? So there are shops like this too.',
  '哦？竟这样对我，考虑清楚后果了吗？': 'Oh? You dare treat me like this — have you considered the consequences?',
  '哪怕回到畜生界，都寻找不到这样合我口味的美食啊。': 'Even back in the Animal Realm, I couldn\'t find food this much to my liking.',
  '哭…我真是太没用了…': 'Sob... I\'m so useless...',
  '哼，吾来汝店，本即无上荣光。': 'Hmph, my presence in your shop is the highest honor.',
  '哼，地上也一样是欺善怕恶。': 'Hmph, the surface is the same — bullying the weak and fearing the strong.',
  '哼，就地上人而言，差不多也就这种程度吧。': 'Hmph, for a surface-dweller, this is about the expected level.',
  '哼，朽木难雕。': 'Hmph, you can\'t carve rotten wood.',
  '哼，看来我是太纵容你了啊。': 'Hmph, seems I\'ve been too lenient with you.',
  '哼，这一顿也就值这么多！': 'Hmph, this meal is only worth this much!',
  '唉，一个个家伙都是要人操心的。': 'Sigh, everyone is such a handful.',
  '唉，侍奉幽幽子大人累得快让我的骨头散架了。': 'Sigh, serving Lady Yuyuko is so tiring my bones are about to fall apart.',
  '唔…还算好吃吧？': 'Mm... it was decent, I guess?',
  '唔姆…味道好奇怪的样子…明明是舞舞推荐的餐厅来着。': 'Hmm... the taste seems weird... Even though it was the restaurant Mai-Mai recommended.',
  '唔，月亮和地上的物价可能不太一样。': 'Hmm, prices on the moon and the surface are probably different.',
  '唔，辛苦了…': 'Mm, good work...',
  '唔，这不是我印象中的味道呢。': 'Hmm, this isn\'t the flavor I remember.',
  '唔，麻雀的小碎骨有点太多了…': 'Hmm, the sparrow has too many tiny bones...',
  '啊——这就是我无论如何都无法实现出来的味道吗！': 'Ah — so this is a flavor I could never possibly achieve!',
  '啊，又有新的灵感了！': 'Ah, I have new inspiration again!',
  '啊，差点预算就被爆破了。': 'Ah, I almost blew my budget.',
  '喂喂，做成这样没关系吗…': 'Hey hey, is it really okay to make it like this...',
  '喂喂？！不怕我报导出去吗？': 'Hey?! Aren\'t you afraid I\'ll report this?',
  '喂！这完全就是黑店吧！！': 'Hey! This is totally a scam shop!!',
  '善恶到头终有报。': 'Good and evil always get their due in the end.',
  '喜欢虫子的老友。虽然咱们已经认识了很久，但我还是受不了围在她身边的那群虫子。': 'An old friend who likes bugs. Though we\'ve known each other for a long time, I still can\'t stand the bugs swarming around her.',
  '喜欢黑暗的老友，总觉得她脑子空空的样子。但不得不说，和我很合得来。无论是第一点还是第二点。': 'An old friend who likes darkness. She always seems empty-headed. But I have to say, we get along well — both with the first point and the second.',
  '喝酒就是要在这种热闹的地方才有味道嘛。': 'Drinking is only good in a lively place like this.',
  '嗯嗯嗯！好吃好吃。': 'Mmm! Delicious, delicious.',
  '嗯，中规中矩，我就勉为其难给个及格分吧。': 'Hmm, average. I\'ll reluctantly give it a passing score.',
  '嘛，还不错还不错。': 'Well, not bad, not bad.',
  '嘿嘿，我的冰可是连飞鸟都能打落哦！': 'Hehe, my ice can knock even flying birds out of the sky!',
  '嚯嚯嚯——不愧是老朽寄望的妖兽。': 'Ho ho ho — as expected of the beast youkai this old one has high hopes for.',
  '四方食事，不过一碗人间烟火。': 'All the world\'s cuisine is but a bowl of earthly sustenance.',
  '回去就找个机会实验下最新的超位魔法。': 'I\'ll find a chance to test the latest super-tier magic when I get back.',
  '回过神来已经几天没吃饭了啊。': 'I just realized I haven\'t eaten in days.',
  '因为万宝槌的力量而活过来的道具。似乎受哪位高人指点，将体内本该被回收的小槌魔力转化成了自己的魔力，从此得到了真正的生命。': 'A tool brought to life by the power of the Miracle Mallet. Apparently guided by some master, it converted the Mallet\'s magic that should have been reclaimed into its own, thus gaining true life.',
  '因为妖怪之山基本没什么侵入者，所以守卫的工作非常清闲。夜雀食堂开张以后，她对于工作之余多了个去处似乎非常高兴，面上虽然没怎么显露，但尾巴暴露了心情。': 'Since Youkai Mountain has hardly any intruders, guard duty is quite relaxed. After the Izakaya opened, she seems very happy to have somewhere to go after work — her face doesn\'t show it much, but her tail gives away her mood.',
  '因为性格太过于一板一眼，对待训练又十分严厉，兔子们都不太亲近她。和清闲自在的姐姐相反，依姬小姐似乎一直处于无法放松的状态，可能聪明人总是容易想太多…': 'Because of her overly rigid personality and strict training methods, the rabbits don\'t warm up to her. Opposite of her carefree sister, Miss Yorihime seems to always be unable to relax — perhaps intelligent people tend to overthink...',
  '国之宴席也莫过于此！': 'Even a national banquet cannot surpass this!',
  '圣人今天也倾听了我的烦恼，为我指点迷津。': 'The saint listened to my troubles today too and guided me.',
  '在2021年万圣节期间登录游戏获得的限定晚装，结合万圣节的气氛做了特别的设计，可爱又精怪。': 'A limited evening dress obtained by logging into the game during Halloween 2021. Specially designed to match the Halloween atmosphere — cute and mischievous.',
  '在2021年圣诞节活动期间登陆游戏获得的限定礼服，毛茸茸的非常暖和，在注重保暖的同时也没有舍弃可爱。在冬日里看到这样一抹亮色，会让人心情变得很好吧？': 'A limited dress obtained by logging into the game during the Christmas 2021 event. Fluffy and very warm, maintaining cuteness while keeping warm. Seeing such a bright color in winter would put anyone in a good mood, wouldn\'t it?',
  '在2022年春节活动期间登陆游戏获得的限定礼服，红黄配色象征着喜气和财富，在春回大地、万象更新的这一天尽情收获祝福吧。': 'A limited dress obtained by logging into the game during the 2022 Spring Festival event. The red and yellow color scheme symbolizes joy and wealth. Enjoy all the blessings on this day of spring\'s return and renewal.',
  '在2023年米斯蒂娅角色日活动期间登陆游戏获得的限定礼服。蓬松可爱的蛋糕裙既纯真又梦幻，寄寓着希冀之情，为庆贺米斯蒂娅角色日及《东方夜雀食堂》Nintendo Switch企划启动，而特意制作的纪念物。': 'A limited dress obtained by logging into the game during the 2023 Mystia Character Day event. The fluffy and cute cake skirt is both innocent and dreamlike, carrying hope and wishes. A specially made memento celebrating Mystia\'s Character Day and the Nintendo Switch launch of "Touhou Mystia\'s Izakaya."',
  '在一些阴郁的妖怪中流行的零食，在浓郁的芝士中混有白果独有的苦味，能让味觉产生强烈的回甘后味，但我完全无法理解。': 'A snack popular among gloomy youkai. Rich cheese mixed with ginkgo\'s distinctive bitterness creates a strong sweet aftertaste — but I can\'t understand it at all.',
  '在人类村子开私塾的妖怪。哎呀，总觉得她与其说是妖怪，倒不如说更像是人类呢。': 'A youkai who runs a private school in the human village. Hmm, she feels more like a human than a youkai.',
  '在人类村子里摆摊贩卖食材的魔界人。名字虽然叫雪，但是修行的似乎却是火系魔法。平时经过人类村子的时候总能看见她不知疲倦的贩卖着囤积的各种食材，然后兑换成金币随身携带。': 'A Makai resident who runs a stall selling ingredients in the human village. Though her name means "snow," she apparently practices fire magic. Whenever I pass through the human village, I always see her tirelessly selling her stockpiled ingredients, converting them to gold coins to carry around.',
  '在人类村子里摆摊贩卖食材的魔界人，修行的似乎是冰系魔法。背后有着大大的白色翅膀，难道其实和我一样是鸟类妖怪吗？平时经过人类村子的时候总能看见她在贩卖自制的各种饮料，虽然满口的不情愿但是却忙前忙后乐此不疲的样子呢，真是奇怪！': 'A Makai resident who runs a stall selling ingredients in the human village, apparently practicing ice magic. With large white wings on her back — could she actually be a bird youkai like me? Whenever I pass through the human village, she\'s always selling her homemade drinks. Though she constantly complains, she keeps busily working with tireless enthusiasm — how strange!',
  '在你的料理下，感觉肉都会发光了！': 'Under your cooking, even the meat seems to glow!',
  '在其中放入油，高温下不管什么东西丢进去炸一下，都可以变成可口的料理，实在是魔鬼的技术！…但这样的料理并不健康。': 'Put oil in it, and at high temperature, anything thrown in to fry becomes delicious — truly a devilish technique! ...But such food isn\'t healthy.',
  '在加入了大量的苏打后，这种起泡清酒酸甜的口感，以及较低的酒精度，使其很受女性的欢迎；可以说是清酒的香槟版本。': 'After adding plenty of soda, this sparkling sake with its sweet and sour taste and low alcohol content is very popular among women. You could call it the champagne version of sake.',
  '在厨房放出黑雾，让你无法辨识哪些是厨具，哪些是食柜，黑雾持续20秒消失。': 'Releases black mist in the kitchen, making it impossible to distinguish between cookware and food cabinets. The mist lasts 20 seconds.',
  '在发酵的圆面饼上面覆盖各种配料烤制而成，完美兼顾了营养和品相，焦糖洋葱的醇香滋味更是为其带来了多重的舌尖享受。可爱的猫咪外形让人有些不忍下嘴呢。': 'Baked on a fermented round dough covered with various toppings, perfectly balancing nutrition and appearance. The rich flavor of caramelized onions adds multiple layers of taste pleasure. The cute cat shape makes it almost too adorable to eat.',
  '在哪里能买到圣人同款耳机呢？': 'Where can I buy the same earphones as the saint?',
  '在地下室的展示柜中启用后，各地会出现钓鱼点。': 'After enabling in the basement display case, fishing spots appear in various locations.',
  '在场上开启数个会变换位置的隙间，如果接近隙间，则会被吸入其中，然后随机传送到其他隙间处，同时托盘内的酒水会消失，持续30秒。': 'Opens several position-shifting gaps on the field. Getting close to a gap sucks you in and teleports you to another gap randomly, while drinks on the tray disappear. Lasts 30 seconds.',
  '在场上种下一朵鲜花并利用能力使其生长，满心情时额外种下一朵，每朵生长的鲜花每24秒生产25小费。除幽香以外的稀有顾客释放奖励符卡时，随机一朵生长的鲜花将吸收符卡之力而盛放，吸引当地出没的稀有顾客造访食堂，被鲜花吸引来的稀有顾客会摘走这朵鲜花。鲜花盛放期间顾客用餐结束后额外提高15心情，15秒后鲜花凋谢，获得一层\u201C落英缀裳\u201D。{{br}}\u201C落英缀裳\u201D：可以抵挡一次中断Combo的失误。': 'Plants a flower and grows it with her ability. At full satisfaction, plants an extra flower. Each growing flower produces 25 tips every 24 seconds. When a rare customer (other than Yuuka) releases a reward spell card, a random growing flower absorbs the card\'s power and blooms, attracting a local rare customer to visit. The attracted customer will pick the flower. While a flower is in full bloom, customers gain 15 extra satisfaction after dining. After 15 seconds, the flower wilts, granting one layer of "Fallen Petals Adorning the Garment."{{br}}"Fallen Petals Adorning the Garment": Can block one combo-breaking mistake.',
  '在外界似乎被称为\u201CCannoli\u201D的西式甜点，最早起源于意大利巴勒莫，也是魔界最为流行的下午茶点心。奶油甜煎饼卷的制作方式非常奇特：首先用特制的铁棍或者锡箔纸固定住面粉做的酥皮，放入油锅中炸至金黄，然后往里面填入奶油馅料，最后在顶端撒上可可粉、糖霜以及可食用金箔便大功告成了。\u201C这种甜点嘛，对于本魔神而言轻轻松松啦！\u201D作为神绮平时下午茶必备的甜点，其本人使用魔法制作的奶油甜煎饼卷受到魔界人的好评，直到有一天，她灵机一动没有使用魔法而是亲手下厨…': 'A Western dessert called "Cannoli" in the outside world, originating from Palermo, Italy —also the most popular afternoon tea treat in Makai. The preparation is quite unique: first secure the flour-based pastry shell on a special iron rod or tin foil, deep-fry until golden, fill with cream filling, and finally sprinkle cocoa powder, powdered sugar, and edible gold leaf on top. "This kind of dessert is a breeze for this great god!" As Shinki\'s essential afternoon tea treat, her magic-made cannoli received great reviews from Makai residents — until one day she had the bright idea of cooking by hand instead of using magic...',
  '在外界似乎被称为\u201CGazpacho\u201D的西式汤品，历史最早可以追溯到西班牙大航海时期。相传最早是西班牙人在通过海路与各国贸易中，使用各国独特的蔬菜水果混合大蒜而成的简单料理。经过多个世纪的发展，现代的西班牙冷汤已经不只是一道简单的蔬菜大杂烩，而是额外衍生出了如添加鲜花、火腿、草莓或是虾肉蟹肉之类的各种高级版本。不过由于神绮大人无法掌握，因此在魔界流行的是最基础的版本。': 'A Western soup called "Gazpacho" in the outside world, dating back to Spain\'s Age of Exploration. Legend has it that Spaniards originally made this simple dish by mixing various countries\' unique vegetables and fruits with garlic during maritime trade. After centuries of development, modern Spanish cold soup is no longer a simple vegetable medley, but has evolved into various premium versions with additions like flowers, ham, strawberries, or shrimp and crab meat. However, since Lady Shinki couldn\'t master these, the most basic version is the one popular in Makai.',
  '在外界似乎被称为\u201COkroshka\u201D的西式汤品，是一道适合在夏季消暑降温的料理。使用大量夏季产出的蔬菜，混合炼乳、开菲尔与格瓦斯。做法非常简单，只需要将混合物放入冰柜，等到冷冻完成后加入盐和黑胡椒即可直接食用。就连神绮都能轻松学会这道菜，因此在魔界非常流行。': 'A Western soup called "Okroshka" in the outside world — a dish perfect for cooling down in summer. Made with plenty of summer vegetables mixed with condensed milk, kefir, and kvass. Very simple to make: just put the mixture in the freezer, then add salt and black pepper once frozen. Even Shinki can easily learn this dish, making it very popular in Makai.',
  '在外界似乎被称为\u201CPoutine\u201D的高热量西式快餐，最早起源于加拿大魁北克省，是加拿大的国菜。因该省有着大量法国后裔，因此当地人在法式炸薯条的基础上，加上了肉汁、手撕牛肉与奶酪块，构成了这道如同塔一般宏伟的热量炸弹。现代的肉汁奶酪薯条还经常会在此基础上额外加上羊肉粒、墨西哥辣椒、培根条、烧烤酱、牧场沙拉酱以及塔塔酱，真是让人看一眼就会腻到反胃…\u201C多就是好！舞舞绝对会喜欢！\u201D雪如此评价这道料理。': 'A high-calorie Western fast food called "Poutine" in the outside world, originating from Quebec, Canada — Canada\'s national dish. Due to the province\'s large French-descended population, locals added gravy, pulled beef, and cheese curds to French fries, creating this tower-like calorie bomb. Modern poutine often includes lamb bits, jalapeños, bacon strips, BBQ sauce, ranch dressing, and tartar sauce — just looking at it might make you sick... "More is better! Mai-Mai will definitely love it!" is how Yuki reviews this dish.',
  '在外界似乎被称为\u201CRisotto\u201D的烩饭料理。魔界之神对此进行改良，使用糯米与帕尔马芝士糅合，添上辣椒碎与菌菇碎，在锅中炒热后，再撒上柔软的花瓣，这道西洋感满满的烩饭就做成了。香糯的芝士烩饭中，晶莹的菌菇碎如同满天星斗，照亮了遍布鲜花的原野。一口下去，是幻想乡春樱漫野结合魔界夜空般的甜辣。': 'A risotto dish from the outside world, improved by the God of Makai. Combining glutinous rice with Parmesan cheese, adding chili flakes and mushroom pieces, stir-frying in a pan, then sprinkling soft petals — this Western-style risotto is complete. In the fragrant, chewy cheese risotto, the glistening mushroom pieces are like stars illuminating a flower-covered meadow. Each bite is a sweet and spicy blend of Gensokyo\'s spring cherry blossoms and Makai\'s night sky.',
  '在外界似乎被称为\u201CSolyanka\u201D的西式汤品，最早起源于俄罗斯寒冷的远东地区。相传，当时的人们为了度过寒冷的严冬，只能使用手中仅有的蔬菜和肉类，加上大量的酸黄瓜和柠檬来做成这道又酸又辣的浓汤。也正因为其又酸又辣，在魔界似乎没有流行起来，神绮也表示不用专门学新的菜谱真是帮了大忙。\u201C酸酸辣辣，喝完就有用不完的力量了，舞舞绝对会喜欢！\u201D雪如此评价这道料理。': 'A Western soup called "Solyanka" in the outside world, originating from Russia\'s cold Far East. Legend has it that to survive the harsh winters, people could only use what vegetables and meat they had, plus lots of pickled cucumbers and lemon to make this sour and spicy thick soup. Because of its sour and spicy nature, it never caught on in Makai, and Shinki expressed relief at not having to learn a new recipe. "Sour and spicy — after drinking it you\'ll have endless energy. Mai-Mai will definitely love it!" is how Yuki reviews this dish.',
  '在幻想乡里你是东洋派还是西洋派？选哪边都会得罪另一边吧。': 'In Gensokyo, are you team Eastern or team Western? Choosing either side offends the other.',
  '在当日结束前触发时，冻结所有剩余时间大于44秒的Buff时间，使之不再减少，直至当日结束。再次触发或在当日结束后触发，所有剩余时间大于44秒的Buff时间增加当前剩余时长的10%（每种类型的Buff至多通过此符卡增加17秒）。': 'When triggered before the day ends, freezes all buff timers with more than 44 seconds remaining, preventing them from decreasing until the day ends. When triggered again or after the day ends, all buff timers with more than 44 seconds remaining increase by 10% of their current remaining time (each buff type can gain at most 17 seconds via this spell card).',
  '在我心里你应该能做得更好。': 'In my heart, I know you can do better.',
  '在我的漫长人生中，这样美味的料理也属罕见。': 'In my long life, cuisine this delicious is truly rare.',
  '在无尽的未来里，有无数种可能。': 'In the endless future, there are infinite possibilities.',
  '在日本很有名的中华料理。使用独特的豆腐烹饪技巧烹制而成的辛辣料理，用它来拌饭吃可是会上瘾的哦。': 'A famous Chinese dish in Japan. A spicy dish made with unique tofu cooking techniques — eating it mixed with rice is absolutely addictive.',
  '在村子里的医馆担任护士的人类，性情直率纯粹，在医护的方面非常细心，对入院治愈后仍不爱惜自己身体的病人恨铁不成钢。面对这种病人，她会偷偷在下针的时候加大力度…': 'A human nurse working at the village clinic. Straightforward and pure in character, very attentive in medical care. She gets frustrated with patients who don\'t take care of themselves even after being cured. With such patients, she secretly pushes the needle in harder...',
  '在树干上常常可以采集的昆虫外壳，较为常见。': 'Insect shells commonly found on tree trunks. Fairly common.',
  '在水果派里探出一个鱼头，仿佛看着地底的天花板，充满了和地狱相衬的绝望气息。': 'A fish head peeking out of a fruit pie, staring at the underground ceiling with a sense of despair befitting hell.',
  '在永远亭就地取材，使用新鲜的食材和米饭一起塞进竹筒中蒸熟。饭被竹子的清香充分浸润后，中和了山猪肉带来的油腻。': 'Made with locally sourced ingredients at Eientei — fresh ingredients and rice stuffed into bamboo tubes and steamed. The rice absorbs the bamboo\'s fresh fragrance, balancing out the grease of the wild boar meat.',
  '在神灵庙里有不少拜神子为师，希望学习仙术的弟子。不过似乎只被支使用来打杂。看起来总是一副斗志昂扬、雄心勃勃的样子…说不定打杂也是一个很有趣的工作？': 'At the Divine Spirit Mausoleum, many disciples worship Miko as their teacher, hoping to learn hermit arts. But they seem to only be used for chores. They always look full of fighting spirit and ambition... Maybe doing chores is actually an interesting job?',
  '在红魔馆种植的用于酿酒的葡萄。': 'Grapes grown at the Scarlet Devil Mansion for winemaking.',
  '在这个地方活着啊，还是要顺应时代，不能太墨守成规啊。': 'Living in this place, you have to go with the times — can\'t be too set in your ways.',
  '在这种地方，可以得到许多有趣的情报。': 'In a place like this, you can get a lot of interesting information.',
  '在高海拔深山中圈养的黑毛猪肉，非常高级。': 'Black-haired pork raised in high-altitude deep mountains. Very premium.',
  '在魔界的烈酒里加入热咖啡，搅拌到融化后，再在顶部盖上一团细腻的奶油，由奶香到酒香再到咖啡香层次分明，口感醇厚，还能驱除一身的寒意。': 'Adding hot coffee to Makai spirits, stirring until blended, then topping with a dollop of fine cream. The flavors layer from creamy to boozy to coffee — rich and mellow, dispelling all chills.',
  '在鱼馅儿内加入适量蜂蜜搅拌后，碾压成鱼饼，投入油锅炸至金黄色，随炸随食。': 'Mix an appropriate amount of honey into the fish filling, press into fish cakes, and deep-fry until golden. Eat fresh from the fryer.',
  '在黑暗的风穴遇到的亲切的指路人。因为知道自己惹人讨厌所以几乎不会到村里去，明明那么可爱…真希望地上的大家也能认识她呢！': 'A kind guide met in the dark Wind Cave. She almost never goes to the village because she knows people find her annoying, even though she\'s so cute... I really wish everyone on the surface could meet her!',
  '地上和畜生界也没什么不同，无趣。': 'The surface is no different from the Animal Realm — boring.',
  '地上是不是有很多这样的店呢。': 'Are there many shops like this on the surface?',
  '地上有如此珍馐，让人几欲流连忘返。': 'Such delicacies on the surface make one want to linger forever.',
  '地上有这么美味的食物，谁还会想回到月亮上呢？': 'With food this delicious on the surface, who would want to return to the moon?',
  '地上现在还有能够退治鬼的专家吗？': 'Are there still experts who can exterminate oni on the surface?',
  '地上的兔子捣的确实是年糕吧？': 'The rabbits on the surface really do pound rice cakes, right?',
  '地上的小丑是怎么样的呢？': 'What are clowns like on the surface?',
};

// Apply translations
let content = fs.readFileSync('app/data/i18n/en.ts', 'utf8');
let count = 0;
for (const [key, value] of Object.entries(translations)) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`('${escaped}':\\s*)'',`, 'g');
  const newContent = content.replace(regex, `$1'${value.replace(/'/g, "\\'")}',`);
  if (newContent !== content) {
    count++;
    content = newContent;
  }
}
fs.writeFileSync('app/data/i18n/en.ts', content);
console.log(`Updated ${count} translations in app/data/i18n/en.ts`);
console.log(`Expected: ${Object.keys(translations).length}`);
