import fs from 'fs';

// English translations for description keys batch 2 (keys 201-400)
const translations: Record<string, string> = {
  '以魔界茶会为印象制作的甜品。表面看起来是一个巧克力做的茶壶，茶壶的肚子里是层层堆叠的奶油蛋糕，周围装饰着蘑菇和西蓝花，就像某个故事里的巧克力房子一样，是充满了梦幻和不可思议的幸福甜品。': 'A dessert inspired by a Makai tea party. On the surface it looks like a chocolate teapot, with layers of cream cake stacked inside, decorated with mushrooms and broccoli around it — just like a chocolate house from some fairy tale. A fantastical and wonderfully happy dessert.',
  '以魔神之翼为原型设计而成的咖啡色千层酥，苦涩与鲜香的夹心结合着酥脆的酥皮，一口咬下去别有一番风味。 最顶层使用成块的巧克力配上草莓果酱作为点缀，看起来就像魔神的翅膀一般。': 'A coffee-colored mille-feuille designed after a demon god\'s wings. The bittersweet and savory filling combined with crispy pastry creates a unique flavor in every bite. The top layer is decorated with chocolate blocks and strawberry jam, looking just like a demon god\'s wings.',
  '任何人都不该被时间轻易抹去。': 'No one should be easily erased by time.',
  '仿佛是融化在可口的冰沙中的毛玉，佐以冻柠口味，在炎热的夏季，不知拯救了多少人命。': 'Like kedama melted in delicious shaved ice, with a frozen lemon flavor. In the hot summer, who knows how many lives it has saved.',
  '优秀的料理可以治疗心病，受教了。': 'Excellent cuisine can heal the soul — I\'ve learned something.',
  '伙伴可以通过\u201C延展手臂\u201D远程上菜上酒，持续120秒。': 'Partners can serve food and drinks remotely via "Extended Arms" for 120 seconds.',
  '伙伴在食堂区域移动时可以穿过顾客或障碍物，持续30秒。': 'Partners can pass through customers and obstacles while moving in the dining area for 30 seconds.',
  '伙伴移动速度下降30%，工作速度下降50%，持续30秒。': 'Partner movement speed decreases by 30% and work speed decreases by 50% for 30 seconds.',
  '传说一杯就能让酒量无底洞一般的鬼族醉生梦死的传说之酒…但我见到的是…鬼明明都当做凉白开来喝的？！传说一点儿都不靠谱啊。': 'A legendary drink said to knock out even the oni\'s bottomless drinkers with just one cup... But what I saw was... the oni were drinking it like plain water?! Legends can\'t be trusted at all.',
  '传说中和鬼立下赌约并获胜的人类剑士所创下的烤串流派，特别使用了野性十足的肉类烧制而成，食之有种冲天的气魄，让人惊叹不已。': 'A skewer style created by a legendary human swordsman who made a bet with an oni and won. Made with wild, hearty meats, eating it fills you with soaring spirit — truly astonishing.',
  '传说中是少彦名神的后裔一族，身长只有一寸左右。因为一直在城里没有出去过，所以普遍缺乏常识，但拥有很强的求知心，对外界十分向往。': 'Supposedly descendants of the god Sukunabikona, standing only about one inch tall. Having never left the castle, they generally lack common sense but have a strong thirst for knowledge and yearn for the outside world.',
  '传说中气焰嚣张、目中无人的不良天人，如果可以的话，真不想招待这样的客人啊…': 'A legendarily arrogant and overbearing delinquent celestial. If possible, I\'d really rather not serve this kind of customer...',
  '传说中由麻雀酿的酒。将米粒藏入截断的竹中，当竹中有水时，日经月累便成佳酿。据说喝了此酒会舞无休止，是带着\u201C诅咒\u201D的美味呢。': 'A legendary sake brewed by sparrows. Rice grains hidden in cut bamboo, with water over days and months, becomes fine wine. They say drinking it makes you dance endlessly — a "cursed" delicacy.',
  '传说中的夜雀食堂应该不止这种程度…': 'The legendary Izakaya should be better than this...',
  '传说中的河童只是擅于弄水，幻想乡里的河童却还擅于经商，可以说是我的大前辈。那份游刃有余地拨着算盘的身姿，偶尔会让我移不开眼睛呢。': 'Legendary kappa are only skilled with water, but Gensokyo\'s kappa are also skilled at business — you could call them my seniors. The way they handle the abacus so effortlessly sometimes makes me unable to look away.',
  '传说中穿上羽毛就是鸟，脱下羽毛就会变成少女的妖怪。通过收集别人的指甲可以预知福祸，所以从事占卜业的很多。大概是为了保持神秘，说话总是神神叨叨的。': 'A legendary youkai that becomes a bird when wearing feathers and turns into a girl when taking them off. They can predict fortune and misfortune by collecting others\' nails, so many work in divination. Perhaps to maintain mystery, they always speak cryptically.',
  '传说中能够读心的觉妖怪，名字也是觉。大概是对自己的种族或能力很自豪吧？因为日以继夜都在工作，所以没什么搭话的机会…': 'A legendary satori youkai who can read minds, whose name is also Satori. She\'s probably proud of her race or ability? Since she works day and night, there\'s hardly any chance to talk...',
  '传说中非常非常可怕的吸血鬼，妖精客人们一直提醒我要小心…虽然看起来明明是个小孩子嘛。': 'A legendarily terrifying vampire — the fairy customers keep reminding me to be careful... even though she clearly looks like a child.',
  '传说庙里的那位圣人就是曾经名满天下的贵人。': 'Legend has it that the saint in the temple was once a famous noble.',
  '传说海的女儿最终为爱化为泡沫，这杯有着独特口味的鸡尾酒，或许就是她当时流下的、替她回归海中的眼泪。': 'Legend has it the daughter of the sea turned into foam for love. This cocktail with its unique flavor might be the tears she shed, returning her to the sea.',
  '传说连天狗喝了也会开心地跳舞的美味清酒，在妖怪之山开一次店就可以验证了吧。不同于其他无色的清酒，天狗踊带有淡淡的琥珀色。': 'A delicious sake said to make even tengu dance with joy. Opening shop at Youkai Mountain should prove it. Unlike other colorless sake, Tengu Dance has a faint amber color.',
  '传闻是超优质的肉牛品种，又称雪花肉，非常高级。': 'Rumored to be an ultra-premium beef breed, also known as marbled beef. Very high-grade.',
  '伺机寻找目标…好！一会儿就吓那个家伙吧！': 'Looking for a target... Got it! I\'ll scare that person later!',
  '似乎和我想象的有所出入。': 'It seems a bit different from what I imagined.',
  '似乎和神绮大人不用魔法的时候制作的炒菜味道很像呢！晚饭后回去还是加餐吃点薯片吧。': 'It tastes just like Lady Shinki\'s stir-fry when she doesn\'t use magic! I\'ll have some chips as a snack after dinner.',
  '似乎因为我来自地上，所以对我很亲切的月之使者，和永远亭的铃仙小姐有着一样的名字。偶尔会表现出对地上的向往，不知道是不是过去发生了什么…也可能是因为月之使者的训练太辛苦了吧。': 'A Lunar emissary who\'s very kind to me, perhaps because I\'m from the surface. She shares the same name as Eientei\'s Reisen. She occasionally shows longing for the surface — I wonder if something happened in the past... or maybe the Lunar emissary training is just too harsh.',
  '似乎是上古的凶兽…曾经是这样认为的。实际见了之后，才发现只是一只馋怪而已。食量很大，而且对口感的要求很高。': 'Supposedly an ancient ferocious beast... That\'s what I used to think. After actually meeting her, she turned out to be just a glutton. Has a huge appetite and very high standards for texture.',
  '住在妖怪山上的非常孤僻的种族，哪怕是同族之间也几乎没有交流。有传言说她们会抓走在山中迷路的小孩…但这是误会，虽然她们经常撂狠话，可她们只是不善言谈，其实是非常直爽善良的妖怪。': 'A very reclusive race living on Youkai Mountain — they barely interact even among themselves. Rumors say they snatch children lost in the mountains... but that\'s a misunderstanding. Despite their harsh words, they\'re just bad at communication and are actually very straightforward and kind youkai.',
  '住在永远亭的公主殿下，据说来自月亮。放着好好的月之公主不做，跑到幻想乡来当家里蹲到底是为什么呢？': 'The princess residing at Eientei, said to be from the moon. Why would she abandon being a Lunar princess to become a shut-in in Gensokyo?',
  '住在魔法森林的魔法使，有着金色的头发和白皙的皮肤，外貌精致得就像人偶一样。据说，她的家里也尽是些人偶。被她操纵的那些人偶栩栩如生，感觉还…蛮瘆人的。': 'A magician living in the Forest of Magic, with golden hair and fair skin — her appearance is as exquisite as a doll. They say her house is full of dolls too. The dolls she controls are so lifelike... it\'s actually kind of creepy.',
  '住持会定期在寺庙里举办怪谈大会，相当刺激哦。': 'The head priestess regularly holds ghost story gatherings at the temple — quite thrilling!',
  '佐上这样的菜肴，真是糟蹋了我的酒！': 'Pairing such a dish with my sake is simply wasting it!',
  '佛心传法，声若雷霆。': 'Preaching with a Buddhist heart, with a voice like thunder.',
  '作为和风料理的代表，将刺身级的三文鱼和金枪鱼鱼生配上芥末和酱油，引出鲜味的绝妙料理。': 'A quintessential Japanese dish — sashimi-grade salmon and tuna served with wasabi and soy sauce to bring out their exquisite umami.',
  '作为新闻素材的话感觉无波无澜呢。': 'As news material, it feels rather uneventful.',
  '作为稗田家第九代家主，我的责任重大。': 'As the ninth-generation head of the Hieda clan, my responsibility is great.',
  '你也会像那样赶我走吗？': 'Will you drive me away like that too?',
  '你以为这是谁的地盘？！': 'Who do you think this territory belongs to?!',
  '你以前参加我家的宴会也没给钱，总得给我打个折吧。': 'You didn\'t pay when you came to my party, so at least give me a discount.',
  '你以后也别想到我的店里来了！': 'Don\'t ever think about coming to my shop again!',
  '你们就拿这样的东西招待异世界的旅人吗？！': 'You serve something like this to travelers from another world?!',
  '你做的料理散发着和圣辇船一样的光辉！': 'Your cooking radiates the same brilliance as the Palanquin Ship!',
  '你加什么东西呀？！为什么会这么好吃？！': 'What did you put in this?! Why is it so delicious?!',
  '你可要想清楚哟…': 'You\'d better think carefully...',
  '你听说过幽灵食堂的都市传说吗？': 'Have you heard the urban legend about the ghost restaurant?',
  '你家的生意就像地狱一样红红火火咧。': 'Your business is booming like hellfire!',
  '你家附近的虫子？和我没关系啦！': 'The bugs near your house? Nothing to do with me!',
  '你就不怕我怨恨你吗？': 'Aren\'t you afraid I\'ll hold a grudge?',
  '你想下地狱吗？！': 'Do you want to go to hell?!',
  '你拥有的是让心花皆绽放的能力！': 'You have the ability to make all hearts bloom!',
  '你是偷偷藏了什么魔法吗？居然会有这么好吃的料理！': 'Did you secretly hide some magic? For the food to be so delicious!',
  '你有没有一点身为经营者的自觉啊？！': 'Do you have any self-awareness as a business owner?!',
  '你的事我很清楚哦，因为一直看着呢。': 'I know all about you — I\'ve been watching, after all.',
  '你的价格就像人类采用了十进制！': 'Your prices are like humans adopting the decimal system!',
  '你的努力我都看在眼里。': 'I see all your hard work.',
  '你看我像不像圣人被钉在十字架上？': 'Do I look like a saint nailed to a cross?',
  '你究竟是怎么把食物烹饪得这么难吃的？简直是在浪费粮食！': 'How on earth did you cook something this terrible? It\'s a total waste of food!',
  '你站在桥上看风景，看风景的人在楼上看你。': 'You stand on the bridge watching the scenery; the watcher above watches you.',
  '你竟然驱赶未来的勇者大人？！': 'You dare drive away the future hero?!',
  '你要好好工作，一定要按时把债务完成！': 'Work hard and make sure to pay off the debt on time!',
  '你还太嫩了啊。一会儿让我来教教你什么是真正的经营之道吧。': 'You\'re still too green. Let me teach you what real business management is about.',
  '你还真是贪心不足啊…': 'You really are never satisfied...',
  '你这儿还是太简陋了，要不要去我店里选几个道具，算你便宜哦。': 'Your place is still too shabby. Want to pick some equipment from my shop? I\'ll give you a discount.',
  '你这里太亮了，我的眼睛有点不舒服。': 'It\'s too bright here — my eyes are a bit uncomfortable.',
  '你都强买强卖，就别怪咱吃霸王餐了！': 'If you\'re going to force sales on us, don\'t blame us for dining and dashing!',
  '使全部正在就餐的顾客的心情暴涨至85%。': 'Boosts all currently dining customers\' satisfaction to 85%.',
  '使场上包括排队顾客在内的普通顾客额外获得一次续单上限和25%预算，每位普通顾客最多可以受到此效果影响三次。': 'Grants all regular customers on the floor (including those in queue) one additional reorder limit and 25% extra budget. Each regular customer can receive this effect up to three times.',
  '使店内的小费率额外增加15%。': 'Increases the tip rate in the shop by an additional 15%.',
  '使当日菜单上的三个料理无法被制作，持续30秒。': 'Makes three dishes on today\'s menu unable to be prepared for 30 seconds.',
  '使用一些边角料食材杂烩而成的烩锅。享受美味的同时还能避免浪费，可谓一举两得。': 'A hodgepodge stew made from leftover ingredient scraps. Enjoying delicious food while avoiding waste — killing two birds with one stone.',
  '使用万宝槌敲击收银台，叠加一层\u201C万宝槌之力\u201D。万宝槌充盈的魔力将在营业结束时使营业额膨胀，第一层\u201C万宝槌之力\u201D使收入提高7%，之后每层使收入提高2%。同时，充盈的万宝槌之力使伙伴【赤蛮奇】分裂出的辘轳首产生暴走，移动速度提高200%。': 'Strikes the cash register with the Miracle Mallet, stacking one layer of "Miracle Mallet Power." The mallet\'s overflowing magic inflates revenue at the end of business. The first layer increases income by 7%, and each subsequent layer increases income by 2%. Additionally, the overflowing Miracle Mallet Power causes partner [Sekibanki]\'s split rokurokubi heads to go berserk, increasing movement speed by 200%.',
  '使用了月之科技制作的极·辣品，能让食用者留下恐怖的回忆。是不是真的用辣椒做的就说不清了。': 'An extremely spicy product made with Lunar technology. It leaves terrifying memories for those who eat it. Whether it\'s actually made with chili peppers is unclear.',
  '使用妖怪之山上被秋天的神明们所庇佑的大麦所酿造的大麦烧酒。': 'Barley shochu brewed from barley blessed by the autumn gods on Youkai Mountain.',
  '使用它不用到达朋友的面前也可以通话。': 'With this, you can call friends without being in front of them.',
  '使用月之都先进技术制作的高级气泡水。迸发的口感有如火箭一般，只需要加一片柠檬就是完美的饮品。': 'Premium sparkling water made with the Lunar Capital\'s advanced technology. The explosive taste is like a rocket — just add a slice of lemon for the perfect drink.',
  '使用柠檬、佛手柑和女仆长精心挑选的红茶品种烘培出带有独特香味的红茶饮料。为了扩张红魔馆的威严，非常普通地以红魔馆命名。': 'A black tea drink made with lemon, bergamot, and carefully selected tea varieties chosen by the head maid. To enhance the Scarlet Devil Mansion\'s prestige, it was quite plainly named after the Scarlet Devil Mansion.',
  '使用真相不明的能力制造的迷之机器，据说灵感来源于外面世界的某种机器。': 'A mysterious machine created with abilities of unknown origin. Said to be inspired by some machine from the outside world.',
  '使用空间能力将在场顾客封闭起来，只要顾客还吃得下并且有能消费得起的料理，就必须消费，直到花费额度至少到达预算的70%才会解除。在解除前，顾客无法离开桌子，只能继续点单。持续60秒。': 'Uses spatial ability to seal customers in place. As long as customers can still eat and there are affordable dishes, they must keep ordering until they spend at least 70% of their budget. Before release, customers cannot leave their seats and must continue ordering. Lasts 60 seconds.',
  '使用面粉烘培出烤火鸡的形状，在表面刷上蜂蜜，肚子里塞满食材，进行充分的烘烤。出炉的假烤鸡有着香脆的外皮和多汁的内馅儿。': 'Flour baked into the shape of a roast turkey, brushed with honey, stuffed with ingredients, and thoroughly baked. The resulting faux turkey has a crispy crust and juicy filling.',
  '使用革新技术制作的分子料理。据说是来自月都的食谱。在制作过程中存在许多无法理解之处，所以经过一定程度的再创作，最终成为这样一个结合了世人眼中的\u201C雅\u201D和\u201C俗\u201D之物的地上料理，也寄托着正邪想要搅混天下的意愿。': 'Molecular cuisine made with revolutionary techniques. Said to come from a Lunar Capital recipe. Many aspects of the process were incomprehensible, so after some creative reinterpretation, it became an earthly dish combining what the world sees as "elegance" and "vulgarity" — also embodying Seija\'s desire to turn the world upside down.',
  '使用飞刀投掷上菜（包括酒水）。': 'Serves dishes (including drinks) by throwing knives.',
  '使用鲜美的八目鳗和河豚，再佐以海带炖煮而成的高级烩锅。由于煮的过程中会飘出纯白的泡沫而得名，是非常高级的家庭料理。': 'A premium hotpot made with delicious lamprey eel and pufferfish, simmered with kelp. Named for the pure white foam that rises during cooking — a very high-class home dish.',
  '侍奉着冥界之主的庭师兼侍卫、厨师…也就是说，她不仅要一个人照顾两百由旬的西行寺庭院，还要守卫西行寺家以及主人的安危，同时还要照顾大胃王主人的饮食需求！无论哪一个都是重担呢，希望她能在夜雀食堂得到一些治愈吧！': 'A gardener, bodyguard, and chef serving the master of the Netherworld... In other words, she has to tend the 200-yojana Saigyouji garden by herself, guard the Saigyouji household and her master\'s safety, AND handle the dietary needs of her big-eater master! Every single one is a heavy burden — I hope she can find some comfort at the Izakaya!',
  '侍奉着冥界之主的庭师兼侍卫、厨师。也就是说，她不仅要一个人照顾两百由旬的西行寺庭院，还要守卫西行寺家以及主人的安危，同时还要照顾大胃王主人的饮食需求！无论哪一个都是重担呢，希望她能在夜雀食堂得到一些治愈吧！': 'A gardener, bodyguard, and chef serving the master of the Netherworld. In other words, she has to tend the 200-yojana Saigyouji garden by herself, guard the Saigyouji household and her master\'s safety, AND handle the dietary needs of her big-eater master! Every single one is a heavy burden — I hope she can find some comfort at the Izakaya!',
  '依姬召唤神灵，附加一层\u201C神耀桂冠\u201D，如果本次提供的料理带有\u201C传说\u201D标签，则额外附加一层。当稀有顾客产生不为完美的评价时，消耗一层\u201C神耀桂冠\u201D引发神迹，将评价提升至完美。': 'Yorihime summons divine spirits, adding one layer of "Divine Laurel Crown." If the served dish has the "Legendary" tag, an extra layer is added. When a rare customer gives a non-perfect evaluation, one layer of "Divine Laurel Crown" is consumed to trigger a miracle, raising the evaluation to perfect.',
  '依姬小姐继承了师傅的意志，想要为月之都做出贡献，所以她才时刻保持着危机感。严格操练士兵，也是不希望她们在战争中死去。将所有一切背负下来的依姬小姐，真是坚强又温柔啊…': 'Miss Yorihime inherited her master\'s will and wants to contribute to the Lunar Capital, which is why she always maintains a sense of urgency. Training soldiers strictly is because she doesn\'t want them to die in war. Yorihime, who carries all these burdens — she\'s truly strong and gentle...',
  '依恋\u201C家的味道\u201D也太软弱了！': 'Being attached to "the taste of home" is too weak!',
  '修仙路漫漫，还是先填饱肚子吧！': 'The path of cultivation is long — let\'s fill our stomachs first!',
  '修行魔法是很费钱的。如果我能早点学会舍食魔法，就能把吃饭的钱省下来研究魔法了。': 'Practicing magic is expensive. If I could learn fasting magic sooner, I could save food money for magic research.',
  '俺已经闻到饭香啦！': 'I can already smell the food!',
  '假装忘记带钱吧…反正我是鸟脑袋嘛。': 'I\'ll just pretend I forgot to bring money... I\'m a birdbrain after all.',
  '做出这样的东西，果然应该用神枪刺穿你吧？': 'For making something like this, shouldn\'t I run you through with my divine spear?',
  '做得不错嘛。': 'Not bad.',
  '做得不错，和我的烤红薯一样好吃。': 'Not bad — as good as my roasted sweet potatoes.',
  '做得好！你值得拥有更多！': 'Well done! You deserve more!',
  '做法极其讲究的道教经典名菜。鱼肚片片，要越薄越好；太极图则要注意造型圆整、八卦形等距，最后再经过细心蒸煮，才能呈现出这道形象生动、鱼肚软糯的道家名菜。': 'A classic Taoist dish with extremely meticulous preparation. The fish maw must be sliced as thin as possible; the tai chi design must be perfectly round with evenly spaced bagua shapes. After careful steaming, this vivid and visually stunning Taoist dish with soft, tender fish maw is presented.',
  '偶尔也要吃吃桃子以外的呢。': 'I should eat something other than peaches once in a while.',
  '偶尔像这样吃一顿也不错Da☆Ze！': 'Having a meal like this once in a while isn\'t bad, da☆ze!',
  '偶尔就这样呆在魔界也挺好的。': 'Staying in Makai like this once in a while is nice.',
  '偶尔找机会来这么一顿，惬意得很啊。': 'Having a meal like this when the opportunity arises is so pleasant.',
  '偶尔换换口味也不错呢。': 'Changing the flavor once in a while isn\'t bad.',
  '偶尔是不是也回去一趟比较好呢…': 'Maybe I should go back once in a while...',
  '像这种东西，就应该和英吉利牛肉一起被冰冻起来！': 'Something like this should be frozen along with English beef!',
  '充满朋克灵魂的演出装束！是\u201C鸟兽伎乐\u201D乐队的起点，真希望有机会可以继续尽情地咆哮和歌唱啊！': 'A performance outfit full of punk spirit! It was the starting point of the "Choujuu Gigaku" band. I really wish for a chance to keep roaring and singing to my heart\'s content!',
  '光长个不长肉也不一定好啊。': 'Growing taller without gaining weight isn\'t necessarily good.',
  '兔子们倒是不讨厌污秽。': 'The rabbits don\'t mind impurity.',
  '兔子就算变成了妖怪，也还是喜欢甘甜新鲜的味道呢，真是可爱。当然啦，已经成为了妖怪，不吃肉是不可能的。吃肉的样子也很可爱。': 'Even after becoming youkai, rabbits still love sweet and fresh flavors — how cute. Of course, having become youkai, it\'s impossible not to eat meat. The way they eat meat is cute too.',
  '公主想必也会喜欢这里的氛围。': 'I\'m sure the princess would love the atmosphere here.',
  '其实人间界也有这样的店哦。': 'There are shops like this in the human world too, you know.',
  '其实我还挺同情芙兰朵露小姐的。她的力量似乎成为了一份不可能挣脱的束缚，即使包括蕾米莉亚小姐在内的所有人的本意都是好的，可惜这不是一个能被\u201C爱\u201D或者\u201C友善\u201D改变的命题。不过，就这段时间的相处而言，\u201C伙伴\u201D似乎可以是答案之一哦？至于证明，就交给时间吧。': 'Actually, I feel quite sorry for Miss Flandre. Her power seems to have become an inescapable shackle. Even though everyone, including Miss Remilia, means well, unfortunately this isn\'t a problem that can be solved with "love" or "kindness." However, based on their time together, "companionship" might be one of the answers? As for proof, let\'s leave that to time.',
  '其实是个很细心又很热心肠的家伙呢。琪露诺虽然嘴上说着不在乎啊无所谓啊什么的，但我还是能看出来她内心深处对大酱很是依赖呢。': 'She\'s actually a really attentive and warm-hearted person. Even though Cirno keeps saying she doesn\'t care, I can still tell that deep down she really depends on Dai.',
  '其实，这家伙也不是那么讨厌啦。虽然嘴巴是坏了点儿（是很坏），但说不定…是个相当天真的家伙呢。似乎在天界过得不是很舒心，如果在地上能让她好好释放压力就好了。': 'Actually, she\'s not that bad. Though her mouth is a bit harsh (okay, very harsh), she might be... quite an innocent person. She doesn\'t seem to be having a great time in heaven. I hope being on the surface can help her relieve some stress.',
  '兽道散落的奇形怪状的石头，还有点儿重。': 'Oddly-shaped stones scattered along the Beast Trail. A bit heavy.',
  '再一次激活强买强卖功能，如果不买，将发动另一张符卡\u201C恶作剧「Combo消失术」\u201D。': 'Reactivates the forced purchase function. If the customer doesn\'t buy, triggers another spell card: "Prank: Combo Disappearing Act."',
  '再怎么非常识，这顿饭也太贵了吧！': 'No matter how unconventional, this meal is way too expensive!',
  '再有名的景点也没有傲慢对待客人的资格。': 'No matter how famous a place is, it has no right to be arrogant to its customers.',
  '再美的皮相，其实都是浮云。': 'No matter how beautiful the appearance, it\'s all fleeting.',
  '军队不能出现不公。': 'There must be no injustice in the military.',
  '减少10%料理时间，增加8%续单概率。': 'Reduces cooking time by 10%, increases reorder probability by 8%.',
  '减少15%料理时间，瞬间完成带有\u201C肉\u201D标签的料理，有30%的概率返还料理食材。': 'Reduces cooking time by 15%, instantly completes dishes with the "Meat" tag, with a 30% chance to return ingredients.',
  '减少20%料理时间。烹饪结束后，此厨具会自动开始制作上一次制作的料理（包含额外添加的食材），自动制作不消耗食材且可以随时打断。': 'Reduces cooking time by 20%. After cooking finishes, this cookware automatically starts making the previous dish (including extra added ingredients). Auto-cooking doesn\'t consume ingredients and can be interrupted at any time.',
  '减少20%料理时间；如果没有添加任何额外食材，则减少70%料理时间，否则增加30%续单率。如果料理带有\u201C流行喜爱\u201D标签则二者同时触发。': 'Reduces cooking time by 20%; if no extra ingredients are added, reduces cooking time by 70%, otherwise increases reorder rate by 30%. If the dish has the "Popular Favorite" tag, both effects trigger simultaneously.',
  '减少33%料理时间。可以同时作为煮锅、油锅和蒸锅使用。': 'Reduces cooking time by 33%. Can be used simultaneously as a boiling pot, frying pan, and steamer.',
  '减少5%料理时间，增加3%续单概率。': 'Reduces cooking time by 5%, increases reorder probability by 3%.',
  '减少50%料理时间。有40%的概率制作出\u201C黑暗物质\u201D，但如果完美歌唱会使此概率降低至5%。': 'Reduces cooking time by 50%. Has a 40% chance of producing "Dark Matter," but a perfect song performance reduces this to 5%.',
  '减少相当于现实时间30秒的营业时间，到时间时会强行终止营业。': 'Reduces business time by the equivalent of 30 real-time seconds. Business will be forcibly ended when time is up.',
  '减少顾客的出现率。': 'Reduces customer appearance rate.',
  '几乎是日本茶中最高级的茶叶，需要用较低的水温来冲泡，甘醇飘香，口感独特。': 'Perhaps the highest grade of Japanese tea. Must be brewed at lower temperatures — sweet, mellow, fragrant, with a unique taste.',
  '凤蝶的妖精。性格似乎比一般的妖精要成熟，而且有种迷雾重重的感觉…应该是错觉吧？虽然看起来娴静温厚，不过骨子里还是喜欢恶作剧，希望她工作的时候不会捣蛋吧！': 'A swallowtail butterfly fairy. Her personality seems more mature than typical fairies, and there\'s an air of mystery about her... Just my imagination, right? Though she appears gentle and mild, she still loves pranks at heart. I hope she won\'t cause trouble during work!',
  '凭什么是你来定价？我说了算！': 'Why do you get to set the price? I\'ll decide!',
  '分布在雾之湖和玄武泽的淡水虾，较为常见。': 'Freshwater shrimp found in Misty Lake and Genbu Marsh. Fairly common.',
  '刚刚来的路上差点被食人牵牛花吞了，好险好险！': 'I almost got swallowed by a man-eating morning glory on the way here — that was close!',
  '刚欲同盟的成员多半都是些各行其是的家伙。': 'Most members of the Alliance of Desires just do whatever they want.',
  '创造了幻想乡的贤者之一，据说是幻想乡最古老的妖怪，虽然神出鬼没而且性格有点儿不近人情，但其实一直以来暗中维护着幻想乡的安全和稳定…虽然没有得到多数人的理解，但恐怕也没有像她一样真挚地对待幻想乡、爱着幻想乡的人了。': 'One of the sages who created Gensokyo, said to be its oldest youkai. Though elusive and somewhat unapproachable, she has actually been secretly maintaining Gensokyo\'s safety and stability all along... Though not understood by most, there is probably no one who treats Gensokyo as sincerely or loves it as deeply as she does.',
  '初见就像是云山雾罩的神秘星球，打开一看\u201C星球\u201D里竟然摆了个生鸡蛋？仔细看蛋液其实是银耳汤，蛋黄则是南瓜泥。吃起来口感清爽，还有香浓的南瓜味。': 'At first glance it looks like a mysterious planet shrouded in mist. Open it up and there\'s a raw egg inside the "planet"? Look closely — the egg white is actually snow fungus soup, and the yolk is pumpkin puree. Light and refreshing with a rich pumpkin flavor.',
  '利用了散碎的棉花糖模拟了绵羊般毛茸茸外表的西式汤。毛茸茸的表层下面是猩红色的肉汤，入口是极具侵略性和力量感的野味。是外表很可爱然而实际很暴力的料理呢。': 'A Western soup using scattered marshmallows to simulate a fluffy sheep-like exterior. Beneath the fluffy surface is a scarlet meat broth with an aggressive, powerful wild game flavor. A dish that looks cute but is actually quite fierce.',
  '利用海藻酸钠溶液和氯化钙溶液反应形成一层海藻酸钠凝胶薄膜，将调好的莫吉托酒包裹在内，做成一个球状的透明凝胶。咬一口就爆浆，达到视觉和味觉的双重惊喜，看起来非常诱人。': 'Using a reaction between sodium alginate and calcium chloride solutions to form a thin gel film, wrapping perfectly mixed mojito inside to create a spherical transparent gel. One bite and it bursts — achieving a double surprise of sight and taste. Looks incredibly tempting.',
  '利用火焰魔法和束缚魔法固定住肉类然后烧烤的料理，视觉特效上值得满分。不过出于某人的奇妙心理，这道料理使用了超位级魔法，导致每次烹饪都像烟花表演。': 'A dish that uses fire magic and binding magic to hold meat in place while grilling — the visual effects are worth full marks. However, due to a certain someone\'s peculiar mindset, this dish uses super-tier magic, making every cooking session look like a fireworks show.',
  '别一直盯着我呀，酒都不好喝了。': 'Stop staring at me — the drinks don\'t taste as good anymore.',
  '别以为给我做点好吃的就可以放宽贷款哦。': 'Don\'t think that making some good food for me will loosen up the loan terms.',
  '别以为老娘登场少就好欺负啊！': 'Don\'t think you can bully me just because I don\'t appear much!',
  '别以为这样就能把我打发掉！': 'Don\'t think you can get rid of me like this!',
  '别这么看着我！我来到店里并不会影响店铺的卫生啦！': 'Don\'t look at me like that! Me being in the shop won\'t affect its hygiene!',
  '制作含有\u201C清淡\u201D或\u201C素\u201D标签的料理，最终只能做出黑暗物质，持续120秒。': 'Creating dishes with the "Light" or "Vegetarian" tag will only produce Dark Matter for 120 seconds.',
  '制作家常奶油浓汤，制作方法简单，无论是蘸面包还是当作炖菜来吃都是非常不错的料理。': 'A simple home-style cream soup. Whether dipping bread in it or eating it as a stew, it makes for an excellent dish.',
  '制作意外的简单，但获取食材却非常困难。据说是现世流行的超高级料理，是每个人的梦想。': 'Surprisingly simple to make, but extremely difficult to obtain the ingredients. Said to be a trendy ultra-premium dish in the modern world — everyone\'s dream.',
  '制作料理台的料理时能瞬间完成，持续60秒。': 'Instantly completes dishes made on the prep counter for 60 seconds.',
  '制作料理时有15%的概率不会减少食材。': '15% chance of not consuming ingredients when cooking.',
  '制作生冷原味食材的必备厨具！无论是处理生肉、生鱼或是处理凉菜沙拉，都是非常方便的厨具。原生的，就是最美味的！': 'Essential cookware for preparing raw, cold, and natural ingredients! Whether processing raw meat, raw fish, or preparing cold salads — it\'s an incredibly handy tool. Natural means the most delicious!',
  '制造落叶也是一件很累的工作呢。': 'Making falling leaves is tiring work too.',
  '力量源源不绝！这就是美食的威力吗？': 'Endless power! Is this the might of good food?',
  '力量满满！此刻的我无论什么都能将其颠倒！': 'Full of power! Right now I can flip anything upside down!',
  '加入了\u201C可疑的\u201D技术，让吃了料理的客人非常开心！虽然不明白，但生意太火爆了！': '"Suspicious" techniques have been added, making customers who eat the food very happy! I don\'t understand, but business is booming!',
  '加入了极为刺激的食材和辅料，对味觉的刺激满点的超级烤串，阿空亲自为它起了一个中二度满满的名字，结果在保持野性的妖怪中莫名的有人气。': 'Super grilled skewers with extremely stimulating ingredients and seasonings, maxing out the taste buds. Okuu personally gave it a super chuunibyou name, and it somehow became popular among the more wild youkai.',
  '努力活着才能吃到这样的美味呢。': 'You can only eat something this delicious by putting in the effort to stay alive.',
  '劳逸结合才是长久之道哟。': 'Balancing work and rest is the key to longevity.',
  '勉强能在路上作充饥之物吧。': 'Barely passable as something to stave off hunger on the road.',
  '勤加练习的话一定可以做得更好。': 'With more practice, you can definitely do better.',
  '勤劳、善良热情的小女孩，开着一家\u201C蓬松松爱莲\u201D魔法店，还养了一只叫做苏格拉底的、个性有点儿酷的猫。': 'A hardworking, kind, and enthusiastic little girl who runs the "Fluffy Ellen" magic shop and keeps a cat named Socrates with a somewhat cool personality.',
  '包括排队顾客在内的所有顾客，有30%的概率增加一次额外续单，每位顾客的概率独立计算。通过此种方式增加的额外续单将无视预算上限。': 'All customers, including those in queue, have a 30% chance to gain an extra reorder. Each customer\'s probability is calculated independently. Extra reorders gained this way ignore budget limits.',
  '包括排队顾客在内的所有顾客，用餐时间增加一倍，但此技能效果优先级低于立刻完食类Buff。': 'All customers\' (including those in queue) dining time is doubled, but this skill effect has lower priority than instant-finish buffs.',
  '区别待遇真没意思。': 'Discrimination is so boring.',
  '区区住在林子里的猴子，是不会明白河里的乐趣。': 'A mere monkey living in the forest wouldn\'t understand the joys of the river.',
  '区区住在河里的两栖类，是不会明白山上的乐趣。': 'A mere amphibian living in the river wouldn\'t understand the joys of the mountain.',
  '区区地上人，做得还挺像样的。': 'Not bad for a mere surface-dweller.',
  '区区门卫吃不起你家的菜！': 'A mere gatekeeper can\'t afford your food!',
  '区区麻雀，连本魔神都敢宰，是想体验一下神罚吗？': 'A mere sparrow dares to rip off this great demon god — do you want to experience divine punishment?',
  '升级后的料理台！': 'Upgraded prep counter!',
  '升级后的油锅！': 'Upgraded frying pan!',
  '升级后的烧烤架！': 'Upgraded grill!',
  '升级后的煮锅！': 'Upgraded boiling pot!',
  '升级后的蒸锅！': 'Upgraded steamer!',
  '单纯的事件是不能称为历史的，只有将其记载下来，方为历史。': 'Simple events cannot be called history — only by recording them do they become history.',
  '博丽灵梦收拾仓库时找到的有点儿褪色的旧巫女服。穿上后感觉自己多少能体会到巫女的身份之重，但绝不可以自称巫女。': 'A slightly faded old shrine maiden outfit that Reimu Hakurei found while cleaning the storeroom. Wearing it makes you somewhat feel the weight of a shrine maiden\'s duty, but you must never call yourself a shrine maiden.',
  '博丽神社在幻想乡有着特殊的、绝对的地位，无论是守矢神社还是早苗小姐，想超越博丽之名都很艰难。不过，在早苗小姐的兢兢业业下，现在大家都记住了守矢巫女之名，真是太好了！': 'The Hakurei Shrine holds a special, absolute status in Gensokyo. Neither the Moriya Shrine nor Miss Sanae can easily surpass the Hakurei name. However, thanks to Miss Sanae\'s diligent work, everyone now remembers the Moriya shrine maiden\'s name — how wonderful!',
  '博丽神社散落的破损的符咒，拼拼凑凑似乎也能得到点儿信息。': 'Damaged charms scattered around the Hakurei Shrine. Piecing them together seems to yield some information.',
  '即使没有入侵者，也万不可掉以轻心。': 'Even without intruders, one must never let their guard down.',
  '即便博览群书，也很难有这等厨技造诣啊。': 'Even reading extensively, it\'s hard to achieve this level of culinary skill.',
  '即便是幻想乡也无法接受地狱来客吗？': 'Even Gensokyo can\'t accept visitors from hell?',
  '即便是轮回多世，我也从未吃过如此美味的料理！': 'Even through multiple cycles of reincarnation, I\'ve never eaten anything this delicious!',
  '压榨劳动人员的钱包却只给吃这种东西吗？！': 'Squeezing workers\' wallets and this is all you serve?!',
  '厚切的鳗鱼块抹上特调酱汁，再覆盖一层软嫩的生蛋，在食用前将其搅拌得金灿灿的样子，吃下去超级满足！': 'Thick-cut eel pieces coated in a special sauce, covered with a soft raw egg. Mix it until it turns golden before eating — incredibly satisfying!',
  '原本以为她是个亲切开朗的妖怪，结果一转身就看到她在背地里说我坏话…以嫉妒为食的妖怪，不煽动别人的嫉妒心就会活不下去吗？感觉很可怜呐。不过她似乎不这么觉得。性格也阴晴不定，真是难以理解。': 'I thought she was a friendly and cheerful youkai, but the moment I turned around, she was badmouthing me... A youkai that feeds on jealousy — can she not survive without stirring up others\' envy? Seems pitiful. But she doesn\'t seem to think so. With her unpredictable personality, she\'s truly hard to understand.',
  '原本以为这样的大人物会很难交流，结果她却意外地好说话，有时甚至还跟小孩子一样…啊，这种事情果然还是保密吧！听说那个金发女仆是她亲手制作的，真厉害，我开始好奇她的一切了。': 'I thought such an important person would be hard to talk to, but she was unexpectedly easy to get along with — sometimes even acting like a child... Ah, I\'d better keep that a secret! I heard she made that blonde maid herself. Amazing — I\'m getting curious about everything about her.',
  '原本是内测人员的特殊食谱，三年来一直令全收集强迫症玩家坐卧不宁，这次彻底开放了。': 'Originally a special recipe exclusive to beta testers. For three years it kept completionist players restless, but now it\'s fully released.',
  '原本是安置在魔法之森的地藏石像，因为森林的魔力而得到了生命——森林里居然蕴藏着能够将存在本身进行变化的魔力，难怪有那么多魔法使住在这，这对修行来说也太便利了！': 'Originally a Jizo statue placed in the Forest of Magic, brought to life by the forest\'s magic — the forest actually contains magic that can transform the very nature of existence! No wonder so many magicians live here — it\'s way too convenient for training!',
  '原来丰姬小姐心里也有想要完成的事呢。她是从什么时候开始产生想要隐退的想法呢？或许从一开始，她就只是被迫继承月之使者首领的工作吧。至今没有隐退，一来是没有合适的继任者，二来…恐怕还是为了依姬小姐吧？': 'So Miss Toyohime has things she wants to accomplish too. When did she start wanting to retire? Perhaps from the very beginning, she was only forced to inherit the role of Lunar emissary leader. She hasn\'t retired partly because there\'s no suitable successor, and partly... probably for Miss Yorihime\'s sake?',
  '原来勇仪小姐曾经是山中四天王之一。传闻说她有异常程度的怪力，腕力即便在鬼之中也几乎无可匹敌。没想到我也能结识到这么厉害的妖怪…果然还是有点儿紧张啊。': 'So Miss Yuugi was once one of the Four Devas of the Mountain. Rumor has it her monstrous strength is unmatched even among oni. Who knew I\'d get to know such a powerful youkai... I\'m still a bit nervous, honestly.',
  '原来秋穰子小姐那么喜欢烤红薯的吗？毕竟是丰收的神明呢，说起来，她的身上好像一直有着一种香喷喷的烤红薯味，应该是用了某种特制香水吧？': 'So Miss Minoriko loves roasted sweet potatoes that much? Being the goddess of harvest and all. Come to think of it, she always seems to have a fragrant roasted sweet potato smell — she must use some special perfume, right?',
  '原来美铃小姐的家乡在海的另一边。但是幻想乡是没有海的，美铃小姐是不是已经回不去了？她的家乡有很多耳熟能详的名菜，我努力学习做给她吃，或许可以缓解一些她的思乡之情。': 'So Miss Meiling\'s homeland is across the sea. But there is no sea in Gensokyo — does that mean Miss Meiling can\'t go back? Her homeland has many well-known dishes. If I study hard and make them for her, maybe it can ease some of her homesickness.',
  '原来舞是刀子嘴豆腐心，虽然满口的不在乎雪，但是实际上非常关心她呢！虽然我不是很理解为什么舞她不愿意直接把内心的想法全部表达出来，或许那样的话就不会让雪有那么多的误会了…不过看着她俩开心地一起玩耍一起摆摊，我应该不需要担心那么多了吧！': 'Turns out Mai has a sharp tongue but a soft heart — though she keeps saying she doesn\'t care about Yuki, she actually cares deeply! I don\'t quite understand why Mai won\'t just express her feelings directly — maybe that would prevent so many misunderstandings for Yuki... But watching them happily playing together and running their stall, I probably don\'t need to worry so much!',
  '原来还能用这种方式来激怒他人，我似乎想到了新的捉弄雪的点子呢~。': 'So you can provoke people this way too — I think I just got a new idea for teasing Yuki~.',
  '原来铃仙曾经是一只捣药兔，因为厌烦无休止的捣药逃到幻想乡而发生了许多事，所以才成为一名月之使者。难怪她会对地上表现出眷恋。不过她似乎也不喜欢月之使者的工作，感觉她从内到外都过得好辛苦啊…': 'So Reisen was once a moon rabbit pounding medicine, who fled to Gensokyo because she was tired of the endless work — many things happened, and that\'s how she became a Lunar emissary. No wonder she shows attachment to the surface. But she doesn\'t seem to like being a Lunar emissary either — she seems to have a hard time through and through...',
  '原来露易兹小姐不仅仅分享旅行过程，也经常分享自己的创意设计。她不仅见多识广，有非常多有趣的想法和创意，还很了解时尚，很会夸人，很会做甜品…真希望自己也能成为像露易兹小姐这样优秀的人呀。': 'Turns out Miss Louise doesn\'t just share her travel experiences — she often shares her creative designs too. She\'s not only well-traveled with many interesting ideas and creative concepts, but also knows fashion, is great at complimenting people, and excels at making desserts... I really wish I could become as amazing as Miss Louise.',
  '原来食物还能这么美味吗？': 'Can food really be this delicious?',
  '原来高贵的公主也会和普通人一样烦恼工作的事情。辉夜小姐和我也没什么不同嘛。作为工作了数载的前辈，我得好好为迷惘的后辈打气呢！': 'So even a noble princess worries about work matters just like ordinary people. Miss Kaguya isn\'t so different from me after all. As a senior who\'s worked for years, I should cheer up my confused junior!',
  '原来魅魔小姐就是魔理沙小姐的师傅！我早就应该想到的，她们俩真的有很多共同点！无论是追求知识的执著和专注这点，还是道德感方面…以及，从来不会展现自己软弱和脆弱的一面…表面看起来完全不同的，这两个孤独又坚定的人，过去会是什么样子的呢？': 'So Miss Mima is Miss Marisa\'s master! I should have realized sooner — they really have so much in common! Whether it\'s their dedication and focus in pursuing knowledge, or their sense of morality... and the way they never show their weak or vulnerable side... These two lonely yet determined people who look so different on the surface — what were they like in the past?',
  '又硬又硌牙，想必比你的肝还要难啃！': 'Hard and gritty — probably tougher to chew than your liver!',
  '又称赤豆，是适应能力较强的草本植物，食用能够起到增强自身免疫力和抗病能力的效果。古代人觉得中风得病都是疫鬼作祟，所以有\u201C赤豆打鬼\u201D的传说。': 'Also known as red beans, a highly adaptable herbaceous plant. Consuming them can enhance immunity and disease resistance. Ancient people believed illnesses were caused by plague demons, hence the legend of "red beans to drive away ghosts."',
};

// Apply translations
let content = fs.readFileSync('app/data/i18n/en.ts', 'utf8');
let count = 0;
for (const [key, value] of Object.entries(translations)) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`('${escaped}':\\s*)'',`, 'g');
  const newContent = content.replace(regex, `$1'${value.replace(/'/g, "\\'")}',`);
  if (newContent !== content) {
    count++;
    content = newContent;
  }
}
fs.writeFileSync('app/data/i18n/en.ts', content);
console.log(`Updated ${count} translations in app/data/i18n/en.ts`);
console.log(`Expected: ${Object.keys(translations).length}`);
