import fs from 'fs';

// English translations for description keys batch 4 (keys 600-799)
const translations: Record<string, string> = {
  '地上的生活成本比海上高多了。': 'The cost of living on land is much higher than at sea.',
  '地上的食物一直是不错的。': 'The food on the surface has always been pretty good.',
  '地上的食物就这种水平吗？': 'Is the food on the surface only at this level?',
  '地上的食物果然有意思！': 'The food on the surface really is interesting!',
  '地上稀奇古怪的东西真不少，虽然不入流，倒也挺有趣的。': 'There are plenty of strange things on the surface. Not exactly refined, but quite interesting.',
  '地上虽然比不上天界的富饶，不过勉强还是能呆一阵子的。': 'The surface may not match Heaven\'s prosperity, but I can manage to stay for a while.',
  '地上都是这般坑蒙拐骗吗？！': 'Is everyone on the surface this deceitful?!',
  '地灵殿之主的妹妹，封闭了第三只眼的觉！由于封闭了内心所以存在感也变得很低，神秘的身影让她在地底收获了许多追崇者。总是挂着灿烂的笑容，但谁也无法知道她真正的内心是怎么想的。就连她自己也不知道。': 'The younger sister of the Palace of Earth Spirits\' master — a satori who closed her third eye! By closing her heart, her presence became very faint, and her mysterious figure earned her many followers underground. She always wears a bright smile, but no one can know what she truly thinks. Not even she herself knows.',
  '地灵殿的限定纪念甜品！以地灵殿的觉妖怪姐妹为原型设计的可爱甜筒，在地底妖怪中有很大的人气。': 'A limited commemorative dessert from the Palace of Earth Spirits! Cute ice cream cones designed after the satori sisters — very popular among underground youkai.',
  '地狱的改革，势必会引发一场激烈的斗争…': 'Reforming Hell will inevitably spark a fierce struggle...',
  '场上所有就座的顾客的剩余预算回复到上限，制作料理不消耗食材且瞬间完成，顾客必定给出最高评价，持续20秒。': 'All seated customers\' remaining budgets are restored to maximum, cooking consumes no ingredients and completes instantly, and customers always give the highest rating. Lasts 20 seconds.',
  '增加相当于现实时间30秒的营业时间。': 'Adds 30 seconds of real-time business hours.',
  '夏天的消暑下酒菜，简单爽口。': 'A refreshing summer drinking snack — simple and crisp.',
  '外界似乎很流行使用〇〇恋人作为地区伴手礼，永远亭也不甘落后潮流，推出了自己的版本！': 'It seems popular in the outside world to use "XX Lover" as regional souvenirs. Eientei doesn\'t want to fall behind the trend and released their own version!',
  '外表是鲤鱼起跳的造型，剖开后尽是梦幻的宝藏，是猫科动物无法抵抗的究极美食。': 'Shaped like a leaping carp on the outside, filled with dreamy treasures inside — the ultimate delicacy that no feline can resist.',
  '外表看起来像是拉长了的团子，切开后中间裹着各式各样的图案，大大增加了团子的新鲜感。据说瘦马团子象征佛舍利，那不就是佛祖的骨灰吗？': 'Looks like elongated dango on the outside. When cut open, it reveals various patterns inside, adding great novelty. They say these dango symbolize Buddha\'s relics — isn\'t that basically Buddha\'s ashes?',
  '外表看起来是气质优雅的公主殿下，实际行事却有些无赖…有点儿理解为什么她能成为那只黑兔子的主人了（黑形容的是心哦）…': 'She looks like an elegant princess on the outside, but actually acts a bit roguish... I kind of understand why she became the master of that black rabbit (black as in her heart)...',
  '外面的世界看起来好脆弱…': 'The outside world looks so fragile...',
  '多谢招待。': 'Thanks for having me.',
  '多谢款待。': 'Thanks for the treat.',
  '多谢老板娘招待。': 'Thanks for the hospitality, boss lady.',
  '多谢老板娘款待！': 'Thanks for the treat, boss lady!',
  '夜晚的萤火虫不是很美好吗？驻足多看一会吧。': 'Aren\'t the fireflies at night beautiful? Stop and watch them a little longer.',
  '大大提升了酸度的可怕布丁，改良了提神的效果，只要吃一口，就能让困倦的身体打起精神。但因为其用料过于凶猛，很不利于口腔健康…': 'A terrifying pudding with greatly increased acidity — improved for a refreshing effect. Just one bite can wake up a drowsy body. But the ingredients are so aggressive that it\'s terrible for dental health...',
  '大姐，你太伤咱的心了。': 'Sis, you really hurt my feelings.',
  '大家的口袋就那么富裕吗？': 'Is everyone really that loaded?',
  '大小姐什么时候才把那本漫画的下册借回来呢？': 'When is the young mistress going to return the second volume of that manga?',
  '大晚上的感觉也好热呀…': 'Even at night it feels so hot...',
  '大量白狼天狗顾客上门，持续120秒。': 'A large number of white wolf tengu customers arrive, lasting 120 seconds.',
  '大错特错！她从来都没有"忍受"过那些谣言，因为她根本就不在乎。于是连澄清都变得多此一举。幽香小姐最为强大之处，正是她的心。我想，并不是强大的妖力让她睥睨众人，真正让她立于不败之地的，是她纯粹又干净的自我。': 'Completely wrong! She never "endured" those rumors, because she simply didn\'t care. So even clarifying became unnecessary. Yuuka\'s greatest strength is her heart. I believe it\'s not her powerful youkai abilities that let her look down on everyone — what truly makes her invincible is her pure and clean sense of self.',
  '天狗的社会有严密的等级制度，山中侍卫这一职务基本都是由白狼天狗担当。大概是职责所在，他们多数的性格比较严肃，但有时候喝多了也会口无遮拦。': 'Tengu society has a strict hierarchy, and mountain guard duty is mostly held by white wolf tengu. Perhaps due to their responsibilities, most have serious personalities, but sometimes after too many drinks they speak without restraint.',
  '天界那群老顽固，一点儿都不懂变通！': 'Those stubborn old fools in Heaven don\'t know the meaning of flexibility!',
  '天要下雨，菜要下饭。': 'Rain must fall, dishes must go with rice.',
  '太太太太太好吃了吧，必须推荐给魔界的大家！': 'SO SO SO SO GOOD — I have to recommend this to everyone in Makai!',
  '太好吃了！我要介绍给我们世界的每一个人！': 'So delicious! I want to introduce this to everyone in our world!',
  '太好吃了！麻雀难道是料理的天才吗？！': 'So delicious! Could the sparrow be a cooking genius?!',
  '太晚睡对皮肤不好…': 'Staying up late is bad for the skin...',
  '太美味了！这是沉淀了历史的技术才能做出来的佳肴！': 'So delicious! This is a dish that can only be made with skills refined through history!',
  '太计较钱财会失了风度哟。': 'Being too concerned with money is unbecoming.',
  '太过分！居然拿这种东西来敷衍我！': 'How dare you! Trying to fob me off with this!',
  '失望的宴会…': 'A disappointing feast...',
  '失算了，居然已经超额了，还是记在雪的账上吧！': 'Miscalculated — I already went over budget. Just put it on Yuki\'s tab!',
  '奢侈地选用了一系列高级食材炖煮成烩锅。通过火候的精妙控制，将食材之间的特点全部提炼了出来，肉质鲜嫩多汁、香滑入味，令人其味无穷。': 'A luxurious stew made with a series of premium ingredients. Through exquisite heat control, all the characteristics of the ingredients are perfectly drawn out — the meat is tender, juicy, fragrant, and flavorful beyond description.',
  '奶油焗的螃蟹在没开盖之前就已经香气四溢，然而这香气只是前戏。撕开蟹钳，弹出白嫩饱满的肉质，此时再细细地吸入汤汁，螃蟹固有的鲜味才彻底的融合和释放。': 'The cream-baked crab releases its aroma even before the lid is opened, but that fragrance is just a prelude. Crack open the claws to reveal plump, tender meat, then slowly sip the broth — only then does the crab\'s inherent umami fully merge and release.',
  '她就像是被忽视、通过恶作剧来吸引大家注意力的别扭的孩子。内心希望融入寺中，却笨挫地不知道该怎么表达…明明活了这么久，还是不谙世故呢。': 'She\'s like an awkward child who, being ignored, tries to attract attention through pranks. Deep down she wants to fit in at the temple, but clumsily doesn\'t know how to express it... Despite living so long, she still doesn\'t understand social graces.',
  '她应该也常来这里吧？': 'She probably comes here often too, right?',
  '她比我想象中的要心思细腻，过去似乎经历了很多难以想象的苦难。即便如此，她仍然心存良善，一直暗中帮助别人。这样的她，一定会获得幸福的！': 'She\'s more delicate in thought than I imagined, and seems to have experienced unimaginable hardships in the past. Even so, she remains kind-hearted, always helping others quietly. Someone like her is sure to find happiness!',
  '她的妹妹是身为丰收之神的秋穰子，但貌似她并不怎么喜欢别人提及她的妹妹，似乎是由于她的妹妹比她更加受欢迎的缘故吧。不过她和她的妹妹一样，倒是挺喜欢甜食的。大概是因为红叶打扫起来很麻烦，信仰她的人也越来越少了，她貌似经常会为此苦恼。': 'Her younger sister is Aki Minoriko, a goddess of harvest, but she doesn\'t seem to like people mentioning her sister — probably because her sister is more popular. Like her sister though, she has a sweet tooth. Perhaps because autumn leaves are troublesome to clean and her followers keep dwindling, she often seems troubled by this.',
  '好、好吃！HIGH起来了！': 'D-delicious! I\'m getting hyped!',
  '好、好吃！就连妖怪做饭都比我好吃…': 'D-delicious! Even a youkai\'s cooking is better than mine...',
  '好、好好粗！不是！好好吃！！': 'S-so th-thick! No! So delicious!!',
  '好不容易成为了拥有自我的生命体，结果还是个家里蹲，这不是很可惜吗？！我一定要想办法让这家伙提起干劲！': 'After finally becoming a living being with a sense of self, ending up as a shut-in is such a waste, isn\'t it?! I have to find a way to motivate this one!',
  '好不容易找到机会来一次来着…': 'I finally found a chance to come here...',
  '好不容易找到的容身之处，我绝不离开。': 'I finally found a place to stay — I\'m never leaving.',
  '好不容易把今日要诵读的万遍真言给念完了。': 'I finally finished reciting the ten thousand mantras for today.',
  '好不容易挤出一些时间，也该犒劳一下自己。': 'I finally squeezed out some time — I should treat myself.',
  '好久没有人从"兔子洞"掉下来了。': 'It\'s been a while since anyone fell down the "rabbit hole."',
  '好可怕…我还是回家吃烤红薯吧…': 'So scary... I\'ll just go home and eat roasted sweet potatoes...',
  '好吃到吓我一跳！': 'So good it startled me!',
  '好吃到我想在店里住下来了哟！': 'So good I want to move into the shop!',
  '好吃好吃！不枉我穿越通道来这边一次呀！': 'Delicious! It was worth crossing through the passage to come here!',
  '好吃得舌头都要融化了！': 'So good my tongue is melting!',
  '好吃得苏格拉底都变得亮晶晶了！': 'So delicious that even Socrates is sparkling!',
  '好吃耶，老板娘你的手艺真好！': 'Yummy! Boss lady, your skills are amazing!',
  '好吃！不枉我特意攒钱来吃！': 'Delicious! It was worth saving up money to eat here!',
  '好吃！以后就让你跟着本小姐混吧！': 'Delicious! From now on, you can roll with me!',
  '好吃！还想吃更多更多。': 'Delicious! I want to eat more and more.',
  '好呀你，连本姑娘的钱都敢骗？！': 'How dare you try to swindle even my money?!',
  '好想去人间界呀。': 'I really want to visit the human world.',
  '好想念XX大人。': 'I really miss Lord XX.',
  '好满足！五蕴皆空不如五脏俱饱。': 'So satisfied! Emptying the five aggregates is nothing compared to filling the five organs.',
  '好马配好鞍，好酒配好菜！': 'A good horse deserves a good saddle, and good wine deserves good food!',
  '如今，幻想乡缘起到底是为了什么而继续写下去呢…': 'Nowadays, what reason is there to keep writing the Gensokyo Chronicle...',
  '如果不使用火鼠裘来承装也许就会烧起来的烈酒，几乎无人能承受其辣度的超级辣口烧酒。': 'A spirit so strong it might catch fire without a fire-rat fur container — an ultra-spicy liquor that almost no one can handle.',
  '如果不提她那套落伍的作风，其实她也蛮有仙人那种风格，尤其对风水什么的似乎很有研究。我是搞不懂啦…要不下次装修的时候请她帮忙看看好了。': 'If you ignore her outdated ways, she actually has that hermit style — especially her knowledge of feng shui. I don\'t understand it myself... Maybe I should ask her to take a look next time I renovate.',
  '如果你是我的学生，我就上头槌了！': 'If you were my student, I\'d headbutt you!',
  '如果冥界也有一家食堂那我就轻松多了。': 'If there were a restaurant in the Netherworld, my life would be much easier.',
  '如果制作的料理不带有"肉"标签，则减少50%料理时间，否则增加30%料理时间。此厨具制作出的料理被顾客食用并给出评价后，接下来给任何顾客由此厨具制作的相同料理必然会得到相同评价。': 'If the dish doesn\'t have the "meat" tag, reduces cooking time by 50%; otherwise increases by 30%. After a customer eats and rates a dish made with this cookware, any subsequent customer served the same dish from this cookware will always give the same rating.',
  '如果加入某些高级的食材，料理的氛围也会变得高级！给我好好记住啊！': 'If you add certain premium ingredients, the dish\'s ambiance becomes premium too! Remember that well!',
  '如果只有这样的话…': 'If this is all there is...',
  '如果场上不存在"幽玄封魔阵"则生成法阵，如果存在则为法阵填充2点能量。{{br}}"幽玄封魔阵"：除魅魔以外的稀有顾客释放任意符卡时填充1点能量。能量达到7点时，消耗全部能量引发"梦符「时空一粟」"。': 'If "Mystic Sealing Formation" doesn\'t exist on the field, creates one; if it exists, charges it with 2 energy.{{br}}"Mystic Sealing Formation": Gains 1 energy when any rare customer (other than the succubus) releases a spell card. At 7 energy, consumes all energy to trigger "Dream Sign: A Grain in Spacetime."',
  '如果失去标志性的装束，我们还会被称为八尺大人吗？': 'If we lose our iconic attire, will we still be called Hachishaku-sama?',
  '如果能在秋天吃到这道菜，一切的悲伤都将不复存在吧。': 'If you could eat this dish in autumn, all sadness would cease to exist.',
  '如果说河童都是些唯利是图的商人，作为小头目的她更是其中的佼佼者！虽然说商人趋利也没什么好指责的，但是再多一点儿人情味不是也挺好吗？': 'If kappa are all profit-driven merchants, she as their boss is the best of them! While there\'s nothing wrong with merchants seeking profit, wouldn\'t a bit more warmth be nice?',
  '如果顾客对料理的评价至少为普通，则心情额外增加15。': 'If the customer rates the dish at least Normal, mood increases by an additional 15.',
  '如果顾客对料理的评价至少为普通，则有15%的概率提高评价至完美。': 'If the customer rates the dish at least Normal, there\'s a 15% chance to upgrade the rating to Perfect.',
  '如此相待，最随和的花儿也不会愿盛开。': 'Treated like this, even the most easygoing flower would refuse to bloom.',
  '如此美味，竟如同神话一般的梦幻。': 'So delicious, it\'s as dreamlike as a myth.',
  '妖兽果然还是要吃肉啊！': 'Beast youkai really do need meat after all!',
  '妖怪狸的首领，有着相应的威严和领导风范，擅长变幻术。不过再如何擅长变幻的妖兽，想要完全藏起尾巴和耳朵都是不可能的。另外尾巴的大小其实是妖力的计量表，或许她从最初开始就没有藏起自己尾巴的打算。': 'The leader of the youkai tanuki, with the appropriate dignity and leadership — skilled in transformation arts. But no matter how skilled a beast youkai is at transformation, completely hiding ears and tail is impossible. Also, tail size is actually a gauge of youkai power, so perhaps she never intended to hide her tail from the start.',
  '妖怪猫特征是两尾分岔成两股，据说妖力越大，分岔越明显。明明长得那么可爱，性格却很凶！幻想乡就连野猫的嘴巴也很刁呢。': 'Youkai cats are characterized by tails that split into two — the stronger the youkai power, the more distinct the split. Despite being so cute, their personality is fierce! Even the stray cats in Gensokyo are picky eaters.',
  '妖怪的改革也是很艰难的。': 'Reform among youkai is also quite difficult.',
  '妖精们每天的生活想必会很有趣吧？如果从责任和义务这些角度来想，大酱她相比起其她妖精在这方面考虑得可能更多一些，但恰好是不至于负累又不会变成笨蛋的平衡点呢。真是让鸟脑袋都羡慕的生活态度啊。': 'The daily lives of fairies must be quite fun, right? From the perspective of duties and obligations, Daiyousei probably thinks about these things more than other fairies, but just enough to stay balanced — not overburdened yet not becoming foolish. What an enviable attitude, even for a birdbrain like me.',
  '妖精们采集露水，和花蜜混合的甘甜饮料。由于妖精们会忘记自己的劳动产品，所以常被动物或者人类采走。传说可以治愈百病甚至起死回生，但似乎是谣言。': 'A sweet drink made by fairies, mixing collected dew with nectar. Since fairies forget about their products, animals and humans often take them. Legend says it can cure all ailments and even revive the dead, but that seems to be just a rumor.',
  '妖精其实不用吃东西，它们看见人吃美味的东西就模仿着吃。喜欢热闹，也喜欢恶作剧，千万要注意别着了它们的道！': 'Fairies don\'t actually need to eat — they imitate eating when they see people enjoy delicious food. They love lively atmospheres and pranks, so be careful not to fall for their tricks!',
  '妖精和妖怪的区别？简单地说，我们更加可爱一点！': 'The difference between fairies and youkai? Simply put, we\'re cuter!',
  '妖精越多，大自然就会越有生机。魔法森林的各种物资都非常丰富，这是因为森林中寄宿许多妖精。据说每棵树都有妖精寄宿其中。妖精多恶作剧也多，要小心才行呢。': 'The more fairies, the more vibrant nature becomes. The Forest of Magic is rich in resources because many fairies dwell there. They say every tree hosts a fairy. More fairies means more pranks, so be careful.',
  '妹红小姐真是帅气啊，虽然是人类，却强到没边，性格也很豪迈。据说爱吃辣的人性格都很爽快，妹红小姐可是无辣不欢呢。': 'Miss Mokou is really cool — though human, she\'s incredibly strong with a bold personality. They say people who love spicy food have straightforward personalities, and Miss Mokou needs her spice.',
  '姐姐她现在在干什么呢？': 'I wonder what my sister is doing right now.',
  '姐姐说肚子吃得鼓鼓的就表示吃饱了！': 'Big sis says when your tummy is round and full, that means you\'re full!',
  '姑获鸟、鬼车鸟、九头鸟，这是三种妖怪啦。': 'Ubume, ghost carriage bird, nine-headed bird — those are three different youkai.',
  '姑获鸟，姑获鸟抱走孩子；夏获鸟，夏获鸟收养孩子。': 'The ubume takes children away; the summer bird adopts children.',
  '孤独才是享受美食的最好状态。': 'Solitude is the best state for enjoying fine food.',
  '孤独是毒也是药。': 'Solitude is both poison and medicine.',
  '守卫的工资果然是太低了，连顿饭也差点吃不起…': 'Guard pay really is too low — I can barely afford a meal...',
  '守护神社的狛犬。性格温和，脸上总是洋溢着笑容，看到她就感觉自己的疲劳都被治愈了。似乎还很擅长算账。这么优秀的孩子却没有在神社得到重视，那就到我的夜雀食堂来发光发亮吧！': 'A komainu who guards a shrine. Gentle in nature, always wearing a smile — just seeing her makes fatigue melt away. She also seems good at accounting. Such an excellent girl isn\'t appreciated at her shrine, so come shine at my Night Sparrow Izakaya!',
  '完全无法和铃铃的毒相比！': 'Completely incomparable to Rin-Rin\'s poison!',
  '完美！这才叫完美…适合本姑娘的身份！': 'Perfect! Now THIS is what perfect means... befitting my status!',
  '定价不公也是罪。我只能按规则来付这笔钱。': 'Unfair pricing is also a sin. I can only pay according to the rules.',
  '实在是太好吃啦！以后我每一顿饭都要来这里吃！啊咧，食材还没卖完…？': 'It\'s just too delicious! I\'m eating every meal here from now on! Huh, I haven\'t sold all my ingredients yet...?',
  '实在是让人难以恭维。': 'It really leaves much to be desired.',
  '实际上是个很善良很温和的人啊。明明是"月之头脑"这么大的来头来着…完全感受不到架子呢，不过举手投足之间的高贵风范依然引人侧目就是了。': 'Actually a very kind and gentle person. Despite the grand title of "Brain of the Moon"... I don\'t feel any arrogance at all, though her noble demeanor in every gesture still turns heads.',
  '实际接触后，发现屠自古小姐的性格确实是直爽又豁达，还充满活力。一点儿也不像是怨灵呢。大概是怨恨已经消散得差不多了吧？能让心胸豁达的屠自古小姐变成怨灵，一定是相当痛苦的事情…': 'After actually meeting her, I found Miss Tojiko\'s personality is indeed straightforward, broad-minded, and full of energy. Not at all like a vengeful spirit. Perhaps most of the resentment has faded? Whatever turned the magnanimous Miss Tojiko into a vengeful spirit must have been incredibly painful...',
  '宰客啦！老板娘宰客啦！': 'Price gouging! The boss lady is overcharging!',
  '宵夜还真是一不小心就会吃过量…': 'Late-night snacks really make it easy to overeat...',
  '寄宿在向日葵中的妖精。据说向日葵之所以一直向着太阳，就是因为她们偷偷躲在背后给花转向。这一招把不少人类都骗倒了，是她们引以为傲的绝技。': 'Fairies dwelling in sunflowers. They say sunflowers always face the sun because these fairies secretly turn the flowers from behind. This trick has fooled many humans — it\'s their proudest skill.',
  '寄宿在怪异唐伞上的灵，因为一直没有人使用，不知不觉就付丧神化了。是个只要见到别人被吓了一跳，就会快乐得手舞足蹈的家伙。': 'A spirit dwelling in a strange umbrella — unused for so long, it unconsciously became a tsukumogami. The kind that dances for joy whenever someone gets startled.',
  '寄宿在玫瑰花中的妖精。不知道她们从哪里听说，玫瑰是某颗星球上独一份的、最娇贵的花，于是掀起了要集体搬家的热潮。不过还没有妖精成功。': 'Fairies dwelling in roses. Somehow they heard that roses are the most precious, one-of-a-kind flower on some planet, sparking a collective desire to relocate. But no fairy has succeeded yet.',
  '寄宿在铃兰花中的妖精。每天都在致力于解开"梅蒂欣小姐说的铃铃究竟是谁"之谜，目前的悬赏已经高达九十九颗"史上最圆的石头"，依然没有人能解开谜题。': 'Fairies dwelling in lily of the valley. They work daily to solve the mystery of "who exactly is the Rin-Rin that Miss Medicine talks about." The reward has risen to ninety-nine of the "roundest stones in history," but no one has solved it yet.',
  '对不起！我只能付得起这么多…': 'Sorry! This is all I can afford...',
  '对不起，我会更努力地工作赚钱的…': 'Sorry, I\'ll work harder to earn money...',
  '对喜欢酸味的人来说是味蕾的盛宴，但不喜欢酸味的人就是牙齿和舌头的炸弹！只在一些小众的妖怪中流行的奇怪做法。': 'A feast for the taste buds if you like sour flavors, but a bomb for your teeth and tongue if you don\'t! A strange preparation popular only among niche youkai.',
  '对妖怪来说，没有存在感就和人类患上绝症一样。': 'For youkai, lacking presence is like a human getting a terminal illness.',
  '对实业家而言只有一条规则：以尽可能低的成本，做质量最好的产品，付尽可能高的工资。': 'For an industrialist, there is only one rule: make the best quality product at the lowest possible cost, while paying the highest possible wages.',
  '对待客人要一视同仁。': 'All customers should be treated equally.',
  '对我来说，"创造"是一件神圣的事，为作品注入灵魂，看着它从无到有，真是美妙啊。': 'For me, "creation" is sacred — infusing a work with soul and watching it come into being from nothing is truly wonderful.',
  '对火候要求极其苛刻的一道菜，需聚息凝神地将肉品烤至完美的三分熟。暗红的色调以及极具破坏性的龙卷风形状，带来了山海欲来的压迫感。一口下去，有种仿佛征服了天下的快感。': 'A dish that demands extremely precise heat control — the meat must be grilled with utmost focus to a perfect medium-rare. The dark red hue and destructive tornado shape create an overwhelming sense of power. Each bite feels like conquering the world.',
  '对蕾米莉亚一顿普通下午茶的模仿。区别是本来的熟成牛排被替换成了更贴近小孩子口味的蜜汁牛肉，配套的煎蛋也换成了全熟。顺带一提，最正宗的做法是牛排三分甚至一分熟。': 'An imitation of one of Remilia\'s ordinary afternoon teas. The difference is the aged steak was replaced with honey-glazed beef more suited to a child\'s palate, and the fried egg was changed to fully cooked. By the way, the most authentic preparation calls for rare or even blue steak.',
  '对长者放尊重点，我掉过的P点比你吃过的米还多。': 'Show some respect to your elders — I\'ve lost more P-points than you\'ve eaten grains of rice.',
  '将一定数量的酒水升级成更高一级的酒水。必定升级三杯1级酒水，有75%的概率升级两杯2级酒水，有50%的概率升级一杯3级酒水。': 'Upgrades a certain number of drinks to a higher tier. Guaranteed to upgrade three Level 1 drinks, 75% chance to upgrade two Level 2 drinks, and 50% chance to upgrade one Level 3 drink.',
  '将三文鱼裹上蛋液和面粉，炸至通体金黄，咬一口汁水四溢，隔壁的猫猫都馋哭啦！': 'Coat salmon in egg wash and flour, then fry until golden all over. One bite releases a flood of juices — even the neighbor\'s cat is drooling!',
  '将冰激凌融化在咖啡中的做法，对于怕苦又需要咖啡提神的人来说是再好不过的饮料。': 'Melting ice cream into coffee — the perfect drink for those who dislike bitterness but need the caffeine boost.',
  '将各种高级烤肉堆成小山的料理。无论视觉还是分量上都简单暴力，对于嗅觉灵敏的食客是秒杀级的食谱。': 'A dish piling various premium grilled meats into a mountain. Simple and powerful in both appearance and portion — an instant knockout for diners with a keen sense of smell.',
  '将各种鲜嫩的食材放入多节竹筒蒸熟，寓意节节高升。而春竹翠绿娇艳的样子，既给客人带来视觉味觉上的新意，还蕴含着迎春的美好寓意。': 'Fresh ingredients steamed in multi-sectioned bamboo tubes, symbolizing rising success. The spring bamboo\'s vibrant green brings visual and gustatory novelty while carrying beautiful connotations of welcoming spring.',
  '将在座顾客的预算拉到和在座最富顾客同等的水准。': 'Raises all seated customers\' budgets to match the wealthiest seated customer.',
  '将店内的顾客统统驱赶。': 'Drives all customers out of the shop.',
  '将整块带皮的三文鱼煎至外焦里嫩，配上鲜嫩的竹笋——不过外界这个菜谱一般是芦笋，这也算是幻想乡式的融合菜吧。': 'Pan-fry a whole skin-on salmon fillet until crispy outside and tender inside, served with fresh bamboo shoots — though in the outside world the recipe usually calls for asparagus. This is Gensokyo-style fusion, I suppose.',
  '将新鲜莲子剥壳去芯，煮至软烂，再将黄油和面粉搅拌均匀，最后混合翻炒，用磨具压出美丽的莲花图案，看起来神圣洁白。': 'Shell and core fresh lotus seeds, boil until soft, mix butter and flour evenly, then stir-fry together and press into beautiful lotus patterns with a mold — sacred and pristine white in appearance.',
  '将普通的玉子烧做大许多倍，就是这款在鬼族中流行的巨人玉子烧了！其澎湃的存在感让豪迈之人为其燃烧！': 'Take an ordinary tamagoyaki and make it many times bigger — that\'s this giant tamagoyaki popular among the oni! Its overwhelming presence ignites the passion of bold souls!',
  '将牛排和松露这两种鲜美的食材调味后包裹在酥皮中进行烘焙，让黄油酥皮的香味和牛排蘑菇的鲜美充分融合的极致菜肴。工序繁复，在外界是出了名的难做。': 'Seasoned steak and truffle wrapped in puff pastry and baked — an exquisite dish that fully merges the aroma of buttery pastry with the umami of steak and mushroom. Famously difficult to prepare in the outside world.',
  '将猪身上最嫩的部位，以新鲜的竹筒锯留成节笆，通小孔，灌上菜料和香料，开大火蒸熟后飘出竹子的独特清香。有时间的条件下，在腌渍肉片的时候加点儿清水会更加晶莹润口。': 'The tenderest cut of pork, sealed in fresh bamboo tubes with small holes, filled with vegetables and spices, then steamed over high heat to release bamboo\'s unique fragrance. If you have time, adding a bit of water when marinating makes the meat more translucent and moist.',
  '将番薯下锅炸至金黄，再裹上能拉出细丝的糖衣，最后在抹过油的盘子上滚一圈，既可口又不粘牙。但不能贪嘴，吃太多容易导致胃腹不适。': 'Fry sweet potatoes until golden, coat in a sugar glaze that pulls into fine threads, then roll on an oiled plate — delicious without being sticky. But don\'t overindulge, as eating too much can cause stomach discomfort.',
  '将自身的预算和全场最高预算水平的顾客预算翻转，并在接下来的15秒内持续将除自己以外的所有顾客的预算降低到全场最低预算顾客水平。': 'Swaps own budget with the highest-budget customer, then continuously lowers all other customers\' budgets to the lowest level for the next 15 seconds.',
  '将蘑菇和肉切片后，混入锅里一起炒，是非常基本的家常料理。': 'Slice mushrooms and meat, stir-fry together in a pan — a very basic home-cooked dish.',
  '将虫类的甲壳磨成大碎块，拌入面中，吃起来香脆又下火，有一种别样的异世界猎奇感的奇怪料理。': 'Ground insect shells mixed into noodles — crispy, cooling, and with a strange otherworldly exotic feel.',
  '将食材炒熟之后倒入生米，充分混合米粒和食材香味的外界某个半岛的做法。': 'A cooking method from a certain peninsula in the outside world: stir-fry ingredients, then add raw rice, fully blending the grain with the ingredients\' flavors.',
  '将鲜果蔬菜雕刻成鲜花的模样，虽然材料简单，但却非常考验刀工。': 'Carving fresh fruits and vegetables into flower shapes — though the materials are simple, it demands exceptional knife skills.',
  '将鸡蛋加入海胆蒸至海胆黄变色就可以出锅的简单料理。吃的时候用勺子挖下去，一口一勺，海胆和蛋羹互相融合渗透的美味就在味蕾上蔓延了。': 'A simple dish: steam eggs with sea urchin until the uni changes color. Eat by scooping with a spoon — each bite lets the merged flavors of sea urchin and egg custard spread across your taste buds.',
  '将黄瓜切段后用盐等调味腌制，出现了神奇而难以抗拒的风味。': 'Cut cucumber into pieces and pickle with salt and other seasonings — creating a magical, irresistible flavor.',
  '小人族闭关太久，外面的物价已经这么高了吗？': 'The Inchlings have been secluded too long — have prices outside risen this much?',
  '小人无节，弃本逐末！': 'The petty abandon principles and chase trivialities!',
  '小儿子最近太淘了，上次还抓了一只妖精回家，幸好最后没出什么事。': 'My youngest has been too much lately — last time he even brought a fairy home. Thankfully nothing bad came of it.',
  '小孩子也有小孩子的烦恼，需要借果汁消愁！': 'Kids have their own worries too — they need juice to drown their sorrows!',
  '小看这人世可是会吃苦头的哦？': 'Underestimating the human world will get you in trouble, you know?',
  '小费就当做是你孝敬的保护费了！': 'Consider the tip as your protection money tribute!',
  '小麻雀也挺会宰客的呢。': 'The little sparrow knows how to overcharge too.',
  '小麻雀做得还真不错啊。也来教教我家的兔子嘛。': 'The little sparrow is doing quite well. Come teach my rabbits too.',
  '小麻雀太坏了。': 'The little sparrow is so mean.',
  '小麻雀的生意经做得稍微有点过头了哟。': 'The little sparrow\'s business tactics are a bit excessive.',
  '小麻雀离烟火气有点太近了呢…': 'The little sparrow is a bit too close to the mundane world...',
  '小麻雀，快把酒满上吧。': 'Little sparrow, fill up the drinks.',
  '少见的黑色豆腐，散发着令人难以接近的味道…让人不禁怀疑这真的可以吃吗？但是实际吃过的人表示根本停不下来。': 'Rare black tofu that emits an off-putting smell... making one doubt if it\'s even edible. But those who\'ve actually tried it say they can\'t stop eating it.',
  '就像在知识宝库上轻浮蹦迪一般让人愤怒。': 'As infuriating as frivolously dancing on a treasure trove of knowledge.',
  '就像外行人做内行事一般让人感到焦躁。': 'As irritating as an amateur doing a professional\'s job.',
  '就像终于寻得了公式得出理想结果一般令人振奋！': 'As exhilarating as finally finding the formula and getting the ideal result!',
  '就像胸无点墨的人炫耀自己的知识一般无聊。': 'As boring as an ignorant person showing off their knowledge.',
  '就像邂逅了未解之谜一般令人陶醉！': 'As intoxicating as encountering an unsolved mystery!',
  '就带了这么多啦…': 'This is all I brought...',
  '就是因为有这种美食，我才一直保持人类的进食习惯。': 'It\'s because of food like this that I keep the human habit of eating.',
  '就着酒吃也还行吧。': 'Not bad when eaten with drinks.',
  '就着酒的话，勉强也可以吃两口。': 'With drinks, I can manage a few bites.',
  '就算像露易兹小姐这样满心满意地为了人类而行动的人，也一样无法得到所有人的认同。想要互相理解真不是一件容易的事啊。但就算这样，露易兹小姐也没有打算放弃热爱的工作。希望她的未来能够一直"不负热爱"。': 'Even someone like Miss Louise, who wholeheartedly acts for humans, still can\'t gain everyone\'s approval. Mutual understanding truly isn\'t easy. But even so, Miss Louise has no intention of giving up the work she loves. I hope she can always "stay true to her passion."',
  '就算我们什么都没做也会遭到厌恶吗？': 'Will we be hated even if we haven\'t done anything?',
  '就算把我卖了我也付不起呀！': 'Even if you sold me, I couldn\'t afford it!',
  '就算是作为路上的充饥之物都不够格呀。': 'Not even fit as food to stave off hunger on the road.',
  '就算是咱们座敷童子，偶尔也想要周游世界呢。': 'Even us zashiki-warashi want to travel the world sometimes.',
  '就算是恶作剧也太过分了！': 'Even for a prank, this is too much!',
  '就这种水平也敢开店？': 'You dare open a shop with skills like this?',
  '就连我都忍不住想去信仰你了！': 'Even I can\'t help but want to worship you!',
  '尽管偶尔会露出悲观的一面，但她内心深处却是个爽朗坚毅的妖怪。虽然总是遭遇挫折，却总是花样层出地努力着呢。这份能量，希望我也可以拥有！': 'Though she occasionally shows a pessimistic side, deep down she\'s a cheerful and resolute youkai. Despite constant setbacks, she keeps trying in creative new ways. I wish I could have that kind of energy too!',
  '居住在月之都的人。他们舍弃了寿命，致力于去除污秽以消除生死。但他们并非不老不死，也会因为事故和战争而死去，身上还是微微带有一丝污秽。': 'People who live in the Lunar Capital. They abandoned lifespan, devoting themselves to removing impurities to transcend life and death. But they aren\'t truly immortal — they can die from accidents and wars, and still carry a faint trace of impurity.',
  '居然吃到这么合我心意的菜…一定要有所回报才行！': 'To eat something so perfectly to my taste... I must repay this!',
  '居然在宴席上驱赶客人，真是无趣。': 'Driving customers away during a feast — how dull.',
  '居然在我们最爱的游乐场里建了一个食堂。': 'They actually built a restaurant in our favorite playground.',
  '居然敢把最强的咱赶走。': 'How dare you kick out the strongest!',
  '居然敢赶萤火虫大人？！': 'How dare you kick out the great firefly?!',
  '居然让醉心于让船沉没的妖怪来担任圣辇船的船长，命莲寺真是从里到外都让人无法理解。这家伙能在任何水面引发水难事故，以后得更加注意厨房积水！': 'Having a youkai obsessed with sinking ships serve as captain of the Palanquin Ship — Myouren Temple is incomprehensible inside and out. This one can cause water disasters on any surface. I\'ll need to watch out for kitchen flooding even more!',
  '居然赶走别的客人而不来赶走我，好嫉妒啊。': 'Kicking out other customers but not me — I\'m so jealous.',
  '居然赶走我而不去赶走别的客人，好嫉妒啊。': 'Kicking me out but not other customers — I\'m so jealous.',
  '居然跑来这种地方开店，真是知道怎么给我们增加工作量啊。': 'Opening a shop in a place like this — you really know how to add to our workload.',
  '居然这么对我，就让你看看虫子的厉害！': 'Treating me like this — I\'ll show you the power of bugs!',
  '居酒屋常见的快手汤羹。使用了豆腐来提鲜，最简单又最原始的美味。': 'A quick soup commonly found in izakayas. Tofu is used for umami — the simplest and most primal deliciousness.',
  '居酒屋常见的快手汤羹。来历不明却随处可见的海带在幻想乡出现之初，有人好奇水煮了一下，结果意外地发现有种异样的鲜味，从此便在幻想乡流行开了。': 'A quick soup commonly found in izakayas. When kelp of unknown origin was first found everywhere in Gensokyo, someone curiously boiled it and unexpectedly discovered a unique umami flavor — and it became popular throughout Gensokyo ever since.',
  '居酒屋常见的，使用威士忌、果汁和苏打勾兑的简单调酒，降低了酒精度之后成为了谁都可以享受的饮料。': 'A simple cocktail commonly found in izakayas, mixing whiskey, juice, and soda. With reduced alcohol content, it becomes a drink anyone can enjoy.',
  '居酒屋常见的，使用烧酒、果汁和苏打勾兑的简单调酒，比起果味High Ball更加有日式风格。': 'A simple cocktail commonly found in izakayas, mixing shochu, juice, and soda — more Japanese in style than the fruit High Ball.',
  '展露真相就是为了品尝这样的美味！': 'Revealing the truth is all for tasting flavors like this!',
  '山女小姐原来是类似地底偶像一样的存在呢！不愧是她。不过，和她那可爱的性格相对的是，她的爱好似乎异于常人…': 'Miss Yamame is something like an underground idol! As expected of her. But in contrast to her cute personality, her hobbies seem... unusual...',
  '山姥是没有集团和组织，喜欢单独行动的种族。': 'Yamanba are a species with no groups or organizations — they prefer to act alone.',
  '工作需要再用心一些…': 'Work needs a bit more care...',
  '差一点就要付不起钱被关在瓶子里了…': 'I nearly couldn\'t pay and almost got trapped in a bottle...',
};

// Apply translations
let content = fs.readFileSync('app/data/i18n/en.ts', 'utf8');
let count = 0;
for (const [key, value] of Object.entries(translations)) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`('${escaped}':\\s*)'',`, 'g');
  const newContent = content.replace(regex, `$1'${value.replace(/'/g, "\\'")}',`);
  if (newContent !== content) {
    count++;
    content = newContent;
  }
}
fs.writeFileSync('app/data/i18n/en.ts', content);
console.log(`Updated ${count} translations in app/data/i18n/en.ts`);
console.log(`Expected: ${Object.keys(translations).length}`);
